// World data for location tailoring: every country an author can pick, with currency,
// an approximate exchange rate (units per USD, for deal values; authors can edit the result),
// an income tier (scales deal size) and its largest cities (2 to 7, largest first).
// Name styles are regional, so Deep tailoring can localize team names for any country.

// ---------- regional name styles ----------
// she: at least 6 names, he: at least 15, so a 20-person roster gets unique names.

export const REGIONS = {
  anglo: {
    label: 'English-speaking',
    destination: 'the Bahamas', lunch: 'The Oak Room',
    she: ['Emma Collins', 'Sophie Hart', 'Megan Doyle', 'Laura Fitzgerald', 'Rachel Quinn', 'Natalie Shaw'],
    he: ['James Whitaker', 'Connor Byrne', 'Matthew Hughes', 'Andrew Sutton', 'Patrick Nolan', 'Samuel Ford', 'Luke Barrett', 'Adam Kerr', 'Henry Walsh', 'Joshua Reid', 'Dylan Hayes', 'Aaron Blake', 'Christopher Dunn', 'Michael Grant', 'Benjamin Cole'],
  },
  hispanic: {
    label: 'Spanish-speaking',
    destination: 'Cancún', lunch: 'La Casona',
    she: ['María Fernández', 'Lucía Morales', 'Carmen Ruiz', 'Valentina Torres', 'Sofía Castillo', 'Isabel Navarro'],
    he: ['Carlos Mendoza', 'Javier Ortiz', 'Diego Herrera', 'Alejandro Vargas', 'Miguel Romero', 'Andrés Salazar', 'Luis Gutiérrez', 'Pablo Ramos', 'Fernando Cruz', 'Ricardo Delgado', 'Sergio Molina', 'Mateo Rojas', 'Tomás Aguilar', 'Eduardo Paredes', 'Gabriel Flores'],
  },
  lusophone: {
    label: 'Portuguese-speaking',
    destination: 'Fernando de Noronha', lunch: 'Casa do Sabor',
    she: ['Ana Oliveira', 'Beatriz Santos', 'Mariana Costa', 'Juliana Ferreira', 'Carolina Almeida', 'Inês Carvalho'],
    he: ['João Silva', 'Pedro Souza', 'Lucas Rodrigues', 'Rafael Pereira', 'Gustavo Lima', 'Thiago Gomes', 'Bruno Martins', 'Felipe Ribeiro', 'André Barbosa', 'Rodrigo Araújo', 'Diogo Teixeira', 'Marcelo Cardoso', 'Tiago Mendes', 'Vinícius Rocha', 'Eduardo Nunes'],
  },
  francophone: {
    label: 'French-speaking',
    destination: 'Martinique', lunch: 'Le Petit Bistrot',
    she: ['Camille Dubois', 'Chloé Martin', 'Léa Bernard', 'Manon Laurent', 'Inès Moreau', 'Aïcha Diallo'],
    he: ['Julien Lefebvre', 'Thomas Girard', 'Antoine Rousseau', 'Nicolas Fournier', 'Hugo Lambert', 'Mathieu Mercier', 'Olivier Blanc', 'Maxime Faure', 'Pierre Garnier', 'Karim Benali', 'Mamadou Traoré', 'Louis Chevalier', 'Étienne Roux', 'Sébastien Perrin', 'Yann Morel'],
  },
  germanic: {
    label: 'German-speaking',
    destination: 'Mallorca', lunch: 'Gasthaus zur Linde',
    she: ['Anna Schneider', 'Lena Fischer', 'Julia Weber', 'Sophie Wagner', 'Elif Yilmaz', 'Laura Becker'],
    he: ['Lukas Meyer', 'Jonas Hoffmann', 'Felix Schulz', 'Tobias Koch', 'Maximilian Richter', 'Leon Klein', 'Paul Wolf', 'David Neumann', 'Can Demir', 'Niklas Braun', 'Florian Zimmermann', 'Stefan Krüger', 'Moritz Lange', 'Jan Hartung', 'Tim Schröder'],
  },
  dutch: {
    label: 'Dutch-speaking',
    destination: 'Curaçao', lunch: 'Café de Kroon',
    she: ['Sanne de Vries', 'Fleur Jansen', 'Lotte Bakker', 'Eva Visser', 'Anouk Smit', 'Noor el Amrani'],
    he: ['Daan van Dijk', 'Bram de Boer', 'Lars Mulder', 'Thijs Bos', 'Ruben Vos', 'Sem Peters', 'Jesse Hendriks', 'Milan Dekker', 'Stijn van Leeuwen', 'Koen Brouwer', 'Bas de Groot', 'Joris Kok', 'Wouter Jacobs', 'Niels Vermeulen', 'Pieter Maas'],
  },
  nordic: {
    label: 'Nordic',
    destination: 'the Canary Islands', lunch: 'Nordhavn Kitchen',
    she: ['Emma Johansson', 'Ingrid Larsen', 'Sofia Nieminen', 'Freja Nielsen', 'Maja Andersson', 'Sigrid Berg'],
    he: ['Erik Lindqvist', 'Lars Hansen', 'Mikkel Jensen', 'Oskar Karlsson', 'Anders Nilsson', 'Jonas Eriksen', 'Mikael Virtanen', 'Henrik Dahl', 'Magnus Olsen', 'Elias Korhonen', 'Nils Pedersen', 'Johan Persson', 'Kasper Holm', 'Sindre Haugen', 'Viktor Lund'],
  },
  italian: {
    label: 'Italian-speaking',
    destination: 'Sardinia', lunch: 'Trattoria da Enzo',
    she: ['Giulia Rossi', 'Francesca Bianchi', 'Chiara Romano', 'Sara Colombo', 'Elena Ricci', 'Martina Greco'],
    he: ['Marco Ferrari', 'Luca Esposito', 'Alessandro Russo', 'Matteo Bruno', 'Davide Gallo', 'Andrea Conti', 'Stefano De Luca', 'Lorenzo Marino', 'Simone Costa', 'Federico Fontana', 'Riccardo Rizzo', 'Giorgio Lombardi', 'Paolo Moretti', 'Nicola Barbieri', 'Fabio Caruso'],
  },
  greek: {
    label: 'Greek-speaking',
    destination: 'Santorini', lunch: 'Taverna Olympia',
    she: ['Eleni Papadopoulou', 'Maria Georgiou', 'Sofia Nikolaou', 'Katerina Dimitriou', 'Anna Christodoulou', 'Ioanna Pappa'],
    he: ['Giorgos Papadakis', 'Nikos Konstantinou', 'Dimitris Alexiou', 'Kostas Vlachos', 'Yannis Economou', 'Panagiotis Makris', 'Christos Antoniou', 'Stavros Karalis', 'Alexandros Petrou', 'Vasilis Theodorou', 'Michalis Lambrou', 'Andreas Stavrou', 'Spyros Kouris', 'Thanos Raptis', 'Stelios Marinos'],
  },
  centraleurope: {
    label: 'Central and Eastern European',
    destination: 'the Adriatic coast', lunch: 'Stara Kuchnia',
    she: ['Anna Kowalska', 'Katarzyna Nowak', 'Elena Petrova', 'Tereza Novotná', 'Marta Horvat', 'Ioana Popescu'],
    he: ['Piotr Wiśniewski', 'Tomasz Lewandowski', 'Jan Dvořák', 'Marek Kováč', 'Ivan Petrović', 'Andrei Ionescu', 'Nikola Jovanović', 'Pavel Novák', 'Mateusz Zieliński', 'Luka Kovačević', 'Bogdan Kowalczyk', 'Milan Horvat', 'Gábor Nagy', 'Tamás Szabó', 'Radu Dumitru'],
  },
  eastslavic: {
    label: 'Russian and Ukrainian-speaking',
    destination: 'the Black Sea coast', lunch: 'Traktir Samovar',
    she: ['Olga Ivanova', 'Natalia Sokolova', 'Yulia Kovalenko', 'Anastasia Popova', 'Irina Volkova', 'Daria Melnyk'],
    he: ['Alexei Smirnov', 'Dmitri Volkov', 'Sergei Morozov', 'Oleksandr Shevchenko', 'Andrei Kuznetsov', 'Mikhail Orlov', 'Pavel Lebedev', 'Ivan Bondarenko', 'Nikolai Fedorov', 'Artem Boyko', 'Maxim Pavlov', 'Yuri Tkachenko', 'Roman Sidorov', 'Vladimir Egorov', 'Denis Kravets'],
  },
  arabic: {
    label: 'Arabic-speaking',
    destination: 'the Red Sea coast', lunch: 'Al Diwan',
    she: ['Fatima Al Hashimi', 'Layla Haddad', 'Noor Rahman', 'Aisha Karim', 'Mariam Yousef', 'Rania Saeed'],
    he: ['Ahmed Al Falasi', 'Yousef Nasser', 'Rashid Al Ketbi', 'Omar Farouk', 'Tariq Aziz', 'Hamza Saleh', 'Karim Boutros', 'Faisal Qasim', 'Salem Al Nuaimi', 'Ali Hassan', 'Ziad Khoury', 'Khalid Mansour', 'Samir Haddad', 'Nabil Amin', 'Walid Jaber'],
  },
  turkic: {
    label: 'Turkish and Central Asian',
    destination: 'Bodrum', lunch: 'Lokanta Mavi',
    she: ['Elif Kaya', 'Zeynep Demir', 'Ayşe Yıldız', 'Aigerim Nurlanova', 'Leyla Mammadova', 'Selin Arslan'],
    he: ['Mehmet Öztürk', 'Emre Çelik', 'Burak Aydın', 'Can Şahin', 'Murat Koç', 'Oğuz Kurt', 'Serkan Polat', 'Arman Bekov', 'Rustam Aliyev', 'Timur Sadykov', 'Kerem Doğan', 'Yusuf Aksoy', 'Baurzhan Omarov', 'Farid Huseynov', 'Deniz Erdem'],
  },
  persian: {
    label: 'Persian-speaking',
    destination: 'Kish Island', lunch: 'Shandiz Garden',
    she: ['Shirin Ahmadi', 'Maryam Hosseini', 'Nazanin Karimi', 'Parisa Rahimi', 'Leila Moradi', 'Sara Jafari'],
    he: ['Reza Tehrani', 'Ali Rezaei', 'Mohammad Sadeghi', 'Hossein Mousavi', 'Amir Kazemi', 'Babak Nouri', 'Farhad Ebrahimi', 'Kaveh Shirazi', 'Omid Rostami', 'Arash Bagheri', 'Dariush Hashemi', 'Navid Asadi', 'Saeed Mohammadi', 'Peyman Zand', 'Kian Najafi'],
  },
  hebrew: {
    label: 'Hebrew-speaking',
    destination: 'Eilat', lunch: 'Café Tamar',
    she: ['Noa Levi', 'Tamar Cohen', 'Maya Friedman', 'Shira Mizrahi', 'Yael Peretz', 'Adi Biton'],
    he: ['Yosef Katz', 'Daniel Avraham', 'Omer Shapiro', 'Itai Ben-David', 'Eitan Goldberg', 'Amit Dahan', 'Ronen Azoulay', 'Gil Rosen', 'Yoav Segal', 'Nadav Harel', 'Lior Klein', 'Tomer Weiss', 'Ariel Gabay', 'Oren Malka', 'Uri Stern'],
  },
  southasian: {
    label: 'South Asian',
    destination: 'the Maldives', lunch: 'Saffron Court',
    she: ['Priya Nair', 'Kavya Reddy', 'Sneha Kulkarni', 'Aditi Sharma', 'Meera Pillai', 'Ayesha Siddiqui'],
    he: ['Rohan Verma', 'Arjun Menon', 'Vikram Joshi', 'Karan Malhotra', 'Siddharth Rao', 'Amit Deshpande', 'Nikhil Gupta', 'Rahul Chawla', 'Varun Iyer', 'Manish Patel', 'Sameer Khan', 'Deepak Singh', 'Imran Qureshi', 'Tanvir Hossain', 'Kasun Perera'],
  },
  chinese: {
    label: 'Chinese-speaking',
    destination: 'Sanya', lunch: 'Jade Garden',
    she: ['Wang Fang', 'Li Na', 'Zhang Wenjing', 'Chen Xiaoyu', 'Liu Yan', 'Zhao Min'],
    he: ['Wang Jun', 'Li Qiang', 'Zhang Hao', 'Liu Yang', 'Chen Jie', 'Yang Lei', 'Huang Wei', 'Zhou Tao', 'Wu Gang', 'Xu Ming', 'Sun Peng', 'Ma Chao', 'Hu Bin', 'Guo Feng', 'Lin Zhi'],
  },
  korean: {
    label: 'Korean',
    destination: 'Jeju Island', lunch: 'Hanok Table',
    she: ['Kim Ji-woo', 'Lee Seo-yeon', 'Park Min-ji', 'Choi Soo-ah', 'Jung Ha-eun', 'Kang Yoo-na'],
    he: ['Kim Min-jun', 'Lee Seo-jun', 'Park Do-hyun', 'Choi Ji-hoon', 'Jung Woo-jin', 'Kang Hyun-woo', 'Cho Sung-min', 'Yoon Tae-yang', 'Jang Dong-hyun', 'Lim Jae-won', 'Han Seung-ho', 'Oh Jun-young', 'Seo Joon-ho', 'Shin Dae-hyun', 'Kwon Min-seok'],
  },
  japanese: {
    label: 'Japanese',
    destination: 'Okinawa', lunch: 'Sakura Dining',
    she: ['Yui Tanaka', 'Aoi Suzuki', 'Mei Takahashi', 'Rina Watanabe', 'Sakura Ito', 'Hana Kobayashi'],
    he: ['Haruto Yamamoto', 'Ren Nakamura', 'Sota Kato', 'Yuto Yoshida', 'Daiki Yamada', 'Kaito Sasaki', 'Riku Matsumoto', 'Takumi Inoue', 'Shota Kimura', 'Kenta Hayashi', 'Hiroshi Shimizu', 'Naoki Mori', 'Ryo Ikeda', 'Yuki Hashimoto', 'Taro Ishikawa'],
  },
  southeastasian: {
    label: 'Southeast Asian',
    destination: 'Langkawi', lunch: 'Kampung Kitchen',
    she: ['Siti Rahmawati', 'Nguyen Thi Lan', 'Maria Santos', 'Pimchanok Srisuk', 'Nur Aina', 'Dewi Lestari'],
    he: ['Budi Santoso', 'Tran Van Minh', 'Jose Reyes', 'Somchai Wongsa', 'Ahmad Faizal', 'Rizal Hidayat', 'Pham Quoc Huy', 'Mark Villanueva', 'Anan Chaiyaporn', 'Hafiz Abdullah', 'Le Hoang Nam', 'Andre Pangilinan', 'Arif Wibowo', 'Thanawat Suksai', 'Zul Hakim'],
  },
  african: {
    label: 'Sub-Saharan African',
    destination: 'Zanzibar', lunch: 'Savannah Grill',
    she: ['Amara Okafor', 'Wanjiru Kamau', 'Ama Mensah', 'Thandiwe Ndlovu', 'Fatou Sow', 'Chipo Moyo'],
    he: ['Chinedu Eze', 'Kwame Asante', 'Tendai Mutasa', 'Sipho Dlamini', 'Emeka Obi', 'Kofi Boateng', 'Juma Otieno', 'Tunde Adeyemi', 'Moses Kiprono', 'Themba Nkosi', 'Abdi Hassan', 'Yaw Owusu', 'Babajide Ogunleye', 'Musa Bello', 'Kagiso Molefe'],
  },
};

// Income tier to deal-size factor (1 high, 2 upper-middle, 3 lower-middle, 4 low income).
export const TIER_FACTOR = { 1: 1, 2: 0.6, 3: 0.4, 4: 0.25 };

// [code, name, region, currency, units per USD (approximate), tier, cities largest first]
const RAW = [
  ['AF', 'Afghanistan', 'persian', 'AFN', 70, 4, 'Kabul|Kandahar|Herat|Mazar-i-Sharif|Jalalabad'],
  ['AL', 'Albania', 'centraleurope', 'ALL', 92, 2, 'Tirana|Durrës|Vlorë|Elbasan|Shkodër'],
  ['DZ', 'Algeria', 'arabic', 'DZD', 134, 3, 'Algiers|Oran|Constantine|Annaba|Blida|Batna'],
  ['AD', 'Andorra', 'hispanic', 'EUR', 0.92, 1, 'Andorra la Vella|Escaldes-Engordany|Encamp'],
  ['AO', 'Angola', 'lusophone', 'AOA', 900, 3, 'Luanda|Huambo|Lobito|Benguela|Lubango'],
  ['AG', 'Antigua and Barbuda', 'anglo', 'XCD', 2.7, 1, "St. John's|All Saints|Liberta"],
  ['AR', 'Argentina', 'hispanic', 'ARS', 1000, 2, 'Buenos Aires|Córdoba|Rosario|Mendoza|La Plata|San Miguel de Tucumán|Mar del Plata'],
  ['AM', 'Armenia', 'eastslavic', 'AMD', 390, 2, 'Yerevan|Gyumri|Vanadzor|Vagharshapat'],
  ['AU', 'Australia', 'anglo', 'AUD', 1.52, 1, 'Sydney|Melbourne|Brisbane|Perth|Adelaide|Gold Coast|Canberra'],
  ['AT', 'Austria', 'germanic', 'EUR', 0.92, 1, 'Vienna|Graz|Linz|Salzburg|Innsbruck|Klagenfurt'],
  ['AZ', 'Azerbaijan', 'turkic', 'AZN', 1.7, 2, 'Baku|Ganja|Sumqayit|Mingachevir'],
  ['BS', 'Bahamas', 'anglo', 'BSD', 1, 1, 'Nassau|Freeport|West End'],
  ['BH', 'Bahrain', 'arabic', 'BHD', 0.376, 1, 'Manama|Riffa|Muharraq|Hamad Town'],
  ['BD', 'Bangladesh', 'southasian', 'BDT', 120, 3, 'Dhaka|Chittagong|Khulna|Rajshahi|Sylhet|Gazipur|Narayanganj'],
  ['BB', 'Barbados', 'anglo', 'BBD', 2, 1, 'Bridgetown|Speightstown|Oistins'],
  ['BY', 'Belarus', 'eastslavic', 'BYN', 3.3, 2, 'Minsk|Gomel|Mogilev|Vitebsk|Grodno|Brest'],
  ['BE', 'Belgium', 'dutch', 'EUR', 0.92, 1, 'Brussels|Antwerp|Ghent|Charleroi|Liège|Bruges'],
  ['BZ', 'Belize', 'anglo', 'BZD', 2, 2, 'Belize City|San Ignacio|Belmopan|Orange Walk'],
  ['BJ', 'Benin', 'francophone', 'XOF', 600, 3, 'Cotonou|Porto-Novo|Parakou|Abomey-Calavi|Djougou'],
  ['BT', 'Bhutan', 'southasian', 'BTN', 84, 3, 'Thimphu|Phuntsholing|Paro|Gelephu'],
  ['BO', 'Bolivia', 'hispanic', 'BOB', 6.9, 3, 'Santa Cruz de la Sierra|El Alto|La Paz|Cochabamba|Sucre|Oruro'],
  ['BA', 'Bosnia and Herzegovina', 'centraleurope', 'BAM', 1.8, 2, 'Sarajevo|Banja Luka|Tuzla|Zenica|Mostar'],
  ['BW', 'Botswana', 'african', 'BWP', 13.5, 2, 'Gaborone|Francistown|Molepolole|Maun'],
  ['BR', 'Brazil', 'lusophone', 'BRL', 5.5, 2, 'São Paulo|Rio de Janeiro|Brasília|Salvador|Fortaleza|Belo Horizonte|Manaus'],
  ['BN', 'Brunei', 'southeastasian', 'BND', 1.35, 1, 'Bandar Seri Begawan|Kuala Belait|Seria|Tutong'],
  ['BG', 'Bulgaria', 'centraleurope', 'BGN', 1.8, 2, 'Sofia|Plovdiv|Varna|Burgas|Ruse|Stara Zagora'],
  ['BF', 'Burkina Faso', 'francophone', 'XOF', 600, 4, 'Ouagadougou|Bobo-Dioulasso|Koudougou|Banfora'],
  ['BI', 'Burundi', 'francophone', 'BIF', 2900, 4, 'Gitega|Bujumbura|Ngozi|Muyinga'],
  ['CV', 'Cabo Verde', 'lusophone', 'CVE', 101, 3, 'Praia|Mindelo|Santa Maria|Assomada'],
  ['KH', 'Cambodia', 'southeastasian', 'KHR', 4050, 3, 'Phnom Penh|Siem Reap|Battambang|Sihanoukville|Kampong Cham'],
  ['CM', 'Cameroon', 'francophone', 'XAF', 600, 3, 'Douala|Yaoundé|Garoua|Bamenda|Bafoussam|Maroua'],
  ['CA', 'Canada', 'anglo', 'CAD', 1.37, 1, 'Toronto|Montreal|Vancouver|Calgary|Edmonton|Ottawa|Winnipeg'],
  ['CF', 'Central African Republic', 'francophone', 'XAF', 600, 4, 'Bangui|Bimbo|Berbérati|Carnot'],
  ['TD', 'Chad', 'francophone', 'XAF', 600, 4, "N'Djamena|Moundou|Abéché|Sarh"],
  ['CL', 'Chile', 'hispanic', 'CLP', 940, 1, 'Santiago|Valparaíso|Concepción|Antofagasta|La Serena|Temuco'],
  ['CN', 'China', 'chinese', 'CNY', 7.2, 2, 'Shanghai|Beijing|Shenzhen|Guangzhou|Chengdu|Chongqing|Hangzhou'],
  ['CO', 'Colombia', 'hispanic', 'COP', 4000, 2, 'Bogotá|Medellín|Cali|Barranquilla|Cartagena|Bucaramanga'],
  ['KM', 'Comoros', 'francophone', 'KMF', 450, 3, 'Moroni|Mutsamudu|Fomboni'],
  ['CG', 'Congo', 'francophone', 'XAF', 600, 3, 'Brazzaville|Pointe-Noire|Dolisie|Nkayi'],
  ['CD', 'Congo (Democratic Republic)', 'francophone', 'CDF', 2800, 4, 'Kinshasa|Lubumbashi|Mbuji-Mayi|Kananga|Kisangani|Goma'],
  ['CR', 'Costa Rica', 'hispanic', 'CRC', 510, 2, 'San José|Alajuela|Cartago|Heredia|Liberia|Puntarenas'],
  ['CI', "Côte d'Ivoire", 'francophone', 'XOF', 600, 3, 'Abidjan|Bouaké|Yamoussoukro|Daloa|San-Pédro|Korhogo'],
  ['HR', 'Croatia', 'centraleurope', 'EUR', 0.92, 1, 'Zagreb|Split|Rijeka|Osijek|Zadar'],
  ['CU', 'Cuba', 'hispanic', 'CUP', 24, 2, 'Havana|Santiago de Cuba|Camagüey|Holguín|Santa Clara'],
  ['CY', 'Cyprus', 'greek', 'EUR', 0.92, 1, 'Nicosia|Limassol|Larnaca|Paphos'],
  ['CZ', 'Czechia', 'centraleurope', 'CZK', 23, 1, 'Prague|Brno|Ostrava|Plzeň|Liberec|Olomouc'],
  ['DK', 'Denmark', 'nordic', 'DKK', 6.9, 1, 'Copenhagen|Aarhus|Odense|Aalborg|Esbjerg'],
  ['DJ', 'Djibouti', 'arabic', 'DJF', 178, 3, 'Djibouti City|Ali Sabieh|Tadjourah|Obock'],
  ['DM', 'Dominica', 'anglo', 'XCD', 2.7, 2, 'Roseau|Portsmouth|Marigot'],
  ['DO', 'Dominican Republic', 'hispanic', 'DOP', 60, 2, 'Santo Domingo|Santiago de los Caballeros|San Pedro de Macorís|La Romana|Punta Cana'],
  ['EC', 'Ecuador', 'hispanic', 'USD', 1, 2, 'Guayaquil|Quito|Cuenca|Santo Domingo|Machala|Manta'],
  ['EG', 'Egypt', 'arabic', 'EGP', 49, 3, 'Cairo|Alexandria|Giza|Shubra El Kheima|Port Said|Suez|Luxor'],
  ['SV', 'El Salvador', 'hispanic', 'USD', 1, 2, 'San Salvador|Santa Ana|San Miguel|Soyapango'],
  ['GQ', 'Equatorial Guinea', 'hispanic', 'XAF', 600, 2, 'Malabo|Bata|Ebebiyín'],
  ['ER', 'Eritrea', 'african', 'ERN', 15, 4, 'Asmara|Keren|Massawa|Assab'],
  ['EE', 'Estonia', 'nordic', 'EUR', 0.92, 1, 'Tallinn|Tartu|Narva|Pärnu'],
  ['SZ', 'Eswatini', 'african', 'SZL', 18, 3, 'Mbabane|Manzini|Lobamba|Siteki'],
  ['ET', 'Ethiopia', 'african', 'ETB', 120, 4, 'Addis Ababa|Dire Dawa|Mekelle|Gondar|Hawassa|Bahir Dar|Adama'],
  ['FJ', 'Fiji', 'anglo', 'FJD', 2.25, 2, 'Suva|Lautoka|Nadi|Labasa'],
  ['FI', 'Finland', 'nordic', 'EUR', 0.92, 1, 'Helsinki|Espoo|Tampere|Vantaa|Oulu|Turku'],
  ['FR', 'France', 'francophone', 'EUR', 0.92, 1, 'Paris|Marseille|Lyon|Toulouse|Nice|Nantes|Lille'],
  ['GA', 'Gabon', 'francophone', 'XAF', 600, 2, 'Libreville|Port-Gentil|Franceville|Oyem'],
  ['GM', 'Gambia', 'african', 'GMD', 70, 4, 'Serekunda|Banjul|Brikama|Bakau'],
  ['GE', 'Georgia', 'eastslavic', 'GEL', 2.7, 2, 'Tbilisi|Batumi|Kutaisi|Rustavi'],
  ['DE', 'Germany', 'germanic', 'EUR', 0.92, 1, 'Berlin|Hamburg|Munich|Cologne|Frankfurt|Stuttgart|Düsseldorf'],
  ['GH', 'Ghana', 'african', 'GHS', 15, 3, 'Accra|Kumasi|Tamale|Takoradi|Cape Coast|Tema'],
  ['GR', 'Greece', 'greek', 'EUR', 0.92, 1, 'Athens|Thessaloniki|Patras|Heraklion|Larissa|Volos'],
  ['GD', 'Grenada', 'anglo', 'XCD', 2.7, 2, "St. George's|Gouyave|Grenville"],
  ['GT', 'Guatemala', 'hispanic', 'GTQ', 7.7, 2, 'Guatemala City|Mixco|Villa Nueva|Quetzaltenango|Escuintla'],
  ['GN', 'Guinea', 'francophone', 'GNF', 8600, 4, 'Conakry|Nzérékoré|Kankan|Kindia'],
  ['GW', 'Guinea-Bissau', 'lusophone', 'XOF', 600, 4, 'Bissau|Bafatá|Gabú'],
  ['GY', 'Guyana', 'anglo', 'GYD', 209, 1, 'Georgetown|Linden|New Amsterdam'],
  ['HT', 'Haiti', 'francophone', 'HTG', 132, 3, 'Port-au-Prince|Cap-Haïtien|Gonaïves|Les Cayes'],
  ['HN', 'Honduras', 'hispanic', 'HNL', 25, 3, 'Tegucigalpa|San Pedro Sula|La Ceiba|Choloma'],
  ['HK', 'Hong Kong', 'chinese', 'HKD', 7.8, 1, 'Hong Kong|Kowloon|Sha Tin|Tsuen Wan'],
  ['HU', 'Hungary', 'centraleurope', 'HUF', 360, 1, 'Budapest|Debrecen|Szeged|Miskolc|Pécs|Győr'],
  ['IS', 'Iceland', 'nordic', 'ISK', 138, 1, 'Reykjavík|Kópavogur|Hafnarfjörður|Akureyri'],
  ['IN', 'India', 'southasian', 'INR', 83, 3, 'Mumbai|Delhi|Bengaluru|Hyderabad|Chennai|Kolkata|Pune'],
  ['ID', 'Indonesia', 'southeastasian', 'IDR', 16000, 2, 'Jakarta|Surabaya|Bandung|Medan|Semarang|Makassar|Palembang'],
  ['IR', 'Iran', 'persian', 'IRR', 42000, 3, 'Tehran|Mashhad|Isfahan|Karaj|Shiraz|Tabriz|Qom'],
  ['IQ', 'Iraq', 'arabic', 'IQD', 1310, 2, 'Baghdad|Basra|Mosul|Erbil|Najaf|Karbala|Sulaymaniyah'],
  ['IE', 'Ireland', 'anglo', 'EUR', 0.92, 1, 'Dublin|Cork|Limerick|Galway|Waterford'],
  ['IL', 'Israel', 'hebrew', 'ILS', 3.7, 1, 'Jerusalem|Tel Aviv|Haifa|Rishon LeZion|Petah Tikva|Beersheba'],
  ['IT', 'Italy', 'italian', 'EUR', 0.92, 1, 'Rome|Milan|Naples|Turin|Palermo|Bologna|Florence'],
  ['JM', 'Jamaica', 'anglo', 'JMD', 157, 2, 'Kingston|Montego Bay|Spanish Town|Portmore|Mandeville'],
  ['JP', 'Japan', 'japanese', 'JPY', 150, 1, 'Tokyo|Yokohama|Osaka|Nagoya|Sapporo|Fukuoka|Kobe'],
  ['JO', 'Jordan', 'arabic', 'JOD', 0.71, 2, 'Amman|Zarqa|Irbid|Aqaba|Madaba'],
  ['KZ', 'Kazakhstan', 'turkic', 'KZT', 480, 2, 'Almaty|Astana|Shymkent|Karaganda|Aktobe|Taraz'],
  ['KE', 'Kenya', 'african', 'KES', 129, 3, 'Nairobi|Mombasa|Kisumu|Nakuru|Eldoret|Thika'],
  ['KI', 'Kiribati', 'anglo', 'AUD', 1.52, 3, 'South Tarawa|Betio|Bikenibeu'],
  ['XK', 'Kosovo', 'centraleurope', 'EUR', 0.92, 2, 'Pristina|Prizren|Ferizaj|Peja|Gjakova'],
  ['KW', 'Kuwait', 'arabic', 'KWD', 0.31, 1, 'Kuwait City|Hawalli|Al Ahmadi|Salmiya|Jahra'],
  ['KG', 'Kyrgyzstan', 'turkic', 'KGS', 87, 3, 'Bishkek|Osh|Jalal-Abad|Karakol'],
  ['LA', 'Laos', 'southeastasian', 'LAK', 21800, 3, 'Vientiane|Pakse|Savannakhet|Luang Prabang'],
  ['LV', 'Latvia', 'nordic', 'EUR', 0.92, 1, 'Riga|Daugavpils|Liepāja|Jelgava'],
  ['LB', 'Lebanon', 'arabic', 'LBP', 89500, 3, 'Beirut|Tripoli|Sidon|Tyre|Zahlé'],
  ['LS', 'Lesotho', 'african', 'LSL', 18, 3, 'Maseru|Teyateyaneng|Mafeteng|Hlotse'],
  ['LR', 'Liberia', 'african', 'LRD', 195, 4, 'Monrovia|Gbarnga|Kakata|Buchanan'],
  ['LY', 'Libya', 'arabic', 'LYD', 4.8, 2, 'Tripoli|Benghazi|Misrata|Bayda|Zawiya'],
  ['LI', 'Liechtenstein', 'germanic', 'CHF', 0.88, 1, 'Schaan|Vaduz|Triesen|Balzers'],
  ['LT', 'Lithuania', 'nordic', 'EUR', 0.92, 1, 'Vilnius|Kaunas|Klaipėda|Šiauliai|Panevėžys'],
  ['LU', 'Luxembourg', 'francophone', 'EUR', 0.92, 1, 'Luxembourg City|Esch-sur-Alzette|Differdange|Dudelange'],
  ['MG', 'Madagascar', 'francophone', 'MGA', 4500, 4, 'Antananarivo|Toamasina|Antsirabe|Fianarantsoa|Mahajanga'],
  ['MW', 'Malawi', 'african', 'MWK', 1730, 4, 'Lilongwe|Blantyre|Mzuzu|Zomba'],
  ['MY', 'Malaysia', 'southeastasian', 'MYR', 4.5, 2, 'Kuala Lumpur|Johor Bahru|George Town|Ipoh|Shah Alam|Kota Kinabalu|Kuching'],
  ['MV', 'Maldives', 'southasian', 'MVR', 15.4, 2, 'Malé|Addu City|Fuvahmulah|Kulhudhuffushi'],
  ['ML', 'Mali', 'francophone', 'XOF', 600, 4, 'Bamako|Sikasso|Ségou|Mopti|Kayes'],
  ['MT', 'Malta', 'italian', 'EUR', 0.92, 1, 'Birkirkara|Mosta|Qormi|Valletta|Sliema'],
  ['MH', 'Marshall Islands', 'anglo', 'USD', 1, 2, 'Majuro|Ebeye|Laura'],
  ['MR', 'Mauritania', 'arabic', 'MRU', 40, 3, 'Nouakchott|Nouadhibou|Kiffa|Kaédi'],
  ['MU', 'Mauritius', 'francophone', 'MUR', 46, 2, 'Port Louis|Vacoas-Phoenix|Beau Bassin-Rose Hill|Curepipe|Quatre Bornes'],
  ['MX', 'Mexico', 'hispanic', 'MXN', 18, 2, 'Mexico City|Guadalajara|Monterrey|Puebla|Tijuana|León|Querétaro'],
  ['FM', 'Micronesia', 'anglo', 'USD', 1, 3, 'Weno|Palikir|Kolonia|Tofol'],
  ['MD', 'Moldova', 'centraleurope', 'MDL', 17.8, 2, 'Chișinău|Bălți|Tiraspol|Bender|Cahul'],
  ['MC', 'Monaco', 'francophone', 'EUR', 0.92, 1, 'Monaco|Monte Carlo|La Condamine|Fontvieille'],
  ['MN', 'Mongolia', 'turkic', 'MNT', 3400, 2, 'Ulaanbaatar|Erdenet|Darkhan|Choibalsan'],
  ['ME', 'Montenegro', 'centraleurope', 'EUR', 0.92, 2, 'Podgorica|Nikšić|Herceg Novi|Bar|Budva'],
  ['MA', 'Morocco', 'arabic', 'MAD', 10, 3, 'Casablanca|Rabat|Fez|Marrakesh|Tangier|Agadir|Meknes'],
  ['MZ', 'Mozambique', 'lusophone', 'MZN', 64, 4, 'Maputo|Matola|Nampula|Beira|Chimoio|Quelimane'],
  ['MM', 'Myanmar', 'southeastasian', 'MMK', 2100, 3, 'Yangon|Mandalay|Naypyidaw|Mawlamyine|Bago'],
  ['NA', 'Namibia', 'african', 'NAD', 18, 2, 'Windhoek|Walvis Bay|Swakopmund|Rundu|Oshakati'],
  ['NR', 'Nauru', 'anglo', 'AUD', 1.52, 1, 'Yaren|Denigomodu|Meneng'],
  ['NP', 'Nepal', 'southasian', 'NPR', 134, 3, 'Kathmandu|Pokhara|Lalitpur|Bharatpur|Biratnagar|Birgunj'],
  ['NL', 'Netherlands', 'dutch', 'EUR', 0.92, 1, 'Amsterdam|Rotterdam|The Hague|Utrecht|Eindhoven|Groningen|Tilburg'],
  ['NZ', 'New Zealand', 'anglo', 'NZD', 1.65, 1, 'Auckland|Wellington|Christchurch|Hamilton|Tauranga|Dunedin'],
  ['NI', 'Nicaragua', 'hispanic', 'NIO', 36.8, 3, 'Managua|León|Masaya|Chinandega|Matagalpa'],
  ['NE', 'Niger', 'francophone', 'XOF', 600, 4, 'Niamey|Zinder|Maradi|Agadez|Tahoua'],
  ['NG', 'Nigeria', 'african', 'NGN', 1500, 3, 'Lagos|Kano|Ibadan|Abuja|Port Harcourt|Benin City|Kaduna'],
  ['KP', 'North Korea', 'korean', 'KPW', 900, 4, 'Pyongyang|Hamhung|Chongjin|Nampo|Wonsan'],
  ['MK', 'North Macedonia', 'centraleurope', 'MKD', 57, 2, 'Skopje|Bitola|Kumanovo|Prilep|Tetovo'],
  ['NO', 'Norway', 'nordic', 'NOK', 10.8, 1, 'Oslo|Bergen|Trondheim|Stavanger|Drammen|Tromsø'],
  ['OM', 'Oman', 'arabic', 'OMR', 0.385, 1, 'Muscat|Seeb|Salalah|Sohar|Nizwa'],
  ['PK', 'Pakistan', 'southasian', 'PKR', 280, 3, 'Karachi|Lahore|Faisalabad|Rawalpindi|Islamabad|Multan|Peshawar'],
  ['PW', 'Palau', 'anglo', 'USD', 1, 1, 'Koror|Airai|Ngerulmud'],
  ['PS', 'Palestine', 'arabic', 'ILS', 3.7, 3, 'Gaza|Hebron|Nablus|Ramallah|Jenin|Bethlehem'],
  ['PA', 'Panama', 'hispanic', 'USD', 1, 1, 'Panama City|San Miguelito|David|Colón|La Chorrera'],
  ['PG', 'Papua New Guinea', 'anglo', 'PGK', 3.9, 3, 'Port Moresby|Lae|Mount Hagen|Madang|Goroka'],
  ['PY', 'Paraguay', 'hispanic', 'PYG', 7700, 2, 'Asunción|Ciudad del Este|San Lorenzo|Luque|Encarnación'],
  ['PE', 'Peru', 'hispanic', 'PEN', 3.75, 2, 'Lima|Arequipa|Trujillo|Chiclayo|Piura|Cusco|Iquitos'],
  ['PH', 'Philippines', 'southeastasian', 'PHP', 57, 3, 'Manila|Quezon City|Davao City|Cebu City|Zamboanga City|Makati|Taguig'],
  ['PL', 'Poland', 'centraleurope', 'PLN', 4, 1, 'Warsaw|Kraków|Wrocław|Łódź|Poznań|Gdańsk|Katowice'],
  ['PT', 'Portugal', 'lusophone', 'EUR', 0.92, 1, 'Lisbon|Porto|Braga|Coimbra|Funchal|Faro'],
  ['QA', 'Qatar', 'arabic', 'QAR', 3.64, 1, 'Doha|Al Rayyan|Al Wakrah|Al Khor|Lusail'],
  ['RO', 'Romania', 'centraleurope', 'RON', 4.6, 1, 'Bucharest|Cluj-Napoca|Timișoara|Iași|Constanța|Brașov'],
  ['RU', 'Russia', 'eastslavic', 'RUB', 92, 2, 'Moscow|Saint Petersburg|Novosibirsk|Yekaterinburg|Kazan|Nizhny Novgorod|Chelyabinsk'],
  ['RW', 'Rwanda', 'african', 'RWF', 1350, 4, 'Kigali|Butare|Gisenyi|Ruhengeri|Muhanga'],
  ['KN', 'Saint Kitts and Nevis', 'anglo', 'XCD', 2.7, 1, 'Basseterre|Charlestown|Sandy Point Town'],
  ['LC', 'Saint Lucia', 'anglo', 'XCD', 2.7, 2, 'Castries|Vieux Fort|Gros Islet|Soufrière'],
  ['VC', 'Saint Vincent and the Grenadines', 'anglo', 'XCD', 2.7, 2, 'Kingstown|Georgetown|Barrouallie'],
  ['WS', 'Samoa', 'anglo', 'WST', 2.7, 3, 'Apia|Vaitele|Salelologa'],
  ['SM', 'San Marino', 'italian', 'EUR', 0.92, 1, 'Serravalle|Borgo Maggiore|San Marino'],
  ['ST', 'São Tomé and Príncipe', 'lusophone', 'STN', 22.5, 3, 'São Tomé|Santo Amaro|Neves'],
  ['SA', 'Saudi Arabia', 'arabic', 'SAR', 3.75, 1, 'Riyadh|Jeddah|Mecca|Medina|Dammam|Khobar|Tabuk'],
  ['SN', 'Senegal', 'francophone', 'XOF', 600, 3, 'Dakar|Touba|Thiès|Kaolack|Saint-Louis|Ziguinchor'],
  ['RS', 'Serbia', 'centraleurope', 'RSD', 108, 2, 'Belgrade|Novi Sad|Niš|Kragujevac|Subotica'],
  ['SC', 'Seychelles', 'francophone', 'SCR', 13.8, 1, 'Victoria|Anse Boileau|Beau Vallon'],
  ['SL', 'Sierra Leone', 'african', 'SLE', 22.5, 4, 'Freetown|Bo|Kenema|Makeni|Koidu'],
  ['SG', 'Singapore', 'southeastasian', 'SGD', 1.35, 1, 'Singapore|Jurong East|Tampines|Woodlands'],
  ['SK', 'Slovakia', 'centraleurope', 'EUR', 0.92, 1, 'Bratislava|Košice|Prešov|Žilina|Nitra'],
  ['SI', 'Slovenia', 'centraleurope', 'EUR', 0.92, 1, 'Ljubljana|Maribor|Celje|Kranj|Koper'],
  ['SB', 'Solomon Islands', 'anglo', 'SBD', 8.4, 3, 'Honiara|Auki|Gizo'],
  ['SO', 'Somalia', 'arabic', 'SOS', 571, 4, 'Mogadishu|Hargeisa|Bosaso|Kismayo|Beledweyne'],
  ['ZA', 'South Africa', 'african', 'ZAR', 18, 2, 'Johannesburg|Cape Town|Durban|Pretoria|Port Elizabeth|Bloemfontein|East London'],
  ['KR', 'South Korea', 'korean', 'KRW', 1350, 1, 'Seoul|Busan|Incheon|Daegu|Daejeon|Gwangju|Suwon'],
  ['SS', 'South Sudan', 'african', 'SSP', 1300, 4, 'Juba|Wau|Malakal|Yei'],
  ['ES', 'Spain', 'hispanic', 'EUR', 0.92, 1, 'Madrid|Barcelona|Valencia|Seville|Zaragoza|Málaga|Bilbao'],
  ['LK', 'Sri Lanka', 'southasian', 'LKR', 300, 3, 'Colombo|Dehiwala-Mount Lavinia|Negombo|Kandy|Galle|Jaffna'],
  ['SD', 'Sudan', 'arabic', 'SDG', 600, 4, 'Khartoum|Omdurman|Port Sudan|Kassala|Nyala'],
  ['SR', 'Suriname', 'dutch', 'SRD', 30, 2, 'Paramaribo|Lelydorp|Nieuw Nickerie'],
  ['SE', 'Sweden', 'nordic', 'SEK', 10.5, 1, 'Stockholm|Gothenburg|Malmö|Uppsala|Västerås|Örebro'],
  ['CH', 'Switzerland', 'germanic', 'CHF', 0.88, 1, 'Zurich|Geneva|Basel|Lausanne|Bern|Lucerne'],
  ['SY', 'Syria', 'arabic', 'SYP', 13000, 4, 'Damascus|Aleppo|Homs|Latakia|Hama'],
  ['TW', 'Taiwan', 'chinese', 'TWD', 32, 1, 'New Taipei|Taichung|Kaohsiung|Taipei|Taoyuan|Tainan'],
  ['TJ', 'Tajikistan', 'persian', 'TJS', 10.9, 3, 'Dushanbe|Khujand|Kulob|Bokhtar'],
  ['TZ', 'Tanzania', 'african', 'TZS', 2600, 3, 'Dar es Salaam|Mwanza|Arusha|Dodoma|Mbeya|Zanzibar City'],
  ['TH', 'Thailand', 'southeastasian', 'THB', 35, 2, 'Bangkok|Nonthaburi|Chiang Mai|Hat Yai|Pattaya|Khon Kaen|Phuket'],
  ['TL', 'Timor-Leste', 'lusophone', 'USD', 1, 3, 'Dili|Baucau|Maliana|Suai'],
  ['TG', 'Togo', 'francophone', 'XOF', 600, 4, 'Lomé|Sokodé|Kara|Kpalimé|Atakpamé'],
  ['TO', 'Tonga', 'anglo', 'TOP', 2.35, 2, "Nuku'alofa|Neiafu|Haveluloto"],
  ['TT', 'Trinidad and Tobago', 'anglo', 'TTD', 6.8, 1, 'Chaguanas|San Fernando|Port of Spain|Arima|Scarborough'],
  ['TN', 'Tunisia', 'arabic', 'TND', 3.1, 3, 'Tunis|Sfax|Sousse|Kairouan|Bizerte|Gabès'],
  ['TR', 'Türkiye', 'turkic', 'TRY', 34, 2, 'Istanbul|Ankara|İzmir|Bursa|Antalya|Adana|Konya'],
  ['TM', 'Turkmenistan', 'turkic', 'TMT', 3.5, 2, 'Ashgabat|Türkmenabat|Daşoguz|Mary'],
  ['TV', 'Tuvalu', 'anglo', 'AUD', 1.52, 2, 'Funafuti|Vaitupu|Nukufetau'],
  ['UG', 'Uganda', 'african', 'UGX', 3700, 4, 'Kampala|Gulu|Lira|Mbarara|Jinja|Mbale'],
  ['UA', 'Ukraine', 'eastslavic', 'UAH', 41, 3, 'Kyiv|Kharkiv|Odesa|Dnipro|Lviv|Zaporizhzhia'],
  ['AE', 'United Arab Emirates', 'arabic', 'AED', 3.67, 1, 'Dubai|Abu Dhabi|Sharjah|Al Ain|Ajman|Ras Al Khaimah'],
  ['GB', 'United Kingdom', 'anglo', 'GBP', 0.79, 1, 'London|Birmingham|Manchester|Glasgow|Leeds|Liverpool|Edinburgh'],
  ['US', 'United States', 'anglo', 'USD', 1, 1, 'New York|Los Angeles|Chicago|Houston|Phoenix|Dallas|San Francisco'],
  ['UY', 'Uruguay', 'hispanic', 'UYU', 40, 1, 'Montevideo|Salto|Ciudad de la Costa|Paysandú|Punta del Este'],
  ['UZ', 'Uzbekistan', 'turkic', 'UZS', 12700, 3, 'Tashkent|Samarkand|Namangan|Andijan|Bukhara|Fergana'],
  ['VU', 'Vanuatu', 'anglo', 'VUV', 119, 3, 'Port Vila|Luganville|Isangel'],
  ['VA', 'Vatican City', 'italian', 'EUR', 0.92, 1, 'Vatican City|Castel Gandolfo'],
  ['VE', 'Venezuela', 'hispanic', 'VES', 36, 2, 'Caracas|Maracaibo|Valencia|Barquisimeto|Maracay|Ciudad Guayana'],
  ['VN', 'Vietnam', 'southeastasian', 'VND', 25000, 3, 'Ho Chi Minh City|Hanoi|Hai Phong|Da Nang|Can Tho|Bien Hoa|Nha Trang'],
  ['YE', 'Yemen', 'arabic', 'YER', 250, 4, "Sana'a|Aden|Taiz|Hodeidah|Mukalla"],
  ['ZM', 'Zambia', 'african', 'ZMW', 26, 3, 'Lusaka|Kitwe|Ndola|Kabwe|Chingola|Livingstone'],
  ['ZW', 'Zimbabwe', 'african', 'USD', 1, 3, 'Harare|Bulawayo|Chitungwiza|Mutare|Gweru'],
];

export const COUNTRIES = Object.fromEntries(
  RAW.map(([code, name, region, currency, fx, tier, cities]) => [code, { code, name, region, currency, fx, tier, cities: cities.split('|') }]),
);

export const COUNTRY_LIST = RAW.map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name));

export const CURRENCIES = [...new Set(RAW.map((r) => r[3]))].sort();

export function findCountry(text) {
  const t = String(text || '').trim().toLowerCase();
  if (!t) return null;
  return RAW.find(([code, name]) => name.toLowerCase() === t || code.toLowerCase() === t)?.[0] || null;
}

export function fxFor(currency) {
  return RAW.find((r) => r[3] === currency)?.[4] ?? 1;
}
