// Frozen subset of the KNOLSKAPE Skills Ontology for NanoAI MVP. Only atomic Skills whose
// behavioral indicators and proficiency levels passed review are assessable. The version is
// pinned per published assessment.
export const ONTOLOGY_VERSION = 'V4.0-frozen-subset-2026.09';

export const SITUATION_TAGS = [
  { id: 'T1', name: 'Customer facing' },
  { id: 'T2', name: 'Team and people' },
  { id: 'T3', name: 'Cross functional' },
  { id: 'T4', name: 'Data and decisions' },
  { id: 'T5', name: 'Change and ambiguity' },
  { id: 'T6', name: 'Risk and compliance' },
  { id: 'T7', name: 'Time and resource pressure' },
];

function ind(id, text, effective = true) { return { id, text, effective }; }

// affinity: 'open' Skills default to Audio or Text; 'mcq' Skills default to MCQ with one open scenario.
// voice: true when "what would you say" situations fit, so Audio is preferred over Text.
export const SKILLS = [
  {
    id: 'SK-COACH', name: 'Coaching', domain: 'People Leadership', macro: 'Developing Others', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Helps a person find their own way forward through questions, observation and agreed next steps rather than handing them the answer.',
    aliases: ['coaching conversations', 'developing people', 'mentoring', 'growth conversations'],
    keywords: ['coach', 'coaching', 'develop', 'grow', 'mentor', 'one on one', 'career', 'potential', 'performance conversation'],
    indicators: [
      ind('COACH-E1', 'Asks open questions that surface the person\'s own view of the situation before offering a view'),
      ind('COACH-E2', 'Names the specific behavior observed and its effect, not a general impression'),
      ind('COACH-E3', 'Agrees a concrete next step the person owns, with a time to review it'),
      ind('COACH-E4', 'Adjusts support to the person\'s experience and confidence in the task'),
      ind('COACH-I1', 'Tells the person what to do without checking their understanding of the problem', false),
      ind('COACH-I2', 'Leaves the conversation without an agreed action or follow up', false),
    ],
    levels: { L0: 'Directs or reassures without exploring the person\'s view', L1: 'Asks some questions but drives to their own solution', L2: 'Explores the person\'s view and co-creates a next step', L3: 'Builds insight through questions, names behavior and impact precisely, and agrees an owned, time bound action' },
    tags: ['T2'],
  },
  {
    id: 'SK-DELEG', name: 'Delegation', domain: 'People Leadership', macro: 'Managing Work Through Others', affinity: 'open', voice: false, hasProducts: true,
    definition: 'Assigns the right work to the right person with a clear outcome, authority and check-in rhythm, and lets them do it.',
    aliases: ['delegating', 'empowerment', 'letting go', 'assigning work'],
    keywords: ['delegate', 'delegat', 'hand over', 'assign', 'workload', 'bandwidth', 'ownership', 'micromanage', 'capacity'],
    indicators: [
      ind('DELEG-E1', 'States the outcome and why it matters, not the steps to follow'),
      ind('DELEG-E2', 'Matches the task to the person\'s capability and development need'),
      ind('DELEG-E3', 'Makes the decision authority and boundaries explicit'),
      ind('DELEG-E4', 'Sets a check-in rhythm proportionate to risk instead of continuous oversight'),
      ind('DELEG-I1', 'Keeps the task or takes it back at the first sign of difficulty', false),
      ind('DELEG-I2', 'Hands over the task without a clear outcome or authority', false),
    ],
    levels: { L0: 'Keeps the work or hands it over with no clarity', L1: 'Assigns the task but prescribes the method or hovers', L2: 'Delegates the outcome with clear authority and a review point', L3: 'Delegates with outcome, authority, support matched to the person and a risk based check-in rhythm' },
    tags: ['T2', 'T7'],
  },
  {
    id: 'SK-FEEDBK', name: 'Giving Feedback', domain: 'People Leadership', macro: 'Developing Others', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Shares specific, timely observations about behavior and impact in a way the receiver can act on.',
    aliases: ['feedback', 'constructive feedback', 'performance feedback', 'critical feedback'],
    keywords: ['feedback', 'appraisal', 'praise', 'performance review', 'observed behavior'],
    indicators: [
      ind('FEEDBK-E1', 'Describes the specific behavior and situation rather than a label or trait'),
      ind('FEEDBK-E2', 'States the impact on people, work or customers'),
      ind('FEEDBK-E3', 'Invites the receiver\'s perspective and listens before proposing change'),
      ind('FEEDBK-E4', 'Agrees what will be different next time and how it will be noticed'),
      ind('FEEDBK-I1', 'Generalizes ("you always", "you are not a team player") or softens until the point is lost', false),
      ind('FEEDBK-I2', 'Delivers feedback in front of others or long after the event', false),
    ],
    levels: { L0: 'Vague, judgmental or avoided', L1: 'Specific behavior but no impact or dialogue', L2: 'Behavior, impact and a two way exchange', L3: 'Behavior, impact, the receiver\'s view heard, and an agreed observable change' },
    tags: ['T2'],
  },
  {
    id: 'SK-DIFFCON', name: 'Difficult Conversations', domain: 'People Leadership', macro: 'Interpersonal Effectiveness', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Raises and works through a sensitive issue directly, holding the relationship and the outcome at the same time.',
    aliases: ['tough conversations', 'courageous conversations', 'having hard talks', 'confronting issues'],
    keywords: ['conversation', 'sensitive', 'tension', 'underperformance', 'confront', 'awkward', 'push back', 'escalate'],
    indicators: [
      ind('DIFFCON-E1', 'Opens with the issue and its purpose in the first sentences, without preamble that hides it'),
      ind('DIFFCON-E2', 'Separates facts from interpretation and says which is which'),
      ind('DIFFCON-E3', 'Acknowledges the other person\'s position and constraints'),
      ind('DIFFCON-E4', 'Proposes a way forward that protects both the outcome and the relationship'),
      ind('DIFFCON-I1', 'Avoids, delays or delegates the conversation', false),
      ind('DIFFCON-I2', 'Attributes motive or escalates tone when challenged', false),
    ],
    levels: { L0: 'Avoids the issue or attacks the person', L1: 'Raises the issue indirectly or one sidedly', L2: 'Raises it directly, separates fact from view, hears the other side', L3: 'Direct, fact based, empathic and lands a shared way forward' },
    tags: ['T2', 'T1'],
  },
  {
    id: 'SK-PRIOR', name: 'Prioritization', domain: 'Execution', macro: 'Planning and Organizing', affinity: 'mcq', voice: false, hasProducts: true,
    definition: 'Chooses what to do first, later and not at all, using impact, urgency and dependencies rather than noise.',
    aliases: ['prioritising', 'prioritizing', 'time management', 'focus', 'triage', 'managing competing demands', 'saying no'],
    keywords: ['priority', 'prioriti', 'urgent', 'deadline', 'competing', 'trade off', 'backlog', 'do first', 'triage', 'which to do'],
    indicators: [
      ind('PRIOR-E1', 'Ranks by business impact and risk rather than by who asked loudest or most recently'),
      ind('PRIOR-E2', 'Identifies dependencies and does the enabling work first'),
      ind('PRIOR-E3', 'Says no or not now explicitly, with the reason and the alternative'),
      ind('PRIOR-E4', 'Re-plans when facts change instead of adding everything to the list'),
      ind('PRIOR-I1', 'Treats every request as equally urgent', false),
      ind('PRIOR-I2', 'Accepts new work without dropping or renegotiating something', false),
    ],
    levels: { L0: 'Reacts to the latest or loudest request', L1: 'Sorts by urgency alone', L2: 'Weighs impact, urgency and dependencies and communicates the order', L3: 'Weighs impact, urgency, dependencies and capacity, declines explicitly, and re-plans as facts change' },
    tags: ['T7', 'T4'],
  },
  {
    id: 'SK-DATADEC', name: 'Data Driven Decision Making', domain: 'Thinking', macro: 'Analytical Thinking', affinity: 'mcq', voice: false, hasProducts: true,
    definition: 'Reads the numbers correctly, asks what they do and do not show, and decides in proportion to the evidence.',
    aliases: ['analytical thinking', 'data literacy', 'evidence based decisions', 'reading dashboards'],
    keywords: ['data', 'chart', 'dashboard', 'metric', 'trend', 'numbers', 'analysis', 'kpi', 'evidence', 'figures'],
    indicators: [
      ind('DATADEC-E1', 'Identifies the specific figure or trend in the data that matters for the decision'),
      ind('DATADEC-E2', 'Distinguishes what the data shows from what it might explain'),
      ind('DATADEC-E3', 'Sizes the response to the size of the gap or signal'),
      ind('DATADEC-E4', 'Names the additional data or check needed before a bigger commitment'),
      ind('DATADEC-I1', 'Acts on an anecdote or a single point while ignoring the trend', false),
      ind('DATADEC-I2', 'Asks for more analysis as a way of avoiding a decision', false),
    ],
    levels: { L0: 'Ignores or misreads the data', L1: 'Reads the headline number but not the pattern', L2: 'Reads the pattern correctly and proposes a proportionate action', L3: 'Reads pattern and caveats, acts proportionately and names the check that would confirm or reverse the decision' },
    tags: ['T4'],
  },
  {
    id: 'SK-STAKE', name: 'Stakeholder Management', domain: 'Collaboration', macro: 'Working Across Boundaries', affinity: 'open', voice: false, hasProducts: true,
    definition: 'Identifies who has a stake in an outcome, understands what they need, and keeps them aligned as things change.',
    aliases: ['managing stakeholders', 'stakeholder alignment', 'managing up', 'partnering'],
    keywords: ['stakeholder', 'align', 'expectation', 'sponsor', 'client', 'partner', 'update', 'buy in', 'cross functional'],
    indicators: [
      ind('STAKE-E1', 'Maps who is affected and what each needs before acting'),
      ind('STAKE-E2', 'Communicates bad news early with options rather than late with excuses'),
      ind('STAKE-E3', 'Tailors the message to the stakeholder\'s interest and level'),
      ind('STAKE-E4', 'Secures explicit agreement on decisions and next steps'),
      ind('STAKE-I1', 'Informs only the stakeholder in front of them', false),
      ind('STAKE-I2', 'Over promises to keep a stakeholder happy in the moment', false),
    ],
    levels: { L0: 'Reacts to whichever stakeholder is present', L1: 'Informs stakeholders but late or uniformly', L2: 'Anticipates needs, communicates early and tailors the message', L3: 'Maps interests, communicates early with options, tailors by audience and secures explicit alignment' },
    tags: ['T3', 'T1'],
  },
  {
    id: 'SK-CUST', name: 'Customer Centricity', domain: 'Customer', macro: 'Customer Focus', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Understands the customer\'s actual problem and acts to solve it within what the business can honestly deliver.',
    aliases: ['customer focus', 'customer empathy', 'customer service', 'client orientation', 'customer experience'],
    keywords: ['customer', 'complaint', 'client', 'service', 'escalation', 'refund', 'account', 'satisfaction', 'churn'],
    indicators: [
      ind('CUST-E1', 'Restates the customer\'s problem in their terms before proposing anything'),
      ind('CUST-E2', 'Offers a concrete resolution with a timeline they own'),
      ind('CUST-E3', 'Is honest about what cannot be done and offers the nearest alternative'),
      ind('CUST-E4', 'Captures the root cause so it does not recur for other customers'),
      ind('CUST-I1', 'Quotes policy as the answer to the customer\'s problem', false),
      ind('CUST-I2', 'Promises what the business cannot deliver to end the conversation', false),
    ],
    levels: { L0: 'Defends the company or deflects', L1: 'Apologizes and follows script without owning resolution', L2: 'Understands the problem, owns a resolution with a timeline', L3: 'Understands, owns, is honest about limits and fixes the cause' },
    tags: ['T1'],
  },
  {
    id: 'SK-PROBS', name: 'Problem Solving', domain: 'Thinking', macro: 'Analytical Thinking', affinity: 'open', voice: false, hasProducts: true,
    definition: 'Defines the real problem, generates options, and chooses one with a clear rationale and a way to check it worked.',
    aliases: ['structured problem solving', 'critical thinking', 'root cause analysis', 'troubleshooting'],
    keywords: ['problem', 'root cause', 'diagnose', 'recurring', 'keeps happening', 'solution', 'troubleshoot'],
    indicators: [
      ind('PROBS-E1', 'States the problem as a gap between what is and what should be, with evidence'),
      ind('PROBS-E2', 'Separates symptoms from likely causes'),
      ind('PROBS-E3', 'Considers more than one option before choosing'),
      ind('PROBS-E4', 'Defines how success will be checked and by when'),
      ind('PROBS-I1', 'Jumps to the first plausible fix', false),
      ind('PROBS-I2', 'Solves the symptom and leaves the cause', false),
    ],
    levels: { L0: 'Reacts to the symptom', L1: 'Identifies a cause but takes the first fix', L2: 'Diagnoses cause, weighs options, picks with a rationale', L3: 'Diagnoses with evidence, weighs options, picks with rationale and a defined check on results' },
    tags: ['T4', 'T5'],
  },
  {
    id: 'SK-INFLU', name: 'Influencing Without Authority', domain: 'Collaboration', macro: 'Working Across Boundaries', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Gains commitment from people who do not report to you by connecting the ask to their interests and evidence.',
    aliases: ['influencing', 'persuasion', 'building buy in', 'lateral leadership'],
    keywords: ['influence', 'persuade', 'convince', 'buy in', 'peer', 'resist', 'agree', 'commit', 'support'],
    indicators: [
      ind('INFLU-E1', 'Frames the ask in terms of the other party\'s goals and constraints'),
      ind('INFLU-E2', 'Uses evidence or a concrete example rather than assertion'),
      ind('INFLU-E3', 'Asks for a specific, bounded commitment'),
      ind('INFLU-E4', 'Addresses the stated objection directly instead of repeating the request'),
      ind('INFLU-I1', 'Relies on escalation or seniority to get agreement', false),
      ind('INFLU-I2', 'Repeats the same argument louder when challenged', false),
    ],
    levels: { L0: 'Asserts or escalates', L1: 'Explains own need without linking to theirs', L2: 'Links to their interests with evidence and a clear ask', L3: 'Links to their interests, uses evidence, handles the objection and lands a bounded commitment' },
    tags: ['T3'],
  },
  {
    id: 'SK-RISK', name: 'Risk and Compliance Judgment', domain: 'Governance', macro: 'Acting with Integrity', affinity: 'mcq', voice: false, hasProducts: false,
    definition: 'Recognizes when a situation carries a compliance, safety or reputational risk and acts within policy while still solving the business problem.',
    aliases: ['compliance mindset', 'risk awareness', 'integrity', 'ethical judgment', 'policy adherence'],
    keywords: ['compliance', 'risk', 'policy', 'audit', 'regulation', 'approval', 'exception', 'fraud', 'safety', 'incident'],
    indicators: [
      ind('RISK-E1', 'Names the specific risk or policy the situation touches'),
      ind('RISK-E2', 'Pauses the action that would breach policy before pursuing the business goal'),
      ind('RISK-E3', 'Escalates or documents through the defined channel'),
      ind('RISK-E4', 'Finds a compliant route to the legitimate business outcome'),
      ind('RISK-I1', 'Treats the policy as a formality to work around under pressure', false),
      ind('RISK-I2', 'Blocks the business outcome without offering a compliant alternative', false),
    ],
    levels: { L0: 'Misses or ignores the risk', L1: 'Notices the risk but proceeds or blocks outright', L2: 'Names the risk, acts within policy, escalates properly', L3: 'Names the risk, acts within policy, escalates and finds the compliant route to the outcome' },
    tags: ['T6'],
  },
  {
    id: 'SK-PLAN', name: 'Planning and Execution', domain: 'Execution', macro: 'Planning and Organizing', affinity: 'open', voice: false, hasProducts: true,
    definition: 'Turns a goal into a sequenced plan with owners, risks and checkpoints, then adjusts as delivery unfolds.',
    aliases: ['execution', 'project planning', 'delivery', 'getting things done', 'operational planning'],
    keywords: ['project plan', 'milestone', 'timeline', 'critical path', 'slip', 'schedule', 'launch', 'dependency', 'checkpoint', 'execution'],
    indicators: [
      ind('PLAN-E1', 'Breaks the goal into sequenced steps with owners and dates'),
      ind('PLAN-E2', 'Identifies the critical path and the risks that threaten it'),
      ind('PLAN-E3', 'Builds in checkpoints that trigger a decision, not just a status update'),
      ind('PLAN-E4', 'Replans around a slip by trading scope, time or resource explicitly'),
      ind('PLAN-I1', 'Plans by listing tasks without sequence or ownership', false),
      ind('PLAN-I2', 'Absorbs slips silently until the deadline is missed', false),
    ],
    levels: { L0: 'Starts work without a plan', L1: 'Lists tasks without sequence, owners or risks', L2: 'Sequenced plan with owners, risks and checkpoints', L3: 'Sequenced plan with critical path, decision checkpoints and explicit trade offs when it slips' },
    tags: ['T7', 'T3'],
  },
  {
    id: 'SK-NEGOT', name: 'Negotiation', domain: 'Commercial', macro: 'Commercial Effectiveness', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Reaches agreements that protect value for the business by preparing, trading rather than conceding, and keeping the relationship intact.',
    aliases: ['negotiating', 'deal making', 'commercial negotiation', 'vendor negotiation'],
    keywords: ['negotiate', 'discount', 'contract', 'terms', 'concession', 'price', 'vendor', 'deal', 'counter'],
    indicators: [
      ind('NEGOT-E1', 'Anchors on interests and the value delivered rather than on price alone'),
      ind('NEGOT-E2', 'Trades a concession for something in return instead of giving it away'),
      ind('NEGOT-E3', 'Knows and states the walk away point or escalation path'),
      ind('NEGOT-E4', 'Keeps the tone collaborative while holding position'),
      ind('NEGOT-I1', 'Concedes on price at the first objection', false),
      ind('NEGOT-I2', 'Makes threats or ultimatums that damage the relationship', false),
    ],
    levels: { L0: 'Concedes or refuses outright', L1: 'Defends price without exploring interests', L2: 'Explores interests, trades concessions, keeps tone collaborative', L3: 'Interest based, trades every concession, knows the walk away and preserves the relationship' },
    tags: ['T1', 'T3'],
  },
  {
    id: 'SK-CHANGE', name: 'Leading Through Change', domain: 'People Leadership', macro: 'Leading Change', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Helps people move through uncertainty by explaining the why, acknowledging the loss and making the next step concrete.',
    aliases: ['change management', 'change leadership', 'adaptability', 'managing transitions', 'resilience'],
    keywords: ['change', 'restructure', 'transition', 'uncertainty', 'new system', 'reorg', 'resistance', 'morale', 'announce'],
    indicators: [
      ind('CHANGE-E1', 'Explains the reason for the change and what will not change'),
      ind('CHANGE-E2', 'Acknowledges what people lose or fear without dismissing it'),
      ind('CHANGE-E3', 'Makes the next concrete step and its timing clear'),
      ind('CHANGE-E4', 'Separates what is decided from what the team can still shape'),
      ind('CHANGE-I1', 'Relays the change as a directive with no reason', false),
      ind('CHANGE-I2', 'Overstates certainty or promises no impact', false),
    ],
    levels: { L0: 'Relays the directive or hides from it', L1: 'Explains the why but ignores the human impact', L2: 'Explains why, acknowledges loss, names the next step', L3: 'Explains why and what stays, acknowledges loss, names next step and where the team has a voice' },
    tags: ['T5', 'T2'],
  },
  {
    id: 'SK-CONFL', name: 'Conflict Resolution', domain: 'Collaboration', macro: 'Interpersonal Effectiveness', affinity: 'open', voice: true, hasProducts: true,
    definition: 'Surfaces the interests behind a disagreement and moves the parties to a workable agreement.',
    aliases: ['managing conflict', 'mediation', 'resolving disputes', 'handling disagreement'],
    keywords: ['conflict', 'disagree', 'dispute', 'argument', 'tension', 'mediate', 'clash', 'friction'],
    indicators: [
      ind('CONFL-E1', 'Hears each party\'s position and restates it to their satisfaction'),
      ind('CONFL-E2', 'Identifies the interests or constraints beneath the positions'),
      ind('CONFL-E3', 'Focuses on the shared goal and the problem, not on blame'),
      ind('CONFL-E4', 'Agrees a specific, testable resolution and how disputes will be handled next time'),
      ind('CONFL-I1', 'Takes a side early or imposes a ruling', false),
      ind('CONFL-I2', 'Smooths over the disagreement without resolving it', false),
    ],
    levels: { L0: 'Avoids, imposes or takes sides', L1: 'Hears positions but pushes a compromise', L2: 'Surfaces interests and lands a workable agreement', L3: 'Surfaces interests, keeps focus on the shared goal and agrees a testable resolution with a path for future disputes' },
    tags: ['T2', 'T3'],
  },
  {
    id: 'SK-COMM', name: 'Commercial Acumen', domain: 'Commercial', macro: 'Commercial Effectiveness', affinity: 'mcq', voice: false, hasProducts: true,
    definition: 'Understands how the business makes money and weighs decisions by margin, cash and customer value, not activity.',
    aliases: ['business acumen', 'financial acumen', 'p&l thinking', 'commercial awareness'],
    keywords: ['margin', 'revenue', 'cost', 'profit', 'pricing', 'budget', 'cash', 'roi', 'p&l', 'volume'],
    indicators: [
      ind('COMM-E1', 'Quantifies the margin or cash effect of an option, not only revenue'),
      ind('COMM-E2', 'Considers the effect on customer value and retention, not just this transaction'),
      ind('COMM-E3', 'Identifies the hidden cost or second order effect of a decision'),
      ind('COMM-E4', 'Chooses the option that protects long term value even when it costs short term revenue'),
      ind('COMM-I1', 'Chases revenue or volume without checking margin', false),
      ind('COMM-I2', 'Cuts cost in a way that damages the customer or the team', false),
    ],
    levels: { L0: 'Decides on activity or top line alone', L1: 'Considers cost but misses margin or second order effects', L2: 'Weighs margin, cash and customer value', L3: 'Weighs margin, cash, customer value and hidden costs, and protects long term value' },
    tags: ['T4', 'T1'],
  },
];

export const SKILL_BY_ID = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
export function getSkill(id) { return SKILL_BY_ID[id]; }
export function effectiveIndicators(skill) { return skill.indicators.filter((i) => i.effective); }
export function indicatorById(id) {
  for (const s of SKILLS) { const f = s.indicators.find((i) => i.id === id); if (f) return { ...f, skillId: s.id }; }
  return null;
}
