// Scripted scenario seeds, group D: Negotiation, Leading Through Change, Conflict Resolution, Commercial Acumen.
export default [
  {
    skillId: 'SK-NEGOT', tag: 'T1', difficulty: 'Low', title: 'The customer asks for 20 percent off',
    header: 'You are an account manager at {company}. A mid sized customer has asked for a 20 percent discount at renewal.',
    situation: 'You are an account manager at {company}. {p1}, the purchasing manager at a mid sized customer, has emailed asking for a 20 percent reduction on the annual {product} renewal, citing "budget pressure and a competitor quote." The account is healthy: usage is up 30 percent this year, the customer added two teams, and support tickets are low. Your discount authority is 8 percent, and anything beyond that needs your director and a business case. You know the competitor\'s product lacks the reporting module {p1}\'s finance team uses every month. The renewal is in three weeks. {p1} has asked for a call tomorrow and has said "I need something to take back to my CFO." You have worked with {p1} for two years and the relationship has been straightforward so far.',
    prompt: 'What would you say to {p1} on the call? Speak as you would say it.',
    mcqPrompt: 'How should you respond to the 20 percent request?',
    facts: ['{p1} wants 20 percent off citing budget and a competitor quote', 'Usage up 30 percent, two teams added, low tickets', 'Your authority is 8 percent', 'The competitor lacks the reporting module finance uses monthly'],
    constraints: ['8 percent authority', 'Three weeks to renewal', '{p1} needs something for their CFO'],
    stakeholders: ['{p1} and their CFO', 'Your director', 'The customer\'s finance team'],
    ideal: [
      { text: 'Anchor on the value delivered, 30 percent more usage and the reporting module finance depends on, rather than on the discount number', indicator: 'NEGOT-E1', fact: 1 },
      { text: 'Trade any concession for something, such as a two year term or a case study, rather than giving it away', indicator: 'NEGOT-E2', fact: 2 },
      { text: 'Know and state your limit and escalation path honestly: 8 percent now, anything more needs a business case', indicator: 'NEGOT-E3', fact: 2 },
      { text: 'Keep the tone collaborative and give {p1} something concrete to take to their CFO', indicator: 'NEGOT-E4', fact: 0 },
    ],
    modelAnswer: 'I would open by asking what is behind the budget pressure and what the CFO needs to see. Then I would set the value context: usage is up 30 percent, two new teams, and the reporting module finance uses monthly, which I would note the competitor quote does not include. I would say honestly that 20 percent is outside what I can do; I can offer up to 8 percent, and I would rather trade than give: 8 percent for a two year term with price protection, which gives the CFO certainty, or 5 percent for one year with a public case study. If {p1} needs more than that, I would offer to build a case for my director together, but I would not promise it. I would send a one page summary {p1} can forward to the CFO the same day.',
    weak: ['Offers 8 percent immediately with nothing in return', 'Says 20 percent is impossible and ends the conversation', 'Promises to get 20 percent approved without authority'],
    mcq: [{
      q: 'How do you respond to {p1} on the call?', options: [
        { level: 'L3', text: 'Explore the CFO\'s need, anchor on 30 percent usage growth and the reporting module, state your 8 percent limit honestly, and trade it for a two year term.' },
        { level: 'L2', text: 'Explain the value the customer is getting and offer the 8 percent you are authorized to give as a goodwill gesture.' },
        { level: 'L1', text: 'Tell {p1} that 20 percent is not possible and that the competitor cannot match the reporting module, so they should renew at list price.' },
        { level: 'L0', text: 'Tell {p1} you will take the 20 percent request to your director and do your best to get it approved before renewal.' },
      ] },
    ],
  },
  {
    skillId: 'SK-NEGOT', tag: 'T3', difficulty: 'Medium', title: 'The vendor who wants to raise prices mid contract',
    header: 'You are a procurement manager at {company}. A critical vendor has asked for a 12 percent price increase, citing input costs.',
    situation: 'You are a procurement manager at {company}. {p2}, the account director at a vendor that supplies a critical component for {product}, has requested a 12 percent price increase from next quarter, citing raw material inflation, with a letter that references a clause allowing "reasonable adjustment for documented cost changes." Switching vendors would take nine months of qualification. Your finance team has modelled that 12 percent costs 900,000 a year. You know the vendor is bidding for a larger contract with your group next year, that their raw material index has risen about 7 percent, not 12, and that your volumes are up 15 percent this year, which lowers their unit cost. {p2} has asked for a meeting on Friday to "finalize the adjustment."',
    prompt: 'How would you prepare, and what would you say to {p2} on Friday? Speak as you would say it.',
    mcqPrompt: 'What is the best negotiating position on Friday?',
    facts: ['12 percent increase requested under a cost adjustment clause', 'Switching takes nine months', 'The raw material index rose about 7 percent', 'Your volumes are up 15 percent', 'The vendor is bidding for a larger group contract'],
    constraints: ['Dependency on the vendor', '900,000 a year at stake'],
    stakeholders: ['{p2} and the vendor', 'Your finance team', 'The group\'s wider contract'],
    ideal: [
      { text: 'Anchor on interests and evidence, the documented 7 percent index and your 15 percent volume growth, rather than on the 12 percent figure', indicator: 'NEGOT-E1', fact: 2 },
      { text: 'Trade any increase for something: a longer term, volume tiers, or a cap on future adjustments', indicator: 'NEGOT-E2', fact: 3 },
      { text: 'Know the walk away and escalation path: the clause requires documentation, and the group bid is context you can name respectfully', indicator: 'NEGOT-E3', fact: 4 },
      { text: 'Keep the relationship collaborative given the nine month dependency', indicator: 'NEGOT-E4', fact: 1 },
    ],
    modelAnswer: 'Before Friday I would get the raw material index data and our volume figures on one page and align with finance on what we can accept. On Friday I would say we take the clause seriously and want to see the documentation, and that the public index shows about 7 percent, not 12. I would add that our volumes are up 15 percent, which lowers their unit cost, so a fair adjustment is smaller still. I would propose: a 4 percent increase in exchange for a two year extension with a cap on further adjustments, and volume tiers that reduce price if we grow again. I would not threaten with the group bid, but I would note that a partnership that adjusts fairly is one we can recommend. If they insist on 12 without documentation, the clause does not support it and I would say so plainly.',
    weak: ['Accepts 12 percent because switching takes nine months', 'Refuses any increase and threatens the group bid', 'Splits the difference at 6 percent without asking for anything in return'],
    mcq: [{
      q: 'What position do you take on Friday?', options: [
        { level: 'L3', text: 'Ask for the documentation, cite the 7 percent index and your 15 percent volume growth, and offer a smaller increase in exchange for a longer term and an adjustment cap.' },
        { level: 'L2', text: 'Counter at 6 percent as a fair middle ground between their request and the index, and keep the relationship positive.' },
        { level: 'L1', text: 'Tell {p2} that any increase puts their group bid at risk and that you expect prices to hold for the contract term.' },
        { level: 'L0', text: 'Accept the 12 percent increase because the clause allows adjustment and switching vendors would take nine months.' },
      ] },
    ],
  },
  {
    skillId: 'SK-NEGOT', tag: 'T1', difficulty: 'High', title: 'The deal that needs a concession you cannot afford',
    header: 'You are a sales director at {company}. A strategic prospect wants unlimited liability in the contract or they will not sign.',
    situation: 'You are a sales director at {company}. A strategic prospect, worth 3 million over three years and a reference in a new sector, has reached the final contract stage for {product}. {p3}, their general counsel, has said they will not sign unless {company} accepts unlimited liability for data breaches. Your legal team\'s position is a cap at two times annual fees; unlimited liability is a board level exception that has been granted once, for a customer ten times this size. {p3} says their board policy is unlimited liability from all critical vendors and that "this is not a negotiating tactic." Your quarter depends on this deal and your CEO has asked for a daily update. The prospect\'s CIO, your sponsor, wants the deal done and has hinted that {p3} has accepted caps before for other vendors.',
    prompt: 'What would you do, and what would you say to {p3}? Explain how you would find a path that protects both the deal and the company.',
    mcqPrompt: 'What is the right approach to the liability demand?',
    facts: ['3 million deal and a new sector reference', 'General counsel demands unlimited liability for data breaches', 'Your standard is a cap at two times fees; unlimited is a board exception', 'The CIO sponsor hints caps were accepted before', 'Your quarter and CEO attention depend on it'],
    constraints: ['Board level exception process', 'Counsel says it is not a tactic', 'Quarter pressure'],
    stakeholders: ['{p3}', 'The CIO sponsor', 'Your legal team and board', 'Your CEO'],
    ideal: [
      { text: 'Anchor on the interest behind the demand, protection against a breach, rather than on the word unlimited', indicator: 'NEGOT-E1', fact: 1 },
      { text: 'Trade rather than concede: offer a higher cap, a dedicated insurance certificate or breach specific remedies in exchange for term or scope', indicator: 'NEGOT-E2', fact: 2 },
      { text: 'Know and state the walk away: unlimited liability is a board exception and you will not pretend otherwise under quarter pressure', indicator: 'NEGOT-E3', fact: 4 },
      { text: 'Keep the tone collaborative and use the CIO\'s information carefully, without accusing {p3} of bluffing', indicator: 'NEGOT-E4', fact: 3 },
    ],
    modelAnswer: 'I would ask {p3} for a direct conversation about what their board is protecting against, because unlimited liability is a way of saying "we need to be made whole after a breach", and there are several ways to get there. I would explain that our standard is a cap at two times fees and that unlimited is a board exception granted once to a customer ten times this size, so I am not going to pretend I can promise it. Then the trade: a cap at five times fees for data breaches specifically, backed by a named cyber insurance certificate, in exchange for a three year term. Or a cap that scales with data volume. I would ask the CIO to help me understand what {p3} has accepted from other critical vendors, without putting {p3} on the spot. I would tell my CEO the honest odds and that I would rather lose the deal than the company\'s liability position.',
    weak: ['Escalates to the board for unlimited liability to save the quarter', 'Tells {p3} you know they accepted caps elsewhere and calls the bluff', 'Walks away at the first refusal without exploring the interest'],
    mcq: [{
      q: 'How do you approach {p3}\'s demand?', options: [
        { level: 'L3', text: 'Explore what their board is protecting, state honestly that unlimited is a board exception you cannot promise, and offer a higher breach specific cap with insurance in exchange for term.' },
        { level: 'L2', text: 'Offer a higher liability cap of five times fees as a compromise and ask the CIO sponsor to help persuade {p3} to accept it.' },
        { level: 'L1', text: 'Tell {p3} that you understand other vendors have been given caps and ask them to apply the same standard to you.' },
        { level: 'L0', text: 'Take the request to your board as an exception, since the deal is worth 3 million and the quarter depends on it.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CHANGE', tag: 'T5', difficulty: 'Low', title: 'Announcing the new rota to the team',
    header: 'You supervise a warehouse shift at {company}. Head office has changed the shift pattern from next month.',
    situation: 'You supervise a 15 person warehouse shift at {company}. Head office has decided that from next month the shift pattern changes from five eight hour days to four ten hour days, to match a new delivery schedule. The decision is final. It means longer days, a three day weekend, and the loss of the Friday early finish that three of your team use for childcare pickups. The change was mentioned in a company wide email that most of the team did not read. You have the team briefing at 6am tomorrow and you know that {p1}, an informal leader on the shift, has already said "they never ask us anything." Head office has given you the rota and a two page FAQ, and has said that individual flexibility requests go to HR after the change takes effect.',
    prompt: 'What would you say to the team at the 6am briefing? Speak as you would say it.',
    mcqPrompt: 'What is the most effective way to run the 6am briefing?',
    facts: ['The pattern changes to four ten hour days next month, decision final', 'Three team members lose a Friday early finish used for childcare', 'Most of the team have not read the announcement', '{p1} is already vocal about not being consulted', 'Flexibility requests go to HR after the change'],
    constraints: ['Decision is final', 'Six minute briefing slot at 6am', 'HR process comes after the change'],
    stakeholders: ['The shift team', '{p1}', 'The three parents', 'Head office and HR'],
    ideal: [
      { text: 'Explain the reason for the change, the new delivery schedule, and what does not change, such as pay and the team', indicator: 'CHANGE-E1', fact: 0 },
      { text: 'Acknowledge what people lose, especially the Friday early finish for childcare, without dismissing it', indicator: 'CHANGE-E2', fact: 1 },
      { text: 'Make the next step and its timing concrete: when the rota starts, where the FAQ is, when you will meet individuals', indicator: 'CHANGE-E3', fact: 4 },
      { text: 'Separate what is decided from what the team can still shape, such as how the ten hour days are split or break timings', indicator: 'CHANGE-E4', fact: 0 },
    ],
    modelAnswer: 'I would say: "From the first of next month our shift pattern changes to four ten hour days. The reason is the new delivery schedule; trucks arrive later and the site has to be running longer four days a week. Pay, the team and who you work with do not change. I know this means longer days and I know three of you use the Friday finish for school pickups; that is a real loss and I am not going to pretend it is not. What is decided is the four day pattern. What we can still shape is which day is off, how breaks fall in a ten hour day and start times within a window, and I want your views on that by Friday. Anyone with a childcare or care issue, come and see me today or tomorrow and I will work with you and HR before the change, not after." I would leave time for questions.',
    weak: ['Reads the head office FAQ aloud and moves on', 'Says the decision was head office\'s and there is nothing anyone can do', 'Overstates that nobody will be worse off'],
    mcq: [{
      q: 'How do you run the 6am briefing?', options: [
        { level: 'L3', text: 'Give the reason and what stays the same, name the Friday childcare loss honestly, say what is decided and what the team can shape, and offer individual conversations this week.' },
        { level: 'L2', text: 'Explain the new pattern and the delivery schedule behind it, hand out the FAQ, and tell people to raise flexibility requests with HR.' },
        { level: 'L1', text: 'Announce the new rota, say the decision came from head office and is final, and ask people to read the email.' },
        { level: 'L0', text: 'Focus on the three day weekend as a benefit and say nobody should be worse off once they get used to it.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CHANGE', tag: 'T5', difficulty: 'Medium', title: 'The system your team did not want',
    header: 'You lead a claims processing team at {company}. A new system goes live in three weeks and your team is resisting.',
    situation: 'You lead a 20 person claims processing team at {company}. In three weeks a new claims system replaces one the team has used for nine years. Training has been offered twice and attendance was under half. Error rates in the pilot group were high for the first fortnight. {p2}, your most experienced processor and the person everyone goes to for help, has said openly that the new system is "slower and built by people who have never processed a claim." Head office is measuring go live readiness by training completion and has asked you to explain your team\'s number. You believe the system is genuinely better for customers in the long run, but you also know {p2} is right about two specific screens being slower. You have a team meeting this afternoon.',
    prompt: 'What would you say to the team this afternoon, and what would you do with {p2}? Speak as you would say it.',
    mcqPrompt: 'What should you do about {p2}\'s opposition?',
    facts: ['Go live in three weeks after nine years on the old system', 'Training attendance under half; pilot errors high for a fortnight', '{p2} is influential and openly opposed, and right about two slow screens', 'Head office measures readiness by training completion'],
    constraints: ['Three weeks', 'Head office scrutiny', '{p2}\'s influence'],
    stakeholders: ['The team', '{p2}', 'Head office', 'Customers'],
    ideal: [
      { text: 'Explain why the change is happening and what it means for customers, and what does not change, such as the team\'s expertise', indicator: 'CHANGE-E1', fact: 0 },
      { text: 'Acknowledge the loss and the legitimate criticism: nine years of fluency and two slower screens, and do not dismiss the pilot errors', indicator: 'CHANGE-E2', fact: 2 },
      { text: 'Make the next steps concrete: training dates this week, a floor walker in week one, and a specific date to review the two screens', indicator: 'CHANGE-E3', fact: 1 },
      { text: 'Separate what is decided, go live, from what the team can shape, such as workarounds and the feedback route, and give {p2} a role in it', indicator: 'CHANGE-E4', fact: 2 },
    ],
    modelAnswer: 'To the team I would say: the new system goes live in three weeks; that is decided. The reason is that customers will see claim status in real time and we stop re-keying into three systems. What does not change is that you are the people who know claims. I would then say what I agree with: two screens are slower, {p2} is right, and the pilot showed a hard first fortnight; I would not pretend otherwise. Concretely: training runs Tuesday and Thursday this week and everyone attends; a floor walker is with us for week one; and I have logged the two screens with the project with a review date. Then what we can shape: the workarounds and the order we move claim types over. I would ask {p2} to lead that, because the team already goes to them. With {p2} privately, I would ask for their help, not their silence.',
    weak: ['Tells the team the system is great and they need to get on board', 'Threatens consequences for not completing training', 'Sidelines {p2} to reduce their influence'],
    mcq: [{
      q: 'What do you do about {p2}?', options: [
        { level: 'L3', text: 'Acknowledge publicly that {p2} is right about the two screens, log them with a review date, and ask {p2} to lead the team\'s workarounds and cutover order.' },
        { level: 'L2', text: 'Meet {p2} privately, hear their concerns, and ask them to keep criticism out of team settings until after go live.' },
        { level: 'L1', text: 'Pair {p2} with the project team so they can see the reasons for the design and hopefully change their view.' },
        { level: 'L0', text: 'Move {p2} to a different queue during the transition so their opinions have less influence on the rest of the team.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CHANGE', tag: 'T2', difficulty: 'High', title: 'The restructure you cannot fully explain yet',
    header: 'You are a department head at {company}. A restructure has been announced that will remove roles in your department, and details are still being decided.',
    situation: 'You lead a department of 45 at {company}. This morning the executive team announced a restructure that will reduce the company\'s headcount by about 8 percent over four months, with consultation starting in three weeks. You know your department will lose roles but not which ones, and you have been told not to speculate. Two of your managers have already been asked by their teams whether they should update their CVs. A major project deadline in five weeks depends on the whole department staying engaged. {p3}, a strong performer, has come to you and said "I would rather know now if it is me, so I can plan." You have an all hands with the department in an hour and you cannot answer the question everyone will ask.',
    prompt: 'What would you say at the all hands, and what would you say to {p3}? Speak as you would say it.',
    mcqPrompt: 'What is the most effective message at the all hands?',
    facts: ['8 percent reduction over four months, consultation in three weeks', 'Your department loses roles; which ones is undecided', 'You are told not to speculate', 'A project deadline in five weeks needs engagement', '{p3} wants to know now if it is them'],
    constraints: ['Cannot say who is affected', 'One hour to prepare', 'Legal consultation process'],
    stakeholders: ['The department', 'Your managers', '{p3}', 'The executive team', 'The project'],
    ideal: [
      { text: 'Explain the reason for the restructure as stated and what does not change, such as pay, the project and how the team is treated', indicator: 'CHANGE-E1', fact: 0 },
      { text: 'Acknowledge the fear and the loss honestly, including that not knowing is hard and that some roles will go, without false reassurance', indicator: 'CHANGE-E2', fact: 1 },
      { text: 'Make the next step and its timing concrete: consultation in three weeks, what happens then, and when you will next speak to them', indicator: 'CHANGE-E3', fact: 0 },
      { text: 'Separate what is decided from what is not, and be clear that you will not speculate, while saying what people can do now', indicator: 'CHANGE-E4', fact: 2 },
    ],
    modelAnswer: 'At the all hands: "You have seen the announcement. The company is reducing headcount by about 8 percent over four months. Our department will be affected; I do not know which roles, and I will not guess, because a guess from me would be worse than the wait. Consultation starts in three weeks, and at that point affected people will hear individually before anything is said to the group. What does not change today: your pay, your work, and how we treat each other. I know not knowing is the hardest part. I will hold a fifteen minute update every Monday whether or not there is news. The project deadline in five weeks still matters, and I will make sure the work you do on it counts in any process." To {p3} privately: "I do not know, and if I did I could not tell you before consultation. Planning is sensible and I will not hold it against you. Here is what I can do: a straight conversation the day I am allowed to have one."',
    weak: ['Reassures everyone that their jobs are probably safe', 'Refuses to discuss the restructure and talks only about the project', 'Tells {p3} privately that they are not at risk'],
    mcq: [{
      q: 'What is the most effective message at the all hands?', options: [
        { level: 'L3', text: 'State the reason and the timeline, say plainly that roles will go and you will not guess which, name what does not change, and commit to weekly updates even without news.' },
        { level: 'L2', text: 'Explain the announcement, say consultation begins in three weeks, and ask people to focus on the project in the meantime.' },
        { level: 'L1', text: 'Reassure the department that strong performers have little to worry about and that the project deadline is the priority.' },
        { level: 'L0', text: 'Keep the all hands to the project and say the restructure will be covered by HR when there is something to say.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CONFL', tag: 'T2', difficulty: 'Low', title: 'Two colleagues, one desk by the window',
    header: 'You supervise a small office team at {company}. Two team members are in a running dispute over a desk.',
    situation: 'You supervise an eight person team at {company}. Since the office moved to hot desking, {p1} and {p2} have argued twice about the desk by the window, once in front of a visitor. {p1} arrives early and takes it most days; {p2} says {p1} "reserves it with a jacket" and that the window desk is the only one where their screen glare is manageable because of a visual condition they have mentioned before. {p1} says they have a long commute and being early should count for something, and that {p2} "makes everything about their needs." Other team members are starting to take sides. Both have asked you to sort it out and each has told you the other is being unreasonable.',
    prompt: 'What would you do, and what would you say to {p1} and {p2}? Speak as you would say it.',
    mcqPrompt: 'What is the right way to resolve the desk dispute?',
    facts: ['Two arguments, one in front of a visitor', '{p2} has a glare related need for the window desk', '{p1} arrives early and feels that should count', 'The team is taking sides'],
    constraints: ['Hot desking policy', 'An accessibility need'],
    stakeholders: ['{p1}', '{p2}', 'The rest of the team'],
    ideal: [
      { text: 'Hear each person\'s position separately and restate it to their satisfaction', indicator: 'CONFL-E1', fact: 2 },
      { text: 'Identify the interests beneath: {p2} needs a glare free screen, {p1} wants effort recognized and a predictable spot', indicator: 'CONFL-E2', fact: 1 },
      { text: 'Focus on the problem, glare and predictability, not on who is unreasonable', indicator: 'CONFL-E3', fact: 3 },
      { text: 'Agree a specific, testable resolution, such as an anti glare screen or a fixed accommodation, and how future desk issues get raised', indicator: 'CONFL-E4', fact: 0 },
    ],
    modelAnswer: 'I would speak to each separately first. To {p2}: I would confirm the glare issue and that they need a workable screen every day, and I would say that is an accommodation, not a favour. To {p1}: I would acknowledge the early starts and the wish for a predictable desk, and I would be clear that a jacket is not a reservation system. Then together: the problem is glare and predictability, not each other. I would propose that {p2} has the window desk as an agreed accommodation, and that I ask facilities for an anti glare filter and a second low glare position so {p1} has a predictable option too. I would ask them both whether that works, note the agreement, and say that desk issues come to me before they become arguments, especially in front of visitors.',
    weak: ['Tells them to sort it out between themselves', 'Rules in {p1}\'s favour because first come first served', 'Bans everyone from the window desk'],
    mcq: [{
      q: 'How do you resolve the desk dispute?', options: [
        { level: 'L3', text: 'Hear each separately, treat the glare need as an accommodation, recognize {p1}\'s wish for predictability, and agree a filter and a second low glare desk with a route for future issues.' },
        { level: 'L2', text: 'Assign the window desk to {p2} because of the visual condition and explain to {p1} that accessibility comes first.' },
        { level: 'L1', text: 'Set a rota for the window desk so {p1} and {p2} alternate days and nobody feels favoured.' },
        { level: 'L0', text: 'Tell both of them that hot desking is first come first served and they need to behave like adults about it.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CONFL', tag: 'T3', difficulty: 'Medium', title: 'Sales and delivery blame each other',
    header: 'You are a general manager at {company}. Your sales lead and delivery lead are in open conflict over a failing client account.',
    situation: 'You are a general manager at {company}. A large client account is in trouble: the client has complained about missed milestones. {p1}, your sales lead, says delivery "cannot execute what was sold." {p2}, your delivery lead, says sales "sold a scope we never agreed and a timeline nobody checked." Both are right about something: the contract includes a module the delivery team had not built, and the delivery team accepted the plan without objection at kickoff. The two have stopped speaking directly and route everything through you. Their teams have started copying each other\'s managers on every email. The client wants a recovery plan in a week. You have both leads in your office now and 40 minutes. Neither has looked at the other since they sat down.',
    prompt: 'What would you say and do in the 40 minutes? Speak as you would say it.',
    mcqPrompt: 'What is the most productive use of the 40 minutes?',
    facts: ['Client complaint about missed milestones and a recovery plan due in a week', 'Sales sold a module that was not built', 'Delivery accepted the plan at kickoff without objection', 'The two leads no longer speak directly; teams are escalating'],
    constraints: ['One week to a recovery plan', '40 minutes'],
    stakeholders: ['{p1}', '{p2}', 'The client', 'Both teams'],
    ideal: [
      { text: 'Hear each lead\'s position and restate it accurately, including the part each is right about', indicator: 'CONFL-E1', fact: 1 },
      { text: 'Surface the interests and constraints beneath: sales needs sellable scope, delivery needs a say before commitments', indicator: 'CONFL-E2', fact: 2 },
      { text: 'Refocus on the shared goal, the client recovery plan, rather than on who caused it', indicator: 'CONFL-E3', fact: 0 },
      { text: 'Agree a specific resolution: joint ownership of the recovery plan and a rule for future deals, such as delivery sign off on scope before contract', indicator: 'CONFL-E4', fact: 3 },
    ],
    modelAnswer: 'I would start by saying what I have heard from each and checking I have it right: {p1}, delivery accepted a plan at kickoff and is now missing it; {p2}, the contract includes a module that did not exist and nobody flagged the timeline. Both true. Then I would name the interests: sales needs to sell what we can deliver, delivery needs a voice before we commit. Then the shared goal: a recovery plan to the client in a week, which neither can produce alone. I would ask them to build it together, with {p2} owning what is deliverable by when and {p1} owning the client conversation about the module. For the future, delivery signs off scope and timeline before any contract. I would ask their teams to stop copying managers and route disagreements to the two of them. We would meet again in three days.',
    weak: ['Decides who is to blame and tells them', 'Takes the client recovery plan away from both and does it yourself', 'Asks them to be more collaborative and sends them away'],
    mcq: [{
      q: 'What do you do in the 40 minutes?', options: [
        { level: 'L3', text: 'Restate each position including where each is right, name the underlying interests, refocus on the recovery plan they build jointly, and set a scope sign off rule for future deals.' },
        { level: 'L2', text: 'Tell them both that the client matters more than blame, assign the recovery plan to delivery and the client conversation to sales, and move on.' },
        { level: 'L1', text: 'Ask each to describe what the other did wrong so it is all on the table, then ask them to shake hands and work together.' },
        { level: 'L0', text: 'Decide that sales caused the problem by selling an unbuilt module, tell {p1} so, and give {p2} full control of the recovery plan.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CONFL', tag: 'T3', difficulty: 'High', title: 'The dispute that has reached HR',
    header: 'You are a senior manager at {company}. Two of your team leads have each filed a complaint about the other.',
    situation: 'You are a senior manager at {company} with six team leads. Two of them, {p2} and {p3}, have each filed a formal complaint with HR about the other in the same week. {p2} says {p3} excludes their team from planning and takes credit for joint work. {p3} says {p2} misses shared deadlines and blames others publicly. Their teams depend on each other for a monthly release that is now at risk. HR has asked you to attempt an informal resolution before a formal process begins, and both have agreed to one joint meeting with you. You know that the conflict began eight months ago when {p3} was given a project both had wanted, and that neither has said this aloud. You have an hour and both are in the room, arms folded.',
    prompt: 'What would you say and do in the hour? Speak as you would say it, including how you would handle the unspoken cause.',
    mcqPrompt: 'How should you run the joint meeting?',
    facts: ['Cross complaints filed with HR in the same week', 'The monthly release depends on both teams', 'HR wants an informal attempt first', 'The conflict began when {p3} got a project both wanted, unspoken', 'One hour, both defensive'],
    constraints: ['A formal process looms', 'One meeting', 'Both defensive'],
    stakeholders: ['{p2}', '{p3}', 'Their teams', 'HR', 'The release'],
    ideal: [
      { text: 'Hear each position in turn without interruption and restate it to each person\'s satisfaction before moving on', indicator: 'CONFL-E1', fact: 0 },
      { text: 'Surface the interests and the unspoken cause carefully, naming the project decision as a possible turning point and inviting their view', indicator: 'CONFL-E2', fact: 3 },
      { text: 'Keep the focus on the shared goal, the release and two functioning teams, and on behaviors, not character', indicator: 'CONFL-E3', fact: 1 },
      { text: 'Agree a specific, testable resolution with a review date and a route for the next disagreement before HR is involved', indicator: 'CONFL-E4', fact: 2 },
    ],
    modelAnswer: 'I would set the ground rules: each speaks uninterrupted, I restate what I heard, and we are here for the release and two teams that work, not to decide who is right. I would hear {p2}, restate it, check it; then {p3}, the same. Then I would say what I have noticed: this started around the time the project was awarded, and I would ask whether that is part of it, because if it is, it deserves to be said. I would own my part in how that decision was communicated. Then I would move to behaviors: joint planning with both teams present, credit given by name in release notes, shared deadlines tracked in one place, and no public blame; disagreements come to me within a day. We would review in a month and I would tell HR we have a plan. I would ask each to name one thing they will do differently from tomorrow.',
    weak: ['Tells them both to act professionally and warns of consequences', 'Lets the meeting become a re-argument of the complaints', 'Avoids the project decision because it is uncomfortable'],
    mcq: [{
      q: 'How do you run the hour?', options: [
        { level: 'L3', text: 'Hear and restate each position, raise the project decision as a possible root and own your part, refocus on the release and behaviors, and agree testable changes with a review date.' },
        { level: 'L2', text: 'Let each present their complaint, identify the behaviors that need to change, and agree a shared deadline tracker and joint planning meetings.' },
        { level: 'L1', text: 'Remind them both that formal processes damage careers and ask them to agree to work professionally together for the sake of the release.' },
        { level: 'L0', text: 'Tell them that you will decide who leads the release going forward and that the other will need to fall in line or face the formal process.' },
      ] },
    ],
  },
  {
    skillId: 'SK-COMM', tag: 'T4', difficulty: 'Low', title: 'The big order at a thin margin',
    header: 'You are a sales team lead at {company}. A rep has brought you a large order that needs a deep discount to close.',
    situation: 'You lead a sales team at {company}. {p1}, one of your reps, has a prospect ready to place an order for {product} worth 500,000 in revenue, the largest single order this year, but the buyer will only sign at a 25 percent discount. The table below shows the margin picture: at list price the gross margin is 38 percent; at 25 percent off it falls to 17 percent, and after the delivery and onboarding costs specific to this customer, which are higher than usual because of their three remote sites, the contribution is close to zero. {p1} points out that the order would take the team past its annual revenue target and that the customer could become a reference. Your commission plan and {p1}\'s both pay on revenue.',
    prompt: 'What would you decide, and what would you say to {p1}? Use the numbers to explain your reasoning.',
    mcqPrompt: 'What should you decide about the order?',
    facts: ['500,000 order at 25 percent discount', 'Margin falls from 38 to 17 percent, contribution near zero after site costs', 'The order would beat the revenue target', 'Commission pays on revenue'],
    constraints: ['Revenue incentives', 'Largest order of the year'],
    stakeholders: ['{p1}', 'The prospect', 'Finance', 'The delivery team serving three sites'],
    ideal: [
      { text: 'Quantify the margin and contribution effect, not just the revenue: 17 percent gross and near zero contribution', indicator: 'COMM-E1', fact: 1 },
      { text: 'Consider customer value beyond the transaction, such as a reference and future orders, and weigh it honestly', indicator: 'COMM-E2', fact: 2 },
      { text: 'Identify the hidden cost: three remote sites raise delivery and onboarding costs', indicator: 'COMM-E3', fact: 1 },
      { text: 'Choose the option that protects long term value, for example a smaller discount with reduced scope or phased sites, even if it risks the revenue target', indicator: 'COMM-E4', fact: 3 },
    ],
    modelAnswer: 'I would not approve the order as it stands. The revenue is attractive but the table says the contribution is close to zero once the three remote sites are onboarded, so we would be working for free to hit a revenue target, and the commission plan is pushing both of us that way. I would say that to {p1} plainly. Then I would look for a version that works: 12 percent off with the customer taking phased onboarding of the two remote sites in year two, which restores contribution to a positive number; or full discount on a smaller initial scope. The reference value is real and I would count it, but a reference customer that loses us money teaches the market to expect 25 percent. I would help {p1} take a counter offer back with the value case.',
    weak: ['Approves the discount because the revenue target matters', 'Refuses any discount and loses the order', 'Approves it and plans to recover margin on future orders that may not come'],
    media: { type: 'table', title: 'Margin at different discount levels for this order', alt: 'Table showing revenue, gross margin percent and contribution after site costs at list price, 12 percent off and 25 percent off', data: { columns: ['Discount', 'Revenue', 'Gross margin', 'Contribution after site costs'], rows: [['0 percent', '667,000', '38 percent', '190,000'], ['12 percent', '587,000', '29 percent', '105,000'], ['25 percent', '500,000', '17 percent', '5,000']] } },
    mcq: [
      { q: 'What do you decide?', options: [
        { level: 'L3', text: 'Decline 25 percent because contribution is near zero after site costs, and help {p1} counter at 12 percent with phased onboarding of the remote sites.' },
        { level: 'L2', text: 'Approve a smaller discount of 15 percent and ask {p1} to persuade the buyer, since 25 percent leaves too little margin.' },
        { level: 'L1', text: 'Approve the order because it is the largest of the year, beats the revenue target and could become a reference.' },
        { level: 'L0', text: 'Approve the 25 percent discount and plan to recover the margin through higher prices on future orders from this customer.' },
      ] },
      { q: 'Which figure in the table changes the decision most?', options: [
        { level: 'L3', text: 'Contribution after site costs at 25 percent off, because it shows the order barely covers its own delivery.' },
        { level: 'L2', text: 'Gross margin falling from 38 to 17 percent, because it shows how much value the discount destroys.' },
        { level: 'L1', text: 'The 500,000 revenue figure, because that is what the annual target and both commission plans actually measure.' },
        { level: 'L0', text: 'The 667,000 list price revenue, because it shows what the order would have been worth.' },
      ] },
    ],
  },
  {
    skillId: 'SK-COMM', tag: 'T1', difficulty: 'Medium', title: 'Cutting the cost that customers notice',
    header: 'You run a regional service operation at {company}. Finance has asked for a 10 percent cost cut and proposed removing the same day repair option.',
    situation: 'You run a regional field service operation at {company} with a cost base of 4 million. Finance has asked for a 10 percent cost reduction next year and has proposed removing the same day repair option, which would save 450,000 by cutting standby engineers. The table below shows what you know: same day repair is used by 15 percent of customers, but those customers generate 40 percent of service contract revenue and renew at 92 percent against 71 percent for the rest. Two alternative savings exist: consolidating two depots saves 280,000 with longer travel times, and moving to a cheaper parts supplier saves 200,000 with a slightly higher failure rate. The finance director wants your answer by Friday and has said "same day is the easy one."',
    prompt: 'What would you propose to the finance director? Use the table to explain the trade offs.',
    mcqPrompt: 'Which cost reduction should you propose?',
    facts: ['10 percent cut needed from a 4 million base', 'Same day repair saves 450,000 but serves customers with 40 percent of revenue and 92 percent renewal', 'Depot consolidation saves 280,000 with slower travel', 'Cheaper parts save 200,000 with higher failures'],
    constraints: ['Friday deadline', 'Finance prefers the simple option'],
    stakeholders: ['The finance director', 'Same day customers', 'Field engineers', 'All service customers'],
    ideal: [
      { text: 'Quantify the revenue and renewal at risk from cutting same day repair, not only the 450,000 saving', indicator: 'COMM-E1', fact: 1 },
      { text: 'Consider customer value and retention: the same day customers renew at 92 percent and carry 40 percent of revenue', indicator: 'COMM-E2', fact: 1 },
      { text: 'Identify the hidden costs of the alternatives: travel time and failure rate, and quantify them', indicator: 'COMM-E3', fact: 3 },
      { text: 'Choose the combination that protects long term value and still reaches the target, or say honestly what it takes', indicator: 'COMM-E4', fact: 0 },
    ],
    modelAnswer: 'I would tell the finance director that same day repair looks like the easy 450,000 but it is the most expensive option we have. Those customers are 15 percent of the base and 40 percent of contract revenue, renewing at 92 percent against 71; if renewal for that group fell even to the average, the lost revenue would exceed the saving within two years. Instead I would propose the depot consolidation at 280,000, with a plan to hold response times through routing, plus a partial parts supplier switch for non critical parts at about 120,000, keeping premium parts where failures matter. That reaches the 10 percent. If finance insists on same day, I would propose pricing it as a premium tier rather than removing it, which turns a cost into revenue. I would send the numbers on one page.',
    weak: ['Accepts the same day cut because finance called it easy', 'Refuses all cuts and argues for the status quo', 'Cuts the parts quality across the board because it is invisible in the short term'],
    media: { type: 'table', title: 'Cost reduction options', alt: 'Table of three options with saving, customers affected, revenue share and renewal impact', data: { columns: ['Option', 'Saving', 'Customers affected', 'Revenue share', 'Known effect'], rows: [['Remove same day repair', '450,000', '15 percent', '40 percent', 'Renewal 92 percent vs 71 percent'], ['Consolidate two depots', '280,000', 'All in region', '100 percent', 'Longer travel times'], ['Cheaper parts supplier', '200,000', 'All', '100 percent', 'Slightly higher failure rate']] } },
    mcq: [{
      q: 'Which reduction do you propose?', options: [
        { level: 'L3', text: 'Depot consolidation plus a partial parts switch on non critical parts, because same day customers carry 40 percent of revenue and renew at 92 percent.' },
        { level: 'L2', text: 'Depot consolidation and the full parts supplier switch, because they reach the target without removing a customer facing service.' },
        { level: 'L1', text: 'Remove same day repair as finance suggests, since it is the largest single saving and only 15 percent of customers use it.' },
        { level: 'L0', text: 'Remove same day repair and consolidate depots to exceed the target and give finance headroom for next year.' },
      ] },
    ],
  },
  {
    skillId: 'SK-COMM', tag: 'T4', difficulty: 'High', title: 'Growth that eats cash',
    header: 'You are a business unit head at {company}. Your unit has doubled revenue and your CFO says it is running out of cash.',
    situation: 'You lead a business unit at {company} selling {product} to enterprise customers. Revenue has doubled in eighteen months and the board has praised the growth. Yesterday the CFO showed you the chart below: operating cash flow has turned negative and is worsening each quarter. The causes are visible in the numbers: enterprise customers pay in 90 days while you pay suppliers in 30; inventory has tripled to support faster delivery promises; and the sales team has been offering extended payment terms to close deals. The CFO wants a plan in a week and has suggested pausing new enterprise deals. Your sales director says a pause would hand the market to a competitor. Two large deals are due to close this month, both with 120 day terms.',
    prompt: 'What would you propose to the CFO? Use the chart and the numbers to explain how you would protect both growth and cash.',
    mcqPrompt: 'What is the right response to the cash position?',
    facts: ['Revenue doubled; operating cash flow negative and worsening', 'Customers pay in 90 days, suppliers in 30', 'Inventory tripled', 'Sales offers extended terms; two deals pending at 120 days'],
    constraints: ['Plan in a week', 'Competitive market'],
    stakeholders: ['The CFO', 'The sales director', 'Enterprise customers', 'Suppliers', 'The board'],
    ideal: [
      { text: 'Quantify the cash effect of the terms gap and inventory, rather than defending the revenue growth', indicator: 'COMM-E1', fact: 1 },
      { text: 'Consider customer value: which customers justify extended terms and which do not', indicator: 'COMM-E2', fact: 3 },
      { text: 'Identify the hidden costs: extended terms are a discount in disguise, and inventory ties up cash for a delivery promise that may not be valued', indicator: 'COMM-E3', fact: 2 },
      { text: 'Choose actions that protect long term value: fix terms and inventory before pausing growth, and price extended terms explicitly', indicator: 'COMM-E4', fact: 0 },
    ],
    modelAnswer: 'I would tell the CFO the growth is real but we are financing our customers and our own inventory, and the chart shows that gets worse the faster we grow. The plan: first, payment terms become a priced item, with 120 day terms carrying a 2 percent premium or requiring finance approval, and the two pending deals renegotiated to 60 days or the premium before signature. Second, inventory: return to a 45 day cover for all but the top ten accounts, freeing a large part of the tripled stock. Third, supplier terms: negotiate 60 days with our two biggest suppliers using our growth as leverage. I would model the cash effect of each over four quarters and show it against the chart. I would not pause enterprise sales, but I would pause deals that do not meet the terms and margin rule, and say so to the sales director.',
    weak: ['Defends the growth and asks the CFO for more working capital', 'Pauses all enterprise deals as the CFO suggested', 'Fixes inventory alone and leaves the payment terms that drive the gap'],
    media: { type: 'chart', title: 'Revenue and operating cash flow by quarter', alt: 'Two line chart over six quarters: revenue rising from 10 to 21 million; operating cash flow falling from plus 1.2 million to minus 2.8 million', data: { points: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6'], series: [{ name: 'Revenue (m)', values: [10, 12, 14.5, 17, 19, 21] }, { name: 'Operating cash flow (m)', values: [1.2, 0.6, -0.3, -1.1, -2.0, -2.8] }] } },
    mcq: [
      { q: 'What do you propose to the CFO?', options: [
        { level: 'L3', text: 'Price extended payment terms, cut inventory cover outside top accounts, extend supplier terms, and renegotiate the two pending deals, pausing only deals that fail the rule.' },
        { level: 'L2', text: 'Reduce inventory to previous levels and ask sales to stop offering terms beyond 90 days on new deals from next quarter.' },
        { level: 'L1', text: 'Ask the CFO for a working capital facility to bridge the gap while revenue growth continues.' },
        { level: 'L0', text: 'Pause new enterprise deals for two quarters as the CFO suggested until cash flow returns to positive.' },
      ] },
      { q: 'What does the chart show about the relationship between growth and cash?', options: [
        { level: 'L3', text: 'Each increment of revenue is worsening cash flow, which means the business model is consuming cash as it grows and the terms and inventory must change.' },
        { level: 'L2', text: 'Cash flow has turned negative while revenue grows, so costs are growing faster than revenue.' },
        { level: 'L1', text: 'Revenue growth is strong and cash flow will recover once the enterprise customers start paying.' },
        { level: 'L0', text: 'The two lines are unrelated because cash flow depends on timing and revenue is the real measure of performance.' },
      ] },
    ],
  },
];
