// Scripted scenario seeds, group B: Prioritization, Data Driven Decision Making, Stakeholder Management, Customer Centricity.
export default [
  {
    skillId: 'SK-PRIOR', tag: 'T7', difficulty: 'Low', title: 'Monday morning, five asks',
    header: 'You are a team lead in the finance operations team at {company}. It is 8:30 on Monday and five requests are waiting.',
    situation: 'You are a team lead in finance operations at {company} with three analysts. It is 8:30 on Monday. Waiting for you: the CFO\'s office wants a one page cash summary by noon for a board pre-read; a regional manager is chasing a supplier payment that is two weeks late and threatening to pause deliveries; the audit team needs three sample invoices by Wednesday; a new analyst starts at 10 and has no laptop yet; and your own manager has asked for a "quick" review of a process document, no date given. One analyst is out sick. The table below shows what each request needs. You have the morning to allocate work across yourself and two analysts, and you will not get to everything today.',
    prompt: 'What would you do this morning, in what order, and what would you say to anyone who has to wait? Explain your reasoning.',
    mcqPrompt: 'What is the best order of work for this morning?',
    facts: ['Board pre-read cash summary due at noon', 'Supplier payment two weeks late, deliveries threatened', 'Audit samples due Wednesday', 'New analyst starts at 10 with no laptop', 'Process review has no date'],
    constraints: ['One analyst out sick', 'Only the morning and two analysts plus you'],
    stakeholders: ['The CFO\'s office and board', 'The regional manager and supplier', 'Audit', 'The new analyst', 'Your manager'],
    ideal: [
      { text: 'Rank by business impact and risk: the board summary and the supplier payment first, rather than by who asked most recently', indicator: 'PRIOR-E1', fact: 0 },
      { text: 'Recognize the dependency: the new analyst\'s laptop is enabling work that unlocks capacity, so raise it with IT immediately', indicator: 'PRIOR-E2', fact: 3 },
      { text: 'Say no or not now explicitly to the process review, with a reason and a proposed date', indicator: 'PRIOR-E3', fact: 4 },
      { text: 'Re-plan around the sick analyst rather than adding everything to the remaining people', indicator: 'PRIOR-E4', fact: 1 },
    ],
    modelAnswer: 'First I would message IT about the new analyst\'s laptop, because that is two minutes and unblocks a person for the rest of the week. Then I would take the cash summary myself, since it is due at noon and goes to the board. I would ask one analyst to resolve the supplier payment this morning and call the regional manager to confirm, because deliveries pausing is the biggest operational risk. The second analyst pulls the audit samples, due Wednesday, so it does not become urgent. I would reply to my manager that the process review will get a proper read on Thursday, with the reason. At 10 I would spend fifteen minutes with the new analyst and pair them with the audit sample work.',
    weak: ['Works through the requests in the order they arrived', 'Tries to do everything today and asks the two analysts to stay late', 'Does the process review first because it came from your manager'],
    media: { type: 'table', title: 'Requests waiting on Monday morning', alt: 'Table of five requests with requester, due time and estimated effort', data: { columns: ['Request', 'From', 'Due', 'Effort'], rows: [['Cash summary for board pre-read', 'CFO office', 'Noon today', '2 hours'], ['Late supplier payment', 'Regional manager', 'Deliveries paused if unpaid', '1.5 hours'], ['Three sample invoices', 'Audit', 'Wednesday', '1 hour'], ['Laptop for new analyst', 'Starts 10:00', 'Today', '10 minutes to request'], ['Process document review', 'Your manager', 'No date', '1 hour']] } },
    mcq: [
      { q: 'What do you do first at 8:30?', options: [
        { level: 'L3', text: 'Send the laptop request to IT, then start the noon board summary while one analyst resolves the supplier payment.' },
        { level: 'L2', text: 'Start the board cash summary yourself immediately, since it has the earliest fixed deadline and the most senior audience.' },
        { level: 'L1', text: 'Call the regional manager about the supplier payment, since they are the person actively chasing you this morning.' },
        { level: 'L0', text: 'Read your manager\'s process document first so it is off your list before the day gets busy.' },
      ] },
      { q: 'What do you do about the process document review?', options: [
        { level: 'L3', text: 'Reply now that it will get a proper review on Thursday, explain the board and supplier priorities, and ask if that works.' },
        { level: 'L2', text: 'Reply that you will get to it later this week once the urgent items are done.' },
        { level: 'L1', text: 'Leave it in your inbox and get to it when there is a gap, since no date was given.' },
        { level: 'L0', text: 'Ask one of the two analysts to review it this morning so your manager is not kept waiting.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PRIOR', tag: 'T4', difficulty: 'Medium', title: 'The roadmap trade off',
    header: 'You are a product owner at {company}. The sprint is full and three stakeholders each want their item added.',
    situation: 'You are a product owner for {product} at {company}. Your team\'s two week sprint starts tomorrow and is fully committed. Three items have arrived today, each with a case. Sales wants a pricing page change for a deal that closes in ten days, worth about 4 percent of the quarter\'s target. Support wants a fix for a bug that generates 60 tickets a week and is now the top driver of complaints. Legal wants a cookie consent update they say is a regulatory requirement, with a deadline in five weeks. Your engineering lead estimates each at three to five days. Taking one in means pulling something out. The chart below shows ticket volume for the bug over the last eight weeks. The sponsor has asked you to make the call today.',
    prompt: 'Which item, if any, would you bring into the sprint, what would come out, and how would you explain the decision to the other two stakeholders?',
    mcqPrompt: 'Which item should come into the sprint?',
    facts: ['Sales pricing change supports a deal worth 4 percent of quarter target, closes in ten days', 'Support bug drives 60 tickets a week and is rising', 'Legal consent update is regulatory with a five week deadline', 'Each item is three to five days of work'],
    constraints: ['Sprint is fully committed', 'One in means one out', 'Decision needed today'],
    stakeholders: ['Sales', 'Support and affected customers', 'Legal', 'The engineering team', 'The sponsor'],
    ideal: [
      { text: 'Rank by impact and risk using the numbers: the rising ticket trend and the deal value, not by who pushed hardest', indicator: 'PRIOR-E1', fact: 1 },
      { text: 'Recognize the dependency and timing: the legal item has five weeks and fits the next sprint, so sequence it explicitly', indicator: 'PRIOR-E2', fact: 2 },
      { text: 'Tell the stakeholder who waits, with the reason and the sprint it lands in', indicator: 'PRIOR-E3', fact: 3 },
      { text: 'Name what comes out of the sprint to make room, rather than adding on top', indicator: 'PRIOR-E4', fact: 3 },
    ],
    modelAnswer: 'I would bring the support bug into the sprint. Sixty tickets a week and rising is the biggest ongoing cost and the chart shows it doubling since week four; every week we wait adds more. To make room I would pull the lowest value committed item, the analytics export polish, and tell the team why. The pricing change I would offer sales a manual workaround for the deal, since a ten day close does not need a product change, and schedule it for the next sprint if the deal needs it. The legal update has five weeks, so it goes into the next sprint as the first committed item, and I would confirm that date with legal in writing today. I would tell the sponsor the order and the reasoning.',
    weak: ['Adds all three to the sprint and asks the team to stretch', 'Picks the sales item because revenue is easiest to defend', 'Picks the legal item because "regulatory" sounds most serious without checking the deadline'],
    media: { type: 'chart', title: 'Weekly support tickets caused by the bug', alt: 'Line chart of weekly tickets from the bug rising from 28 in week 1 to 60 in week 8', data: { points: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7', 'W8'], series: [{ name: 'Tickets', values: [28, 30, 31, 34, 41, 48, 55, 60] }] } },
    mcq: [
      { q: 'Which item do you bring into tomorrow\'s sprint?', options: [
        { level: 'L3', text: 'The support bug, because the chart shows tickets doubling and rising every week, and you name the committed item that comes out to make room.' },
        { level: 'L2', text: 'The support bug, because it affects the most customers, and you ask the team whether they can absorb it alongside the committed work.' },
        { level: 'L1', text: 'The legal consent update, because regulatory work always takes precedence over commercial or support requests.' },
        { level: 'L0', text: 'The sales pricing change, because it has the nearest deadline and the sponsor will want the revenue this quarter.' },
      ] },
      { q: 'What do you tell the two stakeholders whose items are not in the sprint?', options: [
        { level: 'L3', text: 'The reason for the order, the sprint their item lands in, and for sales a manual workaround that protects the deal in the meantime.' },
        { level: 'L2', text: 'That their items are important and will be scheduled soon, and you will confirm the dates after the sprint planning meeting.' },
        { level: 'L1', text: 'That the team is at capacity and they should escalate to the sponsor if they feel their item cannot wait.' },
        { level: 'L0', text: 'Nothing yet, since the decision might change once the team looks at the estimates in more detail.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PRIOR', tag: 'T7', difficulty: 'High', title: 'The week the plan broke',
    header: 'You are a regional operations manager at {company}. A store flood, an audit and a launch are all landing in the same week.',
    situation: 'You are a regional operations manager for twelve stores at {company}. On Monday a burst pipe flooded your largest store, closing it for at least four days and displacing 30 staff. On Tuesday head office moved the annual compliance audit of two of your stores forward to Thursday. The regional {product} launch, planned for months, is on Saturday with marketing spend already committed. Your area managers are asking for direction on all three. You have a week of your own calendar already full of store visits and a performance review for an underperforming store manager, {p2}, which you have postponed twice. The table below shows the commitments. Head office has asked what you will deliver this week and what will move.',
    prompt: 'What would you do this week, what would you drop or move, and how would you communicate it? Explain the reasoning behind the order.',
    mcqPrompt: 'What is the right call on this week\'s commitments?',
    facts: ['Flagship store closed at least four days with 30 displaced staff', 'Compliance audit of two stores moved to Thursday', '{product} launch on Saturday with committed spend', '{p2}\'s review already postponed twice', 'Calendar full of routine store visits'],
    constraints: ['One week, one you', 'Head office wants to know what moves', 'Spend is committed'],
    stakeholders: ['Displaced staff', 'Head office and audit', 'Marketing and customers for the launch', '{p2}', 'Area managers'],
    ideal: [
      { text: 'Rank by impact and risk: staff safety and pay at the flooded store, then the audit and the launch, and say why', indicator: 'PRIOR-E1', fact: 0 },
      { text: 'Identify the dependencies: redeploying flooded store staff to the launch and to audit preparation solves two problems at once', indicator: 'PRIOR-E2', fact: 0 },
      { text: 'Explicitly move the routine store visits and say what happens to {p2}\'s review instead of postponing it silently a third time', indicator: 'PRIOR-E3', fact: 3 },
      { text: 'Re-plan the week with area managers owning items, rather than adding all three to your own list', indicator: 'PRIOR-E4', fact: 4 },
    ],
    modelAnswer: 'First, the flooded store: on Monday I would confirm the 30 staff are safe, paid and redeployed, with the area manager owning the store recovery and insurance. Second, the audit: I would ask the two store managers to run the audit checklist Tuesday and Wednesday, with some redeployed flagship staff helping, and I would be present Thursday. Third, the launch: it goes ahead on Saturday because spend is committed and stores are ready, and the redeployed flagship staff add capacity in the neighboring stores. I would cancel all routine store visits this week and tell head office that is what moves. For {p2}, I would not postpone silently again: I would hold a shorter review on Friday, because a third postponement says the review does not matter. I would send head office the plan on Monday afternoon with owners.',
    weak: ['Tries to attend everything and does not change the calendar', 'Postpones the launch to focus on the flood, wasting committed spend', 'Postpones {p2}\'s review a third time without telling them why'],
    media: { type: 'table', title: 'This week\'s commitments', alt: 'Table of five commitments with day, who is affected and what is at stake', data: { columns: ['Commitment', 'When', 'Who is affected', 'At stake'], rows: [['Flagship store flood recovery', 'Mon to Thu', '30 staff, customers', 'Safety, pay, 15 percent of regional sales'], ['Compliance audit, two stores', 'Thursday', 'Two store managers', 'Audit rating, head office confidence'], ['{product} regional launch', 'Saturday', 'All 12 stores, marketing', 'Committed spend, customer footfall'], ['Performance review with {p2}', 'Postponed twice', '{p2}', 'Credibility of the review process'], ['Routine store visits', 'All week', 'Store managers', 'Routine oversight']] } },
    mcq: [
      { q: 'Head office asks what will move this week. What do you tell them?', options: [
        { level: 'L3', text: 'Routine visits are cancelled; flood recovery, audit and launch go ahead with named area managers owning each, and {p2}\'s review happens on Friday in a shorter form.' },
        { level: 'L2', text: 'Routine visits are cancelled and the launch goes ahead; you will personally lead the flood recovery and attend the audit.' },
        { level: 'L1', text: 'You will do your best to cover everything and will let them know on Friday what did not get done.' },
        { level: 'L0', text: 'The launch should move to next month so the region can focus on the flood and the audit, even though spend is committed.' },
      ] },
      { q: 'How do you handle {p2}\'s performance review?', options: [
        { level: 'L3', text: 'Hold a shorter review on Friday and tell {p2} why the format changed, because a third silent postponement would say the review does not matter.' },
        { level: 'L2', text: 'Move it to next week and tell {p2} today with the reason and the new date.' },
        { level: 'L1', text: 'Ask the area manager to hold the review in your place so it happens this week.' },
        { level: 'L0', text: 'Postpone it again without a new date, since the flood and the audit clearly take precedence.' },
      ] },
    ],
  },
  {
    skillId: 'SK-DATADEC', tag: 'T4', difficulty: 'Low', title: 'One region is behind',
    header: 'You are a regional sales manager at {company}. The quarter to date chart has just landed in your inbox.',
    situation: 'You are a regional sales manager at {company} covering four territories. The quarter to date chart below has just arrived from finance. Three territories are at or above 60 percent of target with six weeks to go. The West territory is at 38 percent. {p1}, the West account manager, told you last month that two large renewals had slipped into next quarter because the client\'s procurement cycle changed, and that they were confident of closing them in early Q3. {p1} has hit target for the last three years. Your director has asked each regional manager to send a one paragraph note today on any territory below 50 percent with a proposed action. You have the chart, {p1}\'s explanation and thirty minutes.',
    prompt: 'What would you write to your director, and what action would you propose for West? Explain what in the chart drives your view.',
    mcqPrompt: 'What is the most appropriate action on West?',
    facts: ['Three territories at or above 60 percent, West at 38 percent, six weeks left', '{p1} attributes the gap to two renewals slipping into next quarter', '{p1} has hit target three years running', 'Director wants a note and action today'],
    constraints: ['Thirty minutes', 'One paragraph', 'Six weeks remain'],
    stakeholders: ['Your director', '{p1}', 'The West clients'],
    ideal: [
      { text: 'Identify the specific gap from the chart: West at 38 percent against a 60 percent peer group, roughly 22 points behind', indicator: 'DATADEC-E1', fact: 0 },
      { text: 'Distinguish what the chart shows, a gap, from the explanation offered, slipped renewals, and treat the explanation as a hypothesis to check', indicator: 'DATADEC-E2', fact: 1 },
      { text: 'Propose an action proportionate to the gap size and {p1}\'s record, such as a pipeline review this week rather than a performance process', indicator: 'DATADEC-E3', fact: 2 },
      { text: 'Name the data needed before a bigger call, for example the value and stage of the two renewals against the gap', indicator: 'DATADEC-E4', fact: 1 },
    ],
    modelAnswer: 'I would write that West is at 38 percent against 60 to 68 percent elsewhere, about 22 points behind with six weeks left. {p1} attributes it to two renewals moving to early Q3 because of a client procurement change. That is a plausible explanation, but I have not yet seen whether those two deals account for the whole gap or whether the rest of the pipeline is also soft. Proposed action: a pipeline review with {p1} on Wednesday to confirm the value and stage of the two renewals, and to identify what can close in the remaining six weeks. Given {p1}\'s three year record, I would not start a performance process; I would confirm the picture first and report back on Thursday with a revised forecast for West.',
    weak: ['Accepts {p1}\'s explanation and writes that West is fine', 'Proposes a performance improvement plan based on the single quarter number', 'Asks finance for a deeper analysis and proposes no action this week'],
    media: { type: 'chart', title: 'Quarter to date attainment by territory', alt: 'Bar chart: North 64 percent, East 68 percent, South 60 percent, West 38 percent of quarterly target', data: { points: ['North', 'East', 'South', 'West'], series: [{ name: 'Percent of target', values: [64, 68, 60, 38] }] } },
    mcq: [
      { q: 'What action do you propose for West in your note?', options: [
        { level: 'L3', text: 'A pipeline review this week to test whether the two slipped renewals explain the 22 point gap, with a revised forecast to follow.' },
        { level: 'L2', text: 'A conversation with {p1} to understand the gap, given that three strong years suggest the slip explanation is likely.' },
        { level: 'L1', text: 'No action yet, because {p1} has explained the slip and has a strong track record.' },
        { level: 'L0', text: 'A formal performance improvement plan for {p1}, because 38 percent with six weeks left is a clear miss.' },
      ] },
      { q: 'What does the chart tell you, on its own?', options: [
        { level: 'L3', text: 'West is about 22 points behind a peer group that is broadly consistent, which is a real gap but not yet a reason.' },
        { level: 'L2', text: 'West is significantly behind the other three territories and will probably miss its target this quarter.' },
        { level: 'L1', text: 'Two renewals slipping into next quarter explain the gap in West, so the chart confirms what the account manager said.' },
        { level: 'L0', text: 'The region is on track overall because three out of four territories are above 60 percent.' },
      ] },
    ],
  },
  {
    skillId: 'SK-DATADEC', tag: 'T4', difficulty: 'Medium', title: 'The dashboard that says two things',
    header: 'You manage a customer support centre for {company}. The monthly dashboard shows satisfaction up and repeat contacts up.',
    situation: 'You manage a 40 seat support centre at {company}. The monthly dashboard below shows two trends over six months. Customer satisfaction has risen from 71 to 79 percent. Repeat contacts, customers who call again within seven days about the same issue, have risen from 12 to 19 percent. Your team lead, {p2}, says the satisfaction number proves the new "warm close" script is working and wants to roll it out to the outsourced partner next month. Your finance partner has noticed the repeat contact cost and is asking whether the script is making agents close calls before the issue is solved. The average handling time has fallen from 9.1 to 7.4 minutes in the same period. The outsourcing decision needs an answer by Friday.',
    prompt: 'What would you decide about the rollout, and what would you say to {p2} and the finance partner? Use the dashboard to explain your view.',
    mcqPrompt: 'What should you do about rolling out the script?',
    facts: ['Satisfaction up from 71 to 79 percent', 'Repeat contacts up from 12 to 19 percent', 'Handling time down from 9.1 to 7.4 minutes', '{p2} wants to roll out the script to the partner next month', 'Decision needed by Friday'],
    constraints: ['Friday deadline', 'Two stakeholders reading the same data differently'],
    stakeholders: ['{p2}', 'The finance partner', 'The outsourced partner', 'Customers calling back'],
    ideal: [
      { text: 'Identify that both trends moved together with the shorter handling time, and that satisfaction and repeat contacts rising at once is the specific pattern to explain', indicator: 'DATADEC-E1', fact: 0 },
      { text: 'Distinguish what the dashboard shows, three correlated trends, from either stakeholder\'s causal story', indicator: 'DATADEC-E2', fact: 3 },
      { text: 'Size the decision to the evidence: pause the partner rollout rather than cancel the script, and test one hypothesis', indicator: 'DATADEC-E3', fact: 4 },
      { text: 'Name the data that would settle it, such as repeat contact rate for calls using the script versus not, or by issue type', indicator: 'DATADEC-E4', fact: 1 },
    ],
    modelAnswer: 'The dashboard shows three things moving together: satisfaction up eight points, repeat contacts up seven points, and handling time down almost two minutes. That pattern is consistent with agents closing warmly but before the issue is resolved, which would explain both numbers. It is also consistent with a change in the issue mix. I would not decide the rollout on Friday. I would tell {p2} the satisfaction gain is real but the repeat contact rise is the same size and costs more, and ask for a split of repeat contacts by agents using the script versus the control group and by issue type. I would tell finance we will have that by Thursday. If the script drives repeats, we amend it to confirm resolution before the warm close and then roll out. I would ask for two more weeks on the partner decision.',
    weak: ['Approves the rollout because satisfaction is the headline metric', 'Cancels the script because finance raised a cost concern', 'Asks for a full analytics project and gives no view on Friday'],
    media: { type: 'chart', title: 'Satisfaction and repeat contacts, last six months', alt: 'Two line chart: satisfaction rising from 71 to 79 percent; repeat contacts within seven days rising from 12 to 19 percent over the same six months', data: { points: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6'], series: [{ name: 'Satisfaction %', values: [71, 72, 74, 76, 78, 79] }, { name: 'Repeat contacts %', values: [12, 12, 14, 16, 18, 19] }] } },
    mcq: [
      { q: 'What do you decide about the partner rollout by Friday?', options: [
        { level: 'L3', text: 'Pause the rollout decision for two weeks and split repeat contacts by script use and issue type, because satisfaction and repeats rose together with shorter calls.' },
        { level: 'L2', text: 'Delay the rollout and ask the analytics team for a broader review of the support centre metrics before deciding.' },
        { level: 'L1', text: 'Approve the rollout because satisfaction is the customer metric that matters most and it has improved steadily.' },
        { level: 'L0', text: 'Stop using the script immediately because repeat contacts are costing more than the satisfaction gain is worth.' },
      ] },
      { q: 'What does the pattern of three trends most likely indicate?', options: [
        { level: 'L3', text: 'Calls may be closing pleasantly before the issue is resolved, which would raise satisfaction, cut handling time and raise repeat contacts together.' },
        { level: 'L2', text: 'The script improves the customer experience but something else is causing repeat contacts to rise.' },
        { level: 'L1', text: 'Customers are more satisfied with the new script and are calling back more often because they enjoy the experience.' },
        { level: 'L0', text: 'The month to month numbers are within normal variation and do not indicate anything about the script either way.' },
      ] },
    ],
  },
  {
    skillId: 'SK-DATADEC', tag: 'T4', difficulty: 'High', title: 'The pilot that looks like a success',
    header: 'You are a learning and development lead at {company}. A pilot programme\'s results table is in front of the leadership team tomorrow.',
    situation: 'You lead learning and development at {company}. Six months ago you piloted a new sales coaching programme with 40 volunteer account managers. The table below compares them with 160 account managers who did not take part. The pilot group\'s average deal size rose 14 percent; the others rose 3 percent. The chief revenue officer wants to roll the programme out to all 200 people at a cost of 320,000 and has asked you to confirm the results tomorrow. Your analyst, {p3}, has pointed out that the pilot group volunteered, was on average two years more experienced, and that four of the 40 closed unusually large deals that account for most of the uplift. Pipeline conversion, which the programme was designed to improve, moved by 1 point in both groups.',
    prompt: 'What would you tell the leadership team tomorrow, and what would you recommend about the rollout? Explain what in the table drives your view.',
    mcqPrompt: 'What should you recommend to the leadership team?',
    facts: ['Pilot group deal size up 14 percent against 3 percent', 'Pilot group volunteered and is two years more experienced', 'Four large deals account for most of the uplift', 'Conversion, the target metric, moved 1 point in both groups', 'Rollout costs 320,000'],
    constraints: ['Leadership meeting tomorrow', 'CRO wants confirmation', 'Pilot design was not controlled'],
    stakeholders: ['The chief revenue officer', 'The leadership team', '{p3}', '200 account managers'],
    ideal: [
      { text: 'Identify that conversion, the metric the programme targeted, did not move, and that four deals drive the headline deal size figure', indicator: 'DATADEC-E1', fact: 3 },
      { text: 'Distinguish what the table shows from what it can explain, given volunteers, experience and four outliers', indicator: 'DATADEC-E2', fact: 1 },
      { text: 'Size the recommendation to the evidence: a second controlled wave rather than either a full rollout or cancellation', indicator: 'DATADEC-E3', fact: 4 },
      { text: 'Name the check that would settle it: median deal size excluding the four outliers, and a matched comparison group', indicator: 'DATADEC-E4', fact: 2 },
    ],
    modelAnswer: 'I would tell leadership that the headline is encouraging but does not yet support a 320,000 decision. The 14 percent deal size uplift comes mostly from four deals, the pilot group volunteered and is more experienced, and conversion, which the programme was designed to lift, moved one point in both groups. What the table shows is a difference between two groups that were not comparable to begin with. I would recommend a second wave of 40, matched on experience and assigned rather than volunteered, with median deal size and conversion tracked for a quarter, at roughly a fifth of the full cost. I would show the median deal size excluding the four outliers so the room sees the size of the underlying effect. I would say plainly to the CRO that I would rather be right in three months than confident tomorrow.',
    weak: ['Confirms the results because the CRO has asked for confirmation', 'Cancels the programme because the pilot was flawed', 'Presents the 14 percent uplift without the caveats and lets leadership decide'],
    media: { type: 'table', title: 'Pilot results, six months', alt: 'Table comparing 40 pilot participants with 160 non participants on deal size change, conversion change, average experience and selection method', data: { columns: ['Measure', 'Pilot group (40)', 'Others (160)'], rows: [['Average deal size change', '+14 percent', '+3 percent'], ['Pipeline conversion change', '+1 point', '+1 point'], ['Average experience', '6.1 years', '4.0 years'], ['Selection', 'Volunteered', 'Did not volunteer'], ['Deals above 250k', '4', '3']] } },
    mcq: [
      { q: 'What do you recommend to the leadership team?', options: [
        { level: 'L3', text: 'A second matched, assigned wave of 40 with median deal size and conversion tracked, because the current uplift rests on four deals and non comparable groups.' },
        { level: 'L2', text: 'Roll out to half the account managers now and compare them with the other half over the next two quarters.' },
        { level: 'L1', text: 'Cancel the programme entirely, because the pilot design was flawed and the conversion metric did not move at all.' },
        { level: 'L0', text: 'Approve the full rollout, because a 14 percent uplift against 3 percent is a clear and significant result.' },
      ] },
      { q: 'Which figure in the table matters most for the decision?', options: [
        { level: 'L3', text: 'Conversion moved one point in both groups, because that is the metric the programme was designed to change.' },
        { level: 'L2', text: 'The pilot group\'s two extra years of average experience, because it means the two groups were never comparable to begin with.' },
        { level: 'L1', text: 'The 14 percent deal size increase, because larger deals drive revenue directly and that is what leadership cares about.' },
        { level: 'L0', text: 'The 320,000 rollout cost, because it determines whether the programme is affordable within this year\'s budget.' },
      ] },
    ],
  },
  {
    skillId: 'SK-STAKE', tag: 'T3', difficulty: 'Low', title: 'Who needs to know about the change of vendor',
    header: 'You are a facilities manager at {company}. You are switching the office catering vendor in three weeks.',
    situation: 'You are a facilities manager at {company}. After a tender you are switching the office catering vendor for 600 staff in three weeks. The new vendor is cheaper and better rated but will change the menu, move the coffee station, and stop the Friday breakfast that the sales team runs its weekly meeting around. The finance director sponsored the tender and wants it done. The head of sales does not yet know about Friday breakfast. The two catering staff employed by the old vendor have worked in the building for eight years and are liked. The works council must be informed of any change affecting staff amenities, with two weeks\' notice. Your manager has asked you for a stakeholder plan by tomorrow.',
    prompt: 'Who would you engage, in what order, and what would you say to each? Explain your reasoning.',
    mcqPrompt: 'Who should you speak to first, and why?',
    facts: ['Vendor changes in three weeks for 600 staff', 'The Friday breakfast the sales team relies on will stop', 'The works council needs two weeks\' notice', 'Two long serving catering staff are affected', 'The finance director sponsors the change'],
    constraints: ['Three weeks total, two weeks\' notice for the works council', 'Plan due tomorrow'],
    stakeholders: ['The finance director', 'The head of sales', 'The works council', 'The catering staff', '600 staff'],
    ideal: [
      { text: 'Map who is affected and what each needs before acting, including the works council notice period as a hard dependency', indicator: 'STAKE-E1', fact: 2 },
      { text: 'Tell the head of sales about Friday breakfast early, with options, rather than letting them discover it', indicator: 'STAKE-E2', fact: 1 },
      { text: 'Tailor the message: cost and ratings for finance, meeting rhythm for sales, employment for the catering staff, amenity change for the works council', indicator: 'STAKE-E3', fact: 4 },
      { text: 'Secure explicit agreement on the plan and dates from the sponsor and the works council', indicator: 'STAKE-E4', fact: 0 },
    ],
    modelAnswer: 'First I would inform the works council this week, because the two week notice is a hard constraint and the timeline fails without it. Second, the head of sales, before anyone else hears, with the Friday breakfast issue and two options: ask the new vendor to price a Friday option, or move the meeting to a coffee slot; I would rather they hear it from me with choices than from the team. Third, I would ask the old vendor how the two catering staff are affected and whether the new vendor will consider them, and say that to staff honestly. Fourth, I would confirm the plan and dates with the finance director in writing. Then an all staff note two weeks out with the menu and the coffee station change. I would list each group, what they need, the message and the date in the plan for my manager.',
    weak: ['Sends one all staff email announcing the change and considers the stakeholders informed', 'Tells the finance director everything is fine and hopes sales does not notice', 'Delays informing the works council until the vendor contract is signed'],
    mcq: [{
      q: 'Who do you speak to first, and why?', options: [
        { level: 'L3', text: 'The works council, because their two week notice is the hard dependency, then the head of sales with options on the Friday breakfast before they hear it elsewhere.' },
        { level: 'L2', text: 'The head of sales, because losing Friday breakfast is the most visible change and they are the most likely to object.' },
        { level: 'L1', text: 'The finance director, to reconfirm they want to proceed before you speak to anyone who might push back.' },
        { level: 'L0', text: 'All 600 staff, with a single announcement email, so everyone hears the same message at the same time.' },
      ] },
    ],
  },
  {
    skillId: 'SK-STAKE', tag: 'T3', difficulty: 'Medium', title: 'Bad news for the sponsor before the board',
    header: 'You are a programme manager at {company}. The sponsor presents to the board on Thursday and your programme has just lost its lead engineer.',
    situation: 'You are the programme manager for {product} at {company}. On Thursday the sponsor, {p1}, presents the programme to the board as on track for a March launch. This morning your lead engineer resigned with one month\'s notice, and your own assessment is that March is now unlikely; May is realistic. You also know that the head of engineering has been reluctant to backfill and would prefer to pull two people from another team, which that team\'s head will resist. {p1} has a strong preference for hearing about problems with a plan attached and tends to react badly to surprises in public. It is Monday. You have a weekly one to one with {p1} on Wednesday, but the board pack is due to be submitted on Tuesday afternoon.',
    prompt: 'What would you do between now and Tuesday afternoon, and what would you say to {p1}? Explain the order.',
    mcqPrompt: 'What should you do first?',
    facts: ['The sponsor presents "on track for March" on Thursday', 'The lead engineer resigned today; May is realistic', 'The board pack is due Tuesday afternoon', 'Backfill needs the head of engineering and another team\'s head', '{p1} wants problems with a plan attached'],
    constraints: ['Board pack deadline is before your Wednesday one to one', 'Public surprise must be avoided'],
    stakeholders: ['{p1}', 'The board', 'The head of engineering', 'The other team\'s head'],
    ideal: [
      { text: 'Map who needs what: the sponsor needs the news before the pack, engineering needs a backfill decision, the other team head needs to be asked not told', indicator: 'STAKE-E1', fact: 3 },
      { text: 'Bring the bad news to {p1} today, before the pack is submitted, with options rather than waiting for Wednesday', indicator: 'STAKE-E2', fact: 2 },
      { text: 'Tailor the message for {p1}: the fact, the realistic date, two options and what you need from them', indicator: 'STAKE-E3', fact: 4 },
      { text: 'Secure explicit agreement on what the board hears on Thursday and who speaks to the head of engineering', indicator: 'STAKE-E4', fact: 0 },
    ],
    modelAnswer: 'I would not wait for Wednesday. Today I would spend an hour with the head of engineering to get the realistic backfill options and their cost in time. Then I would ask {p1} for 20 minutes today or first thing Tuesday and say: the lead engineer resigned this morning; my honest assessment is May, not March; here are two options, a backfill from the other team that gets us to late April with the other team head\'s agreement, or an external hire that gets us to May. I would say what I need from {p1}: a decision on the option and agreement on what the board pack says on Tuesday. I would propose the pack says "re-planning after a key resignation, revised date by end of month" rather than "on track". I would offer to speak to the other team head myself but ask {p1} to back the request.',
    weak: ['Waits for the Wednesday one to one because that is the scheduled slot', 'Lets the pack go in as "on track" and plans to raise it after the board', 'Emails {p1} the resignation with no options and no proposed board wording'],
    mcq: [{
      q: 'It is Monday morning. What do you do first?', options: [
        { level: 'L3', text: 'Get backfill options from the head of engineering today, then brief {p1} before the pack deadline with the realistic date, two options and proposed board wording.' },
        { level: 'L2', text: 'Ask {p1} for 20 minutes today and tell them about the resignation and your view that March is unlikely.' },
        { level: 'L1', text: 'Draft a recovery plan over the next two days and present it at the Wednesday one to one with the new date.' },
        { level: 'L0', text: 'Leave the board pack as "on track", since the resignation is not yet confirmed as a delay, and raise it after Thursday.' },
      ] },
    ],
  },
  {
    skillId: 'SK-STAKE', tag: 'T1', difficulty: 'High', title: 'Three stakeholders, three different truths',
    header: 'You are an account director at {company}. Your client\'s CFO, COO and IT director each want a different outcome from the renewal.',
    situation: 'You are an account director at {company} leading the renewal of a 2 million contract for {product}. The client\'s CFO wants a 15 percent price reduction and has said so in writing. The COO, who uses the product daily, wants two new modules and is prepared to pay more. The IT director wants to consolidate vendors and has been meeting a competitor. None of the three knows exactly what the others have said to you. Your own commercial team can offer at most 5 percent on price and the modules would add 20 percent. The renewal decision sits with a steering committee of all three in three weeks, chaired by the CFO. You have a relationship with each and a call scheduled with the COO tomorrow.',
    prompt: 'How would you manage the three stakeholders over the next three weeks, and what would you say to the COO tomorrow? Explain your reasoning.',
    mcqPrompt: 'What is the best approach to the three stakeholders?',
    facts: ['The CFO wants 15 percent off in writing', 'The COO wants two modules and will pay more', 'The IT director is talking to a competitor about consolidation', 'Your limit is 5 percent off; modules add 20 percent', 'The steering committee decides in three weeks'],
    constraints: ['The three do not know each other\'s positions', 'Committee chaired by the CFO'],
    stakeholders: ['The CFO', 'The COO', 'The IT director', 'The steering committee', 'Your commercial team'],
    ideal: [
      { text: 'Map the three interests and the tension between them before the COO call, and identify that the IT director is the risk', indicator: 'STAKE-E1', fact: 2 },
      { text: 'Bring the price constraint to the CFO early with options rather than letting it surface at the committee', indicator: 'STAKE-E2', fact: 3 },
      { text: 'Tailor each conversation: value and modules for the COO, total cost of ownership for the CFO, integration and roadmap for the IT director', indicator: 'STAKE-E3', fact: 0 },
      { text: 'Work towards one proposal the three can agree together, and secure explicit alignment before the committee', indicator: 'STAKE-E4', fact: 4 },
    ],
    modelAnswer: 'I would treat this as one negotiation with three interests. Tomorrow with the COO I would explore the two modules, quantify the operational value in their terms and ask whether they would sponsor a proposal that bundles modules with a modest overall price move. I would then ask the IT director for a meeting this week on integration and roadmap, and address consolidation directly: what would a single vendor need to offer, and where does our product sit. With the CFO I would not wait for the committee: I would go early, acknowledge the 15 percent request, and offer a total cost view over three years where the bundle with 5 percent off and phased modules lowers cost per user. Two weeks out I would propose a pre-meeting with all three to align on one proposal, so the committee ratifies rather than debates.',
    weak: ['Tells each stakeholder what they want to hear and hopes it holds at the committee', 'Focuses only on the CFO because they chair the committee', 'Offers 15 percent to close the risk without authority'],
    mcq: [{
      q: 'How do you approach the next three weeks?', options: [
        { level: 'L3', text: 'Meet each stakeholder on their own interest, take the price constraint to the CFO early with a total cost option, and align all three on one proposal before the committee.' },
        { level: 'L2', text: 'Focus on the CFO as chair, offer the maximum 5 percent, and explain to the COO that modules will need to wait until next year.' },
        { level: 'L1', text: 'Use the COO call to build an internal champion and let the COO manage the CFO and IT director for you.' },
        { level: 'L0', text: 'Tell each stakeholder their request is achievable so they support the renewal, and resolve the differences at the committee.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CUST', tag: 'T1', difficulty: 'Low', title: 'The third call about the same invoice',
    header: 'You are a customer account executive at {company}. A long standing customer is calling for the third time about an invoice error.',
    situation: 'You work in customer accounts at {company}. {p1}, the finance manager at a customer of eight years, is on the phone for the third time in two weeks about the same problem: they were invoiced twice for one delivery of {product}. The first agent raised a ticket. The second agent said the credit note was "in progress." Nothing has happened, and {p1} has just been chased by their own auditor for the duplicate. {p1} is polite but tired: "I have explained this three times. I just need it fixed and I need to know when." You can see the ticket. It is sitting with billing, unassigned, because the delivery reference does not match. You cannot issue the credit note yourself, but you can reach the billing team lead directly.',
    prompt: 'What would you say to {p1} on this call? Speak as you would say it.',
    mcqPrompt: 'What is the best response to {p1}?',
    facts: ['Duplicate invoice, third call in two weeks', 'The ticket is unassigned in billing because a reference does not match', '{p1} is being chased by their auditor', 'You cannot issue the credit but can reach the billing lead'],
    constraints: ['You cannot fix it yourself', 'The customer needs a date'],
    stakeholders: ['{p1}', 'The billing team lead', 'The customer\'s auditor'],
    ideal: [
      { text: 'Restate the problem in {p1}\'s terms, a duplicate invoice their auditor is now chasing, before proposing anything', indicator: 'CUST-E1', fact: 2 },
      { text: 'Offer a concrete resolution you own: you will get the ticket assigned today and call back with a credit note date by a stated time', indicator: 'CUST-E2', fact: 3 },
      { text: 'Be honest about what you cannot do, issue the credit yourself, and what you will do instead', indicator: 'CUST-E3', fact: 3 },
      { text: 'Capture the cause, the mismatched reference and the unassigned ticket, so it does not recur', indicator: 'CUST-E4', fact: 1 },
    ],
    modelAnswer: 'I would say: "{p1}, you were invoiced twice for one delivery, you have raised it three times and now your auditor is asking. That should not have happened and I am going to own it from here." I would tell them what I can see: the ticket is sitting with billing unassigned because a delivery reference does not match. I cannot issue the credit note myself, but I can reach the billing lead directly and I will do that as soon as we hang up. I would commit: "You will hear from me by 4pm today with the date the credit note will be issued, and a written confirmation you can give your auditor." Afterwards I would ask billing why the mismatch left the ticket unassigned for two weeks and log it so it does not happen to the next customer.',
    weak: ['Apologizes and says the credit note is in progress, again', 'Explains that billing handles credit notes and offers to transfer the call', 'Promises the credit note today without checking whether billing can do it'],
    mcq: [{
      q: 'What do you say to {p1}?', options: [
        { level: 'L3', text: 'Restate the problem and its impact, say what you can see in the ticket, commit to a callback time today with a credit note date, and fix the cause afterwards.' },
        { level: 'L2', text: 'Apologize for the three calls, explain the reference mismatch, and promise to chase billing and update them as soon as you hear.' },
        { level: 'L1', text: 'Apologize, confirm the ticket is still open with billing, and offer to add a note asking them to prioritize it.' },
        { level: 'L0', text: 'Explain that credit notes are handled by billing and offer to transfer {p1} so they can speak to someone who can help.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CUST', tag: 'T1', difficulty: 'Medium', title: 'The customer who wants what the product does not do',
    header: 'You are a customer success manager at {company}. A key account is demanding a feature that is not on the roadmap.',
    situation: 'You are a customer success manager at {company}. {p2}, the operations head at a key account, has asked for the third time for {product} to export reports in a format their legacy finance system reads. Each month {p2}\'s team spends two days reformatting exports by hand. The product team has confirmed the format is not on the roadmap for at least a year, because only two customers use that system. {p2} has written that "if the export is not fixed by the renewal we will look elsewhere." The renewal is in four months and the account is worth 8 percent of your book. You know that a partner has built a middleware connector for another customer with a similar system, which would cost {p2} about 6,000 a year. You have a call with {p2} this afternoon.',
    prompt: 'What would you say to {p2} on the call? Speak as you would say it.',
    mcqPrompt: 'How should you respond to {p2}?',
    facts: ['The export format is not on the roadmap for at least a year', '{p2}\'s team spends two days a month reformatting', '{p2} has threatened to leave at renewal in four months', 'A partner connector exists for about 6,000 a year', 'The account is 8 percent of your book'],
    constraints: ['You cannot change the roadmap', 'Four months to renewal'],
    stakeholders: ['{p2} and their team', 'The product team', 'The partner', 'Your renewal book'],
    ideal: [
      { text: 'Restate the real problem, two days a month of manual reformatting and audit risk, not "the feature request"', indicator: 'CUST-E1', fact: 1 },
      { text: 'Offer a concrete resolution with a timeline you own, such as a connector trial set up within three weeks', indicator: 'CUST-E2', fact: 3 },
      { text: 'Be honest that the native export is not coming within a year, and why, rather than hinting it might', indicator: 'CUST-E3', fact: 0 },
      { text: 'Capture the need for the product team as a documented request tied to revenue so it is properly weighed', indicator: 'CUST-E4', fact: 4 },
    ],
    modelAnswer: 'I would start with the problem as {p2} experiences it: two days a month of manual reformatting so their finance system can read our reports, three requests, and a renewal decision hanging on it. Then I would be straight: the native export is not on our roadmap for at least a year, because only two customers use that system, and I would rather say that than hint otherwise. Then the resolution: a partner has built a connector for a similar system; I would propose setting up a trial in the next three weeks at our cost so their team can test it before any commitment, and if it works it costs about 6,000 a year, which is far less than two days of a team every month. I would also log the request with the product team with the revenue attached. I would confirm a follow up date.',
    weak: ['Promises to push the product team and hopes something changes before renewal', 'Quotes the roadmap policy and says nothing can be done', 'Offers a discount to compensate for the missing feature'],
    mcq: [{
      q: 'What do you say to {p2} this afternoon?', options: [
        { level: 'L3', text: 'Name the two days a month problem, say plainly that the native export is not coming this year, and propose a partner connector trial within three weeks at your cost.' },
        { level: 'L2', text: 'Explain the roadmap position honestly and tell {p2} about the partner connector as an option they could explore.' },
        { level: 'L1', text: 'Tell {p2} you will escalate the request to the product team again and ask them to hold their decision until you hear back.' },
        { level: 'L0', text: 'Offer a renewal discount to compensate for the missing feature and ask {p2} to keep working around the export for now.' },
      ] },
    ],
  },
  {
    skillId: 'SK-CUST', tag: 'T6', difficulty: 'High', title: 'The customer asking you to bend the rule',
    header: 'You lead a branch service team at {company}. Your best customer wants a delivery that would breach a safety procedure.',
    situation: 'You lead the service team at a {company} branch supplying building sites. {p3}, the site manager for your largest customer, calls at 4pm. A concrete pour is scheduled for 6am tomorrow and the reinforcing steel has not arrived from another supplier. {p3} asks you to deliver a replacement load tonight. Your driver has already done the legal maximum driving hours today, and the only alternative is a contractor vehicle without the certified crane needed to unload steel safely on that site. {p3} says: "If the pour does not happen, we lose 40,000 and I lose face with my director. You have always sorted us out. Just get it here and my lads will unload it." This customer is 20 percent of the branch\'s revenue and {p3} has been loyal for years.',
    prompt: 'What would you say to {p3}, and what would you do? Speak as you would say it.',
    mcqPrompt: 'What is the right response to {p3}?',
    facts: ['A 6am pour depends on steel that has not arrived', 'Your driver is out of legal hours', 'The alternative vehicle cannot unload steel safely on site', '{p3} offers to have their crew unload by hand', 'The customer is 20 percent of branch revenue'],
    constraints: ['Legal driving hours', 'Safe unloading requires a certified crane', 'Loyal, high value customer'],
    stakeholders: ['{p3} and their director', 'Your driver', 'The site crew who would unload', 'The branch'],
    ideal: [
      { text: 'Restate {p3}\'s problem, a 6am pour, 40,000 and their standing, before answering', indicator: 'CUST-E1', fact: 0 },
      { text: 'Offer a concrete resolution you own, such as a 5am certified delivery from a sister branch or a contractor with a crane, with a callback time', indicator: 'CUST-E2', fact: 2 },
      { text: 'Be honest that the tonight delivery cannot happen because of driving hours and unloading safety, and say so plainly', indicator: 'CUST-E3', fact: 1 },
      { text: 'Capture the cause so it does not recur, such as an early warning arrangement for pours', indicator: 'CUST-E4', fact: 0 },
    ],
    modelAnswer: 'I would say: "{p3}, I hear you: the pour is at six, 40,000 is on the line and this lands on you. I am going to try to get you steel for the pour." Then the honest part: I cannot send a load tonight. My driver is out of legal hours and the only other vehicle cannot unload steel safely on your site; a crew unloading by hand is how people get hurt, and I will not do that to your team or mine. Then the resolution: I will call our sister branch and two crane contractors now and aim for a certified delivery on site at 5am. "I will call you back by 5pm today with a yes or no and a time." If it fails, I would help {p3} find a supplier who can. Afterwards I would suggest an early warning arrangement for pours so we do not meet like this again.',
    weak: ['Sends the contractor vehicle because the customer is too important to lose', 'Says no, quotes the policy and ends the call', 'Promises a 5am delivery before checking whether anyone can do it'],
    mcq: [{
      q: 'What do you say to {p3}?', options: [
        { level: 'L3', text: 'Acknowledge the stakes, refuse the unsafe tonight delivery plainly and say why, and commit to a callback by 5pm with a certified 5am option.' },
        { level: 'L2', text: 'Explain that driving hours and unloading rules prevent a delivery tonight, apologize, and say you will see what can be done in the morning.' },
        { level: 'L1', text: 'Agree to look into it and call {p3} back, without yet saying whether a tonight delivery is possible.' },
        { level: 'L0', text: 'Send the contractor vehicle tonight and let {p3}\'s crew unload, because a 20 percent customer and a 40,000 loss justify the exception.' },
      ] },
    ],
  },
];
