// Scripted scenario seeds, group C: Problem Solving, Influencing Without Authority, Risk and Compliance Judgment, Planning and Execution.
export default [
  {
    skillId: 'SK-PROBS', tag: 'T4', difficulty: 'Low', title: 'The returns that keep coming back',
    header: 'You manage an online order fulfilment team at {company}. Returns for one product line have doubled in a month.',
    situation: 'You manage order fulfilment for {company}\'s online store. Returns of the {product} range have doubled in the last month, from 4 percent to 8 percent of orders. The most common return reason customers select is "not as described." Your team lead thinks the new packaging is being damaged in transit and wants to switch couriers, which would cost 30,000 a year more. A customer service colleague mentions that several callers said the colour looked different from the website. The product photos were refreshed five weeks ago by the marketing team. Your director has asked you to bring a recommendation to Friday\'s operations meeting. You have access to the returns data, the customer service notes and the marketing team. The team lead has already asked the courier for a quote and is expecting a decision.',
    prompt: 'What would you do before Friday, and what would you recommend? Explain how you would make sure you are fixing the right problem.',
    mcqPrompt: 'What should you do first?',
    facts: ['Returns doubled from 4 to 8 percent in a month', 'Most common reason is "not as described"', 'The team lead suspects packaging damage and proposes a 30,000 courier switch', 'Callers mention the colour differs from the website', 'Photos were refreshed five weeks ago'],
    constraints: ['Recommendation due Friday', 'Courier switch is expensive'],
    stakeholders: ['Your director', 'The team lead', 'The marketing team', 'Customers returning items'],
    ideal: [
      { text: 'State the problem as a gap, returns up from 4 to 8 percent with "not as described" as the reason, before accepting any cause', indicator: 'PROBS-E1', fact: 0 },
      { text: 'Separate symptoms from likely causes, and test the photo refresh against the timing and the colour comments', indicator: 'PROBS-E2', fact: 4 },
      { text: 'Consider more than one option, such as fixing the photos or the packaging, before recommending a courier switch', indicator: 'PROBS-E3', fact: 2 },
      { text: 'Define how success will be checked, for example returns for the range back below 5 percent within four weeks', indicator: 'PROBS-E4', fact: 0 },
    ],
    modelAnswer: 'Before Friday I would pull the returns by week and by reason and check whether the rise started when the photos changed five weeks ago. I would read the customer service notes for the range and count how many mention colour or appearance versus damage. I would also check whether returned items arrive damaged, which would support the packaging theory. If the timing and the notes point to the photos, the recommendation is to correct the product images with marketing this week, which costs almost nothing, and to hold the courier decision. I would define success as returns for the range back under 5 percent within four weeks, and report weekly. If the data points to damage instead, I would test better packaging before spending 30,000 on a courier.',
    weak: ['Approves the courier switch because the team lead is confident', 'Blames marketing for the photos without checking the data', 'Asks for more time to investigate and brings no view to Friday'],
    mcq: [{
      q: 'What do you do first?', options: [
        { level: 'L3', text: 'Plot returns by week and reason against the photo refresh date and read the service notes, to test the colour and damage explanations before choosing a fix.' },
        { level: 'L2', text: 'Check whether returned items arrive damaged, since that would confirm or rule out the packaging theory quickly.' },
        { level: 'L1', text: 'Ask marketing to restore the old product photos while you look into the packaging issue in parallel.' },
        { level: 'L0', text: 'Approve the courier switch now because returns have doubled and the team lead knows the operation best.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PROBS', tag: 'T5', difficulty: 'Medium', title: 'The onboarding that takes twice as long',
    header: 'You lead an HR operations team at {company}. New hires take 40 days to be fully set up, against a target of 20.',
    situation: 'You lead HR operations at {company}. New hires take an average of 40 days from offer acceptance to being fully set up with systems access, equipment and payroll, against a target of 20. Hiring managers complain, and two recent hires mentioned it in their first month feedback. Your team has mapped the steps: HR creates the record, IT provisions accounts, facilities orders equipment and payroll enrols the person. Each team says its own step takes under three days. The delays sit in the handoffs: IT waits for a manager approval that often sits unread; facilities waits for IT to confirm the start date; payroll cannot enrol until the bank form is returned, which candidates often send late. Your director wants the time halved within a quarter and has offered budget for a new onboarding tool.',
    prompt: 'What would you do to halve the onboarding time? Explain how you would decide where to act first and how you would know it worked.',
    mcqPrompt: 'Where should you act first?',
    facts: ['Onboarding takes 40 days against a 20 day target', 'Each step takes under three days; delays are in handoffs', 'Manager approval sits unread; facilities waits on IT; bank forms return late', 'A new tool has been offered as budget'],
    constraints: ['One quarter', 'Four teams involved'],
    stakeholders: ['Hiring managers', 'New hires', 'IT, facilities, payroll', 'Your director'],
    ideal: [
      { text: 'State the problem as the gap between 40 and 20 days located in handoffs, with evidence from the step map', indicator: 'PROBS-E1', fact: 1 },
      { text: 'Separate the symptom, slow onboarding, from causes such as sequential dependencies and unread approvals', indicator: 'PROBS-E2', fact: 2 },
      { text: 'Consider options such as parallel provisioning, removing the manager approval step, and pre-collecting the bank form, before buying a tool', indicator: 'PROBS-E3', fact: 3 },
      { text: 'Define the measure: median days to full setup, tracked per hire, with a target of 20 by quarter end', indicator: 'PROBS-E4', fact: 0 },
    ],
    modelAnswer: 'The map shows the work takes under twelve days and the waiting takes the rest, so I would start with the handoffs, not the tool. First, measure the waiting time at each handoff for the last 20 hires so we know which is biggest. My expectation is the manager approval and the sequential wait between IT and facilities. Options: let IT provision on offer acceptance with a default access set, so no manager approval is needed; trigger facilities from the HR record rather than from IT; and collect the bank form with the contract, not after. I would run these for the next ten hires and track median days to full setup. If we are under 25 days by mid quarter, we keep going and consider whether a tool adds anything; if not, we look at what is still waiting.',
    weak: ['Buys the onboarding tool first because budget is available', 'Tells each team to be faster at its own step', 'Adds a weekly onboarding status meeting to chase the handoffs'],
    mcq: [{
      q: 'Where do you act first?', options: [
        { level: 'L3', text: 'Measure waiting time at each handoff for recent hires, then remove or parallelize the biggest waits, tracking median days to setup against the 20 day target.' },
        { level: 'L2', text: 'Make IT provision a default access set on offer acceptance, since the manager approval is the delay everyone knows about.' },
        { level: 'L1', text: 'Set a three day service level for each team\'s step and report weekly on who is meeting it.' },
        { level: 'L0', text: 'Use the budget for the onboarding tool now, because a system will enforce the process across all four teams.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PROBS', tag: 'T7', difficulty: 'High', title: 'The line that stops every Thursday',
    header: 'You are a plant manager at {company}. One production line has stopped for over an hour on four consecutive Thursdays.',
    situation: 'You manage a plant at {company} with three production lines. Line 2 has stopped for 60 to 90 minutes on each of the last four Thursdays, costing about 12,000 per stop. The maintenance lead says a worn drive belt was replaced after the second stop and the problem should have gone away. The shift supervisor believes the Thursday night crew is running the line too fast to make up for a slow start. The quality manager notes that Thursday is when a different grade of raw material is used, delivered on Wednesdays by a new supplier. The three explanations are all plausible and each owner is sure of their own. Your operations director has told you a fifth stop will trigger a review of the plant\'s bonus. Thursday is in three days and you have the stop logs, the speed data and the material batch records.',
    prompt: 'What would you do in the next three days? Explain how you would find the cause and what you would do if Thursday arrives before you are sure.',
    mcqPrompt: 'What is the right approach in the next three days?',
    facts: ['Four Thursday stops of 60 to 90 minutes, about 12,000 each', 'A belt was replaced after stop two; stops continued', 'Supervisor suspects overspeed by the night crew', 'A different material grade from a new supplier is used on Thursdays', 'A fifth stop triggers a bonus review'],
    constraints: ['Three days', 'Three confident owners with different theories'],
    stakeholders: ['The maintenance lead', 'The shift supervisor', 'The quality manager', 'The operations director', 'The night crew'],
    ideal: [
      { text: 'State the problem precisely, stops on Thursdays only, and rule out the belt since stops continued after it was replaced', indicator: 'PROBS-E1', fact: 1 },
      { text: 'Separate the remaining causes and test them against the data: speed logs by shift and day, and material batch versus stop times', indicator: 'PROBS-E2', fact: 3 },
      { text: 'Consider options and choose a plan that covers the uncertainty, such as running Thursday at standard speed with the old material grade as a controlled test', indicator: 'PROBS-E3', fact: 2 },
      { text: 'Define how success will be checked: no stop this Thursday and a clear read on which variable changed', indicator: 'PROBS-E4', fact: 4 },
    ],
    modelAnswer: 'The belt theory is weakened because two stops followed the replacement, so I would set it aside. The stops are Thursday specific, and two things are also Thursday specific: the material grade and, possibly, the crew\'s speed. Over the next two days I would compare line speed on Thursday nights against other nights from the logs, and match stop times to material batches. If speed is normal and stops coincide with the new supplier\'s batches, the material is the likely cause. For this Thursday I would run a controlled test: standard speed enforced and the previous supplier\'s grade if any remains, changing one variable at a time where I can. I would tell the director the plan, the cost of the test and that a stop under those conditions tells us something too. Success is no stop and a clear read on the variable.',
    weak: ['Orders the night crew to slow down because the supervisor is most senior', 'Replaces more parts because maintenance had a plausible theory', 'Waits for a fifth stop to get more data'],
    mcq: [{
      q: 'What do you do in the next three days?', options: [
        { level: 'L3', text: 'Set aside the belt theory, compare Thursday speed and material batches against the stop logs, and run a controlled Thursday changing one variable with the director informed.' },
        { level: 'L2', text: 'Ask maintenance, the supervisor and quality to each present their evidence on Wednesday and decide on the most convincing case.' },
        { level: 'L1', text: 'Instruct the night crew to run at standard speed on Thursday and switch back to the old supplier at the same time to be safe.' },
        { level: 'L0', text: 'Schedule a full maintenance overhaul of Line 2 on Wednesday night so that every mechanical cause is eliminated before Thursday.' },
      ] },
    ],
  },
  {
    skillId: 'SK-INFLU', tag: 'T3', difficulty: 'Low', title: 'Getting the data team to move your request up',
    header: 'You are a marketing analyst at {company}. You need a data extract from a team that does not report to you and has a six week queue.',
    situation: 'You are a marketing analyst at {company}. Your campaign launch in three weeks needs a customer segment extract from the central data team. Their queue is six weeks and {p1}, the data team lead, has replied: "Everything in the queue is urgent for someone. You are in the queue." {p1}\'s team is measured on the number of requests closed per month and on data quality incidents, and they were criticized last quarter for a segment that went out with errors. You have no authority over {p1} and your own manager has said "sort it out yourself." You know that your segment definition is simple, reuses a table {p1}\'s team already maintains, and that the campaign will be reported to the leadership team {p1} presents to.',
    prompt: 'What would you say to {p1} to get the extract in time? Speak as you would write or say it.',
    mcqPrompt: 'Which approach is most likely to work with {p1}?',
    facts: ['Launch in three weeks; queue is six weeks', '{p1} is measured on requests closed and data quality incidents', 'The team was criticized for a segment with errors last quarter', 'Your segment reuses a table they already maintain', 'The campaign will be reported to leadership'],
    constraints: ['No authority over {p1}', 'Your manager will not escalate for you'],
    stakeholders: ['{p1} and the data team', 'The campaign', 'The leadership team'],
    ideal: [
      { text: 'Frame the ask in {p1}\'s terms: a quick close that reuses their table and carries low quality risk', indicator: 'INFLU-E1', fact: 3 },
      { text: 'Use concrete evidence, such as the segment definition and the specific table, rather than asserting urgency', indicator: 'INFLU-E2', fact: 3 },
      { text: 'Ask for a specific, bounded commitment, such as one hour of one analyst by a stated date', indicator: 'INFLU-E3', fact: 0 },
      { text: 'Address the stated objection, "everything is urgent", directly rather than repeating the request', indicator: 'INFLU-E4', fact: 1 },
    ],
    modelAnswer: 'I would go to {p1} with a different ask. "You said everything in the queue is urgent, and I take that. So I am not asking to jump the queue on urgency. This extract is a filter on the customer table your team already maintains; here is the definition on one page. I think it is under an hour for one of your analysts and there is no new logic, so the quality risk is low. Could someone do it by the 12th? I will validate the counts myself the same day and send you the sign off, so it closes as a completed request with no incident. When the campaign results go to leadership I will name the data team\'s support." A specific, small, safe request is easier to say yes to than a plea.',
    weak: ['Escalates to {p1}\'s manager to force the request through', 'Repeats that the campaign is very important and the deadline is fixed', 'Builds the extract yourself from an unofficial copy of the table'],
    mcq: [{
      q: 'Which message to {p1} is most likely to get the extract in time?', options: [
        { level: 'L3', text: 'Accept the queue logic, show the extract is a one hour filter on a table they maintain with low quality risk, ask for a specific date and offer to validate and credit the team.' },
        { level: 'L2', text: 'Explain the campaign timeline and the leadership visibility, and ask whether there is any flexibility for a small request.' },
        { level: 'L1', text: 'Ask again, stressing that the launch date cannot move and that marketing is counting on the data team.' },
        { level: 'L0', text: 'Copy {p1}\'s manager on a request that the extract be prioritized given the campaign\'s importance to the business.' },
      ] },
    ],
  },
  {
    skillId: 'SK-INFLU', tag: 'T3', difficulty: 'Medium', title: 'The peer who will not adopt the shared process',
    header: 'You lead the quality function at {company}. A peer plant manager refuses to adopt the incident reporting process your other plants use.',
    situation: 'You lead the quality function across four plants at {company}. Three plants have adopted a shared incident reporting process that has cut repeat incidents by a third. {p2}, the manager of the fourth plant, has declined twice, saying "my plant has the best safety record in the group and my people do not need more forms." {p2} is right about the record. {p2} reports to the operations director, not to you, and the director has said they will not mandate it. Next month the group\'s customer audit will check for consistent incident reporting across all sites, and a gap at {p2}\'s plant could cost the group a preferred supplier status worth a great deal to everyone, including {p2}. You have asked {p2} for 30 minutes and they have agreed.',
    prompt: 'What would you say to {p2} in those 30 minutes? Speak as you would say it.',
    mcqPrompt: 'What is the most effective approach with {p2}?',
    facts: ['Three plants cut repeat incidents by a third with the shared process', '{p2} has declined twice and has the best safety record', 'The director will not mandate adoption', 'A customer audit next month checks consistent reporting across sites', 'Preferred supplier status is at stake for all plants'],
    constraints: ['No authority over {p2}', '30 minutes', 'Audit in one month'],
    stakeholders: ['{p2} and their plant', 'The operations director', 'The customer auditors', 'The other three plants'],
    ideal: [
      { text: 'Frame the ask in {p2}\'s interests: protecting the plant\'s record and the group status their plant depends on, not compliance with your process', indicator: 'INFLU-E1', fact: 4 },
      { text: 'Use evidence: the one third reduction at three plants and the audit requirement, with specifics', indicator: 'INFLU-E2', fact: 0 },
      { text: 'Ask for a bounded commitment, such as a four week trial on one shift before the audit', indicator: 'INFLU-E3', fact: 3 },
      { text: 'Address the objection, "more forms for a plant that does not need them", directly, for example by showing the form takes two minutes and exists to prove what they already do', indicator: 'INFLU-E4', fact: 1 },
    ],
    modelAnswer: 'I would start by agreeing: {p2}\'s plant has the best record in the group, and I would say I want that record to count. Then the problem: next month\'s customer audit checks consistent incident reporting across all four sites, and a gap at one site puts preferred supplier status at risk for the group, including their plant\'s volume. On the objection, I would show the form: two minutes per incident, and its purpose here is not to fix their plant but to prove to an auditor what their people already do. Evidence from the other plants: a third fewer repeat incidents. The ask: a four week trial on one shift, starting next week, with my team doing the setup, and {p2} decides after the audit whether to keep it. I would ask them to name the shift.',
    weak: ['Asks the operations director to mandate it despite what they said', 'Tells {p2} the other three plants are doing it and they should too', 'Presents the process\'s benefits in general without addressing the record or the audit'],
    mcq: [{
      q: 'How do you use the 30 minutes with {p2}?', options: [
        { level: 'L3', text: 'Acknowledge the record, link the audit risk to their plant\'s interests, answer the forms objection with the two minute form, and ask for a four week trial on one shift.' },
        { level: 'L2', text: 'Explain the audit requirement and the results at the other three plants, and ask {p2} to adopt the process before the audit.' },
        { level: 'L1', text: 'Present the benefits of the process and the group\'s desire for consistency, and ask {p2} to reconsider.' },
        { level: 'L0', text: 'Tell {p2} that if they do not adopt it you will raise it with the director again and note the gap in the audit preparation report.' },
      ] },
    ],
  },
  {
    skillId: 'SK-INFLU', tag: 'T3', difficulty: 'High', title: 'Turning the finance partner from blocker to sponsor',
    header: 'You are a product lead at {company}. Your finance business partner has vetoed your pricing experiment for the second time.',
    situation: 'You are a product lead for {product} at {company}. You want to run a pricing experiment: a 10 percent lower entry price for new customers in one region for a quarter, to test whether volume gains offset margin. {p3}, the finance business partner for your division, has blocked it twice, saying "we do not give away margin to run experiments, and once a price goes down it never comes back." {p3} is respected by the CFO and was burned two years ago when a discount became permanent. Your divisional head supports the idea in principle but will not override finance. Two competitors have moved their entry price down this year and your new customer acquisition in that region has fallen 18 percent. You have a 45 minute meeting with {p3} on Thursday and want to leave with an agreement to run something.',
    prompt: 'What would you say to {p3} on Thursday? Speak as you would say it, including how you would handle the objection about prices never coming back.',
    mcqPrompt: 'How do you approach the Thursday meeting with {p3}?',
    facts: ['{p3} has blocked the experiment twice on margin and permanence grounds', '{p3} was burned by a discount that became permanent', 'Competitors have cut entry prices; acquisition is down 18 percent', 'Your divisional head will not override finance', '45 minutes on Thursday'],
    constraints: ['No authority over {p3}', 'Finance credibility with the CFO', 'One meeting'],
    stakeholders: ['{p3}', 'The CFO', 'The divisional head', 'New customers in the region'],
    ideal: [
      { text: 'Frame the proposal in {p3}\'s terms: protecting margin against an 18 percent acquisition decline and controlling the risk they have lived through', indicator: 'INFLU-E1', fact: 2 },
      { text: 'Use evidence: competitor moves, the acquisition drop and a modelled margin exposure with a cap', indicator: 'INFLU-E2', fact: 2 },
      { text: 'Ask for a bounded commitment: one region, one quarter, a hard end date and a margin ceiling, with {p3} as co-owner of the readout', indicator: 'INFLU-E3', fact: 0 },
      { text: 'Address the permanence objection directly with a mechanism, such as a time boxed promotional code rather than a list price change', indicator: 'INFLU-E4', fact: 1 },
    ],
    modelAnswer: 'I would open with what {p3} is protecting: margin. Then the fact they may not have connected: new customer acquisition in the region is down 18 percent since two competitors cut entry prices, so we are already losing margin in the form of customers we do not win. I would address the permanence concern first, because I know it comes from experience: the experiment would run as a time boxed promotional code that expires on a fixed date, not a list price change, so the price mechanically comes back. I would show the modelled downside capped at a number and offer a kill switch if margin falls below a floor. The ask: one region, one quarter, {p3} co-owns the readout to the CFO. If it fails, finance was right and we have the evidence; if it works, {p3} sponsored it.',
    weak: ['Goes over {p3}\'s head to the CFO with the competitor data', 'Repeats the strategic case for the experiment louder', 'Drops the experiment because finance has said no twice'],
    mcq: [{
      q: 'How do you approach Thursday?', options: [
        { level: 'L3', text: 'Frame it as protecting margin against the acquisition drop, answer the permanence objection with an expiring code and a margin floor, and ask for one region for one quarter with {p3} co-owning the readout.' },
        { level: 'L2', text: 'Present the competitor moves and the 18 percent decline, and propose the experiment again with a smaller discount of 5 percent.' },
        { level: 'L1', text: 'Ask {p3} what evidence would change their mind and offer to come back with it in a month.' },
        { level: 'L0', text: 'Bring the divisional head to the meeting so that finance feels the weight of the business behind the experiment.' },
      ] },
    ],
  },
  {
    skillId: 'SK-RISK', tag: 'T6', difficulty: 'Low', title: 'The gift at the end of the quarter',
    header: 'You are a sales manager at {company}. A customer\'s procurement lead has sent your team member an expensive gift.',
    situation: 'You are a sales manager at {company}. It is the last week of the quarter. {p1}, one of your account executives, tells you that the procurement lead at a customer they are about to sign a 400,000 renewal with has sent them a watch worth roughly 1,200 "as a thank you for the partnership." {p1} is unsure whether to keep it and does not want to offend the customer three days before signature. {company}\'s gifts policy sets a 100 limit on gifts from customers, requires anything above it to be declared and returned or donated, and has a mandatory reporting line to compliance. The renewal is 15 percent of your quarter. The procurement lead is known to be sensitive about being treated as a supplier risk.',
    prompt: 'What would you tell {p1} to do, and what would you do yourself? Explain your reasoning.',
    mcqPrompt: 'What should you tell {p1} to do?',
    facts: ['A 1,200 watch was gifted by a customer three days before a 400,000 signature', 'Policy caps gifts at 100 and requires declaration and return or donation', 'Compliance reporting is mandatory', 'The renewal is 15 percent of the quarter'],
    constraints: ['Three days to signature', 'A sensitive customer contact'],
    stakeholders: ['{p1}', 'The customer\'s procurement lead', 'Compliance', 'Your quarter'],
    ideal: [
      { text: 'Name the specific policy the gift touches, the 100 limit and mandatory reporting, and that a gift before signature is also a perception risk', indicator: 'RISK-E1', fact: 1 },
      { text: 'Pause any thought of keeping it until it is declared, regardless of the quarter timing', indicator: 'RISK-E2', fact: 3 },
      { text: 'Report it to compliance through the defined channel today and document it', indicator: 'RISK-E3', fact: 2 },
      { text: 'Find a compliant route that protects the relationship, such as a gracious return note that cites company policy, so the renewal proceeds', indicator: 'RISK-E4', fact: 0 },
    ],
    modelAnswer: 'I would tell {p1} the gift cannot be kept: it is twelve times the policy limit, and a valuable gift from procurement three days before a signature is exactly the situation the rule exists for, whatever the intent. Step one, today: {p1} declares it to compliance through the gifts register and I confirm I have been informed. Step two: we return it with a warm note that thanks the procurement lead and explains that company policy does not allow us to accept gifts over a nominal value, with a line that we would be glad to mark the partnership with a team lunch after signature. I would offer to make the call myself if {p1} is worried. The renewal proceeds on its merits. I would document the decision in the register.',
    weak: ['Tells {p1} to keep it quietly until after signature and then declare it', 'Tells {p1} to return it without declaring it to avoid a compliance record', 'Refuses the gift bluntly in a way that damages the relationship'],
    mcq: [{
      q: 'What do you tell {p1} to do?', options: [
        { level: 'L3', text: 'Declare the gift to compliance today, return it with a gracious note citing company policy, and offer a team lunch after signature to mark the partnership.' },
        { level: 'L2', text: 'Return the watch to the procurement lead with thanks and an explanation of the policy, and mention it to compliance if they ask.' },
        { level: 'L1', text: 'Hold the watch unopened until after signature, then declare and return it so the deal is not put at risk.' },
        { level: 'L0', text: 'Keep it, since it was given as thanks for the partnership and declaring it might offend a sensitive customer contact.' },
      ] },
    ],
  },
  {
    skillId: 'SK-RISK', tag: 'T6', difficulty: 'Medium', title: 'The spreadsheet of customer data on a personal drive',
    header: 'You are a team lead in a service centre at {company}. You discover a colleague has been emailing customer lists to a personal account.',
    situation: 'You lead a team of ten in a service centre at {company}. While covering for {p2}, a well liked team member on leave, you find that {p2} has been emailing spreadsheets of customer names, phone numbers and account balances to a personal email address every Friday for months, apparently to work on call lists at home over the weekend. {p2} is your most productive agent and has never had a conduct issue. Company policy prohibits sending customer data outside the corporate environment; a breach must be reported to the data protection officer within 24 hours of discovery. Your manager is travelling. You believe {p2}\'s intent was to work harder, not to misuse the data, and you are worried a report could end their career.',
    prompt: 'What would you do in the next 24 hours, and what would you say to {p2} when they return? Explain your reasoning.',
    mcqPrompt: 'What should you do in the next 24 hours?',
    facts: ['Customer names, numbers and balances were sent to a personal email weekly for months', 'Policy prohibits it and requires a report to the data protection officer within 24 hours', '{p2} is productive with no conduct history and likely well intentioned', 'Your manager is travelling'],
    constraints: ['24 hour reporting window', 'A colleague\'s career', 'Manager unavailable'],
    stakeholders: ['{p2}', 'The data protection officer', 'Customers whose data left the environment', 'Your manager'],
    ideal: [
      { text: 'Name the specific risk: personal data outside the corporate environment, a reportable breach regardless of intent', indicator: 'RISK-E1', fact: 0 },
      { text: 'Do not delay or clean up before reporting, even though {p2}\'s intent seems good', indicator: 'RISK-E2', fact: 2 },
      { text: 'Report to the data protection officer within 24 hours through the defined channel and inform your manager', indicator: 'RISK-E3', fact: 1 },
      { text: 'Find the compliant route to the legitimate need: a secure way for agents to prepare call lists remotely', indicator: 'RISK-E4', fact: 2 },
    ],
    modelAnswer: 'Intent does not change what this is: months of customer personal and financial data leaving the corporate environment, which is a reportable breach. Within 24 hours I would report it to the data protection officer with the facts I have, dates, data types and volume, and I would message my manager so they hear it from me. I would not delete anything or contact {p2} on leave to fix it first. I would say to the DPO what I know about intent, because that is relevant to how it is handled, but the report itself is not optional. When {p2} returns I would meet them privately, explain what I found and what I had to do, and let them explain. Separately, I would raise that agents need a secure way to prepare call lists remotely, because the behavior shows a gap in tools.',
    weak: ['Waits for {p2} to return and asks them to delete the emails before deciding', 'Deletes the emails yourself to protect {p2} and says nothing', 'Reports {p2} for misconduct without noting intent or the tooling gap'],
    mcq: [{
      q: 'What do you do in the next 24 hours?', options: [
        { level: 'L3', text: 'Report to the data protection officer with the facts and the likely intent, inform your manager, do not delete anything, and note the need for secure remote call list access.' },
        { level: 'L2', text: 'Report to the data protection officer within 24 hours as the policy requires and wait for their guidance before doing anything else.' },
        { level: 'L1', text: 'Wait for {p2} to return from leave so you can understand their intent before deciding whether a report is needed.' },
        { level: 'L0', text: 'Ask IT to delete the emails from the corporate side and speak to {p2} privately on their return, keeping it within the team.' },
      ] },
    ],
  },
  {
    skillId: 'SK-RISK', tag: 'T6', difficulty: 'High', title: 'The approval that was signed after the fact',
    header: 'You are a project manager at {company}. You learn that a change was deployed before its approval was signed, and the approval was backdated.',
    situation: 'You manage a payments platform project at {company}. During a routine review you find that a configuration change to the payments limit was deployed to production on the 14th, but the change approval from the risk committee is dated the 12th and was in fact signed on the 16th; the approver, {p3}, is a senior manager who confirms they "signed it when they got to it and put the meeting date on it." The change itself was correct and has caused no incident. Your platform is regulated and the regulator\'s audit is in six weeks; backdated approvals are a serious finding. {p3} says raising it will "create a problem where there is not one" and that the team was under pressure to deploy. Your programme director reports to {p3}\'s peer.',
    prompt: 'What would you do, and what would you say to {p3}? Explain how you would balance the finding against the pressure and the relationship.',
    mcqPrompt: 'What is the right course of action?',
    facts: ['A production change was deployed before approval', 'The approval was signed after deployment and dated as if before', '{p3} confirms it and wants it left alone', 'The regulator audits in six weeks', 'No incident resulted from the change'],
    constraints: ['Regulated platform', 'Senior approver resists', 'Six weeks to audit'],
    stakeholders: ['{p3}', 'The risk committee', 'The regulator', 'Your programme director', 'The team under deployment pressure'],
    ideal: [
      { text: 'Name the specific risk: a backdated approval on a regulated platform is a control failure regardless of the change\'s outcome', indicator: 'RISK-E1', fact: 1 },
      { text: 'Do not accept "leave it alone" and do not quietly correct the date', indicator: 'RISK-E2', fact: 2 },
      { text: 'Escalate through the defined channel, for example the risk committee or compliance, and document what was found and when', indicator: 'RISK-E3', fact: 3 },
      { text: 'Find the compliant route to the legitimate need: an emergency change procedure so pressure does not produce backdating again', indicator: 'RISK-E4', fact: 4 },
    ],
    modelAnswer: 'I would tell {p3} directly that I understand the change was right and the team was under pressure, and that I still have to raise it: a backdated approval on a regulated platform is a control failure, and if the regulator finds it in six weeks rather than hearing it from us, the finding is far worse. I would say I would rather we self-report it together than have it found. I would then log it with compliance and the risk committee as a control exception with the true dates, the reason, and the fact that no incident occurred, and inform my programme director. I would propose an emergency change process with a same day retrospective approval so the team has a legitimate route when speed is needed. I would not correct the date myself or leave it.',
    weak: ['Agrees with {p3} because the change caused no harm', 'Corrects the approval date to the real date and files it quietly', 'Reports {p3} to the regulator directly without using internal channels'],
    mcq: [{
      q: 'What do you do?', options: [
        { level: 'L3', text: 'Tell {p3} you must raise it and why, log it with compliance and the risk committee with true dates and context, inform your director, and propose an emergency change route.' },
        { level: 'L2', text: 'Log the control exception with compliance with the true dates and let them decide how to handle {p3} and the audit.' },
        { level: 'L1', text: 'Ask {p3} to re-sign the approval with the correct date and add a note explaining the delay, so the record is at least accurate.' },
        { level: 'L0', text: 'Leave it, since the change was correct, caused no incident, and {p3} is senior and has asked you not to create a problem.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PLAN', tag: 'T7', difficulty: 'Low', title: 'Six weeks to the customer event',
    header: 'You are an events coordinator at {company}. You have just been given a customer event to run in six weeks.',
    situation: 'You coordinate events at {company}. Your director has just asked you to run a half day customer event for 80 guests in six weeks, to launch {product}. There is a budget of 25,000. You have a venue shortlist, a product team that needs to prepare a demo, a marketing team that produces invitations and a sales team that owns the guest list. From past events you know that guest lists arrive late, that the venue needs a signed contract four weeks out to hold the date, and that demos have failed when the product team was not given a rehearsal in the room. Your director wants a plan on their desk in two days showing what happens when and who owns each part.',
    prompt: 'Write the plan you would give your director: the sequence, owners, key risks and checkpoints. Explain the reasoning behind the order.',
    mcqPrompt: 'What is the most important thing to get right in the first week?',
    facts: ['Six weeks, 80 guests, 25,000 budget', 'Venue needs a signed contract four weeks out', 'Guest lists historically arrive late', 'Demos fail without an in room rehearsal', 'Plan due in two days'],
    constraints: ['Fixed date and budget', 'Four teams to coordinate'],
    stakeholders: ['Your director', 'Sales, marketing and product teams', 'The venue', '80 guests'],
    ideal: [
      { text: 'Break the goal into sequenced steps with owners and dates, from venue contract to rehearsal', indicator: 'PLAN-E1', fact: 0 },
      { text: 'Identify the critical path: the venue contract in week two and the guest list feeding invitations, with the risks that threaten them', indicator: 'PLAN-E2', fact: 1 },
      { text: 'Build in decision checkpoints, such as a go or no go on guest numbers at week three, not just status updates', indicator: 'PLAN-E3', fact: 2 },
      { text: 'Plan the trade off in advance: if the guest list is late, what moves, scope, time or resource', indicator: 'PLAN-E4', fact: 2 },
    ],
    modelAnswer: 'Week one: confirm the venue from the shortlist and get the contract signed by the end of week two, because that is the hard dependency; I own it. Sales delivers the guest list by the end of week two; I would tell the sales lead now that the list historically arrives late and ask for a draft in week one so invitations can go out in week three, owned by marketing. Product owns the demo with a script by week four and an in room rehearsal in week five, which I would book with the venue now. Checkpoints: week three, go or no go on guest numbers, with a decision to widen the invite list if under 60 acceptances; week five, rehearsal outcome, with a fallback to a recorded demo if it fails. Budget tracked weekly against the 25,000. Risks and owners listed on one page.',
    weak: ['Lists all the tasks without dates or owners', 'Waits for the guest list before booking anything', 'Plans status meetings every week but no decision points'],
    mcq: [{
      q: 'What matters most in the first week?', options: [
        { level: 'L3', text: 'Lock the venue contract path and ask sales for a draft guest list early, because those two items drive everything downstream and both have failed before.' },
        { level: 'L2', text: 'Confirm the venue and sign the contract, since the venue will not hold the date beyond four weeks out.' },
        { level: 'L1', text: 'Set up a weekly status meeting with all four teams so everyone stays aligned on progress.' },
        { level: 'L0', text: 'Design the invitations and the event branding, because they take the longest to get right and set the tone.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PLAN', tag: 'T3', difficulty: 'Medium', title: 'The migration that has slipped two weeks',
    header: 'You lead a systems migration at {company}. You are two weeks behind with eight weeks to a fixed cutover date.',
    situation: 'You lead the migration of {company}\'s customer records to a new platform. Cutover is fixed for the last weekend of the quarter, eight weeks away, because the old platform\'s contract ends. Data cleansing, which the plan gave four weeks, has taken six and is not finished: 12 percent of records still fail validation. Testing was due to start this week. The vendor has offered two extra engineers at 40,000. The business sponsor has asked whether the date is at risk and what you propose. Options on the table include migrating clean records first and the failing 12 percent later by a manual process, extending cleansing and compressing testing, or adding the vendor engineers. Your test lead is clear that testing cannot be compressed below three weeks without real risk.',
    prompt: 'What would you propose to the sponsor, and how would you re-plan the eight weeks? Explain the trade offs you are making.',
    mcqPrompt: 'What is the best re-plan?',
    facts: ['Cutover is fixed in eight weeks by contract end', 'Cleansing has overrun by two weeks; 12 percent of records fail', 'Testing needs three weeks minimum', 'Vendor engineers cost 40,000', 'Option to migrate clean records first exists'],
    constraints: ['Fixed date', 'Testing cannot compress below three weeks', 'Budget for vendor help is available but not free'],
    stakeholders: ['The business sponsor', 'The test lead', 'The vendor', 'Customers whose records fail'],
    ideal: [
      { text: 'Re-sequence with owners and dates: start testing on the 88 percent now while cleansing continues on the 12 percent in parallel', indicator: 'PLAN-E1', fact: 1 },
      { text: 'Identify the critical path, testing at three weeks plus cutover, and the risk that failing records grow or block cutover', indicator: 'PLAN-E2', fact: 2 },
      { text: 'Set decision checkpoints: at week four, decide whether the 12 percent migrates or goes manual, based on a named threshold', indicator: 'PLAN-E3', fact: 4 },
      { text: 'Make the trade off explicit to the sponsor: scope split and cost of engineers versus date, not a silent absorption', indicator: 'PLAN-E4', fact: 3 },
    ],
    modelAnswer: 'I would tell the sponsor the date holds if we change scope and sequence. Testing starts this week on the 88 percent of records that validate, protecting the three weeks the test lead needs. Cleansing continues in parallel on the 12 percent with the two vendor engineers, at 40,000, because that is cheaper than a missed cutover with no old platform. Checkpoint at week four: if failing records are below 3 percent they join the main migration; if not, they migrate through a manual process in the two weeks after cutover with a customer communication plan. I would name the risk that the failing records include high value accounts and ask the business to prioritize which are cleansed first. This is a trade of scope and money to hold the date, and I would say that plainly.',
    weak: ['Compresses testing to two weeks to catch up', 'Asks for the cutover date to move without checking the contract', 'Adds the vendor engineers and keeps the original plan otherwise'],
    mcq: [{
      q: 'What do you propose?', options: [
        { level: 'L3', text: 'Start testing on the clean 88 percent now, cleanse the rest in parallel with vendor help, set a week four threshold to decide migrate or manual, and tell the sponsor the scope and cost trade.' },
        { level: 'L2', text: 'Add the vendor engineers to finish cleansing in two weeks, then run three weeks of testing on the full data set before cutover.' },
        { level: 'L1', text: 'Extend cleansing by two weeks and compress testing to two weeks so that the full data set migrates on the fixed date.' },
        { level: 'L0', text: 'Ask the sponsor to negotiate a two month extension on the old platform contract so the original plan can complete.' },
      ] },
    ],
  },
  {
    skillId: 'SK-PLAN', tag: 'T5', difficulty: 'High', title: 'Three plans, one team, a merger announced',
    header: 'You are a head of operations at {company}. A merger announcement has just changed the assumptions under every plan your team is running.',
    situation: 'You are head of operations at {company}. This morning the company announced a merger with a competitor, to complete in six months. Your team of 30 is running three plans: a warehouse consolidation due in four months that assumed the current network; a new ordering system going live in ten weeks; and a hiring plan for 12 roles, four already offered. The integration office has said it will take three months to issue guidance and that "business as usual continues." Your team is unsettled and two managers have asked whether to stop work. The warehouse lease decision has a penalty deadline in three weeks. You have a leadership meeting tomorrow where you are expected to say what continues, what pauses and what changes.',
    prompt: 'What would you say tomorrow about each of the three plans, and how would you re-plan the next three months? Explain how you decided.',
    mcqPrompt: 'What is the right approach to the three plans?',
    facts: ['Merger completes in six months; guidance in three months', 'Warehouse consolidation assumed the current network, lease penalty in three weeks', 'Ordering system goes live in ten weeks', 'Four of 12 hires already offered', 'Team is unsettled'],
    constraints: ['No integration guidance for three months', 'A lease decision in three weeks'],
    stakeholders: ['Your team and its managers', 'The leadership team', 'The integration office', 'Offered candidates'],
    ideal: [
      { text: 'Sequence decisions by their deadlines and reversibility: the lease in three weeks first, the system on its own merits, hiring split by offered and not', indicator: 'PLAN-E1', fact: 1 },
      { text: 'Identify the critical path and risks: the lease penalty and the network assumption, and what happens if guidance changes the network', indicator: 'PLAN-E2', fact: 1 },
      { text: 'Set decision checkpoints tied to the integration timeline, such as a lease decision gate in two weeks with the integration office consulted', indicator: 'PLAN-E3', fact: 0 },
      { text: 'Make the trade offs explicit: continue, pause or change per plan, with what is being traded and who decides', indicator: 'PLAN-E4', fact: 4 },
    ],
    modelAnswer: 'Tomorrow I would give a decision on each plan. The ordering system continues: it is ten weeks out, adds value regardless of network, and pausing would waste the work; I would ask the integration office to confirm no conflict. Hiring: the four offered roles are honoured, because withdrawing damages us; the other eight pause until guidance, with the reason given to the team. The warehouse consolidation is the hard one: the network assumption may change, and the lease penalty is in three weeks. I would ask the integration office for an exception decision on the lease within two weeks, and set a gate: if no answer, we pay to extend the option rather than commit, trading money for reversibility. To the team, I would say which plans continue and why, and hold a fortnightly re-plan until guidance lands.',
    weak: ['Pauses everything until the integration office issues guidance', 'Continues everything unchanged because "business as usual" was stated', 'Commits to the warehouse lease to avoid the penalty without checking the network assumption'],
    mcq: [{
      q: 'What do you say about the three plans tomorrow?', options: [
        { level: 'L3', text: 'System continues, offered hires honoured and the rest paused, and a two week gate on the lease with the integration office, trading money for reversibility if no answer.' },
        { level: 'L2', text: 'System and hiring continue as planned; the warehouse consolidation pauses until the integration office gives guidance.' },
        { level: 'L1', text: 'All three plans continue as they are, because the integration office has said business as usual continues.' },
        { level: 'L0', text: 'All three plans pause until guidance arrives in three months, and the team focuses on day to day operations.' },
      ] },
    ],
  },
];
