// Scripted scenario seeds, group A: Coaching, Delegation, Giving Feedback, Difficult Conversations.
// Placeholders: {company} {product} {p1} {p2} {p3}. Filled by the generator from author terminology and balanced name lists.
export default [
  {
    skillId: 'SK-COACH', tag: 'T2', difficulty: 'Medium', title: 'The stalled first project',
    header: 'You lead a six person analytics team at {company}. {p1}, eight months in, owns their first end to end project.',
    situation: 'You lead a six person analytics team at {company}. {p1} joined eight months ago and is running their first end to end project: a churn dashboard the sales director asked for. The dashboard was due last Friday. In this morning\'s stand up {p1} says it is "nearly there" for the third week running. You have seen the working file. The data model is sound, but {p1} keeps adding filters the director never asked for and has not shown anyone a draft. Two other analysts have quietly told you they are waiting on {p1} for a shared table. The sales director has emailed you directly asking when they can expect it. You have a 30 minute one to one with {p1} in ten minutes. {p1} is capable and cares a lot about getting things right, and you know a blunt push will make them add more checks, not fewer.',
    prompt: 'What would you say to {p1} in this one to one? Speak as you would in the room.',
    mcqPrompt: 'Which opening to the one to one best helps {p1} move the project forward?',
    facts: ['The dashboard is a week late and has slipped three weeks running', 'The data model is sound; scope keeps growing with filters nobody requested', 'No draft has been shown to the sales director or the team', 'Two analysts are blocked waiting on a shared table from {p1}', 'The sales director has escalated directly to you'],
    constraints: ['30 minutes available', '{p1} adds checks when pushed bluntly', 'Team members are blocked and have not raised it with {p1}'],
    stakeholders: ['{p1}, a capable analyst on a first project', 'The sales director waiting on the dashboard', 'Two analysts blocked on the shared table'],
    ideal: [
      { text: 'Ask {p1} for their own read of what is holding the dashboard back before offering a view', indicator: 'COACH-E1', fact: 1 },
      { text: 'Name the specific pattern observed, three weeks of "nearly there" and unrequested filters, and its effect on the director and the two blocked analysts', indicator: 'COACH-E2', fact: 3 },
      { text: 'Agree a concrete next step {p1} owns, such as showing the current draft to the director this week, with a time to review it', indicator: 'COACH-E3', fact: 2 },
      { text: 'Adjust support to {p1}\'s confidence, for example offering to join the first walkthrough without taking over the work', indicator: 'COACH-E4', fact: 0 },
    ],
    modelAnswer: 'I would open by asking {p1} how they think the dashboard is going and what is making it hard to call it done. I would listen for whether they see the scope growing. Then I would say what I have noticed: three stand ups of "nearly there", filters the director never asked for, and two colleagues waiting on the shared table, and that the director has now written to me. I would ask what a version the director could react to this week would look like, and agree that {p1} shares the current draft with them by Thursday, with the shared table released today. I would offer to sit in on the first walkthrough if that helps, and we would review on Friday how it went.',
    weak: ['Tells {p1} exactly which filters to remove and sets the deadline without asking for their view', 'Reassures {p1} that it is fine and quality matters, leaving without an agreed date', 'Focuses on the director\'s email and pressure rather than on what {p1} can do next'],
    mcq: [{
      q: 'You have ten minutes before the one to one. Which opening best sets up the conversation?',
      options: [
        { level: 'L3', text: 'Ask {p1} how they see the project and what is making it hard to finish, then share what you have observed about the scope and the people waiting.' },
        { level: 'L2', text: 'Tell {p1} the director has escalated, ask what they need from you to ship a first version this week, and agree a date.' },
        { level: 'L1', text: 'Explain that quality matters but so do deadlines, and ask {p1} to send you the file so you can decide which filters to keep.' },
        { level: 'L0', text: 'Say the dashboard must go to the director by tomorrow as it stands, and that you will take over the shared table so the team can move.' },
      ],
    }],
  },
  {
    skillId: 'SK-COACH', tag: 'T2', difficulty: 'Low', title: 'The reluctant presenter',
    header: 'You manage a customer success team at {company}. {p2} has asked to be excused from presenting at the quarterly review.',
    situation: 'You manage a customer success team of nine at {company}. Each quarter one team member presents the account health summary to the regional leadership group. This quarter it is {p2}\'s turn. {p2} has the strongest account knowledge on the team and wrote most of the summary. This morning {p2} messaged you: "Can someone else present on Thursday? I am not good in front of that group and I would rather not." You know that six months ago {p2} presented to a smaller group and did well, though they told you afterwards they had barely slept. Leadership has started to notice {p2}\'s work and one of them asked you last week whether {p2} was ready for a senior role. You have a scheduled catch up with {p2} this afternoon. Thursday is three days away and the summary is ready.',
    prompt: 'What would you say to {p2} in this afternoon\'s catch up?',
    mcqPrompt: 'How should you respond to {p2}\'s request?',
    facts: ['{p2} wrote most of the summary and has the strongest account knowledge', '{p2} presented well to a smaller group six months ago but found it stressful', 'Leadership is noticing {p2} and asked about senior readiness', 'The presentation is in three days and the content is ready'],
    constraints: ['Three days to prepare', '{p2} has asked directly to be excused'],
    stakeholders: ['{p2}', 'The regional leadership group', 'The rest of the team who rotate through presenting'],
    ideal: [
      { text: 'Ask {p2} what specifically worries them about Thursday before suggesting anything', indicator: 'COACH-E1', fact: 1 },
      { text: 'Reflect back the specific evidence from the earlier presentation, what went well and what it cost them', indicator: 'COACH-E2', fact: 1 },
      { text: 'Agree a next step {p2} owns, such as a rehearsal on Wednesday, with a check-in after Thursday', indicator: 'COACH-E3', fact: 3 },
      { text: 'Offer support scaled to the worry, such as co-presenting the first slide or a dry run with a trusted colleague, without removing the opportunity', indicator: 'COACH-E4', fact: 2 },
    ],
    modelAnswer: 'I would start by asking {p2} what in particular worries them about Thursday, and listen. Then I would remind them of the earlier presentation, that the content landed and the questions were handled, and acknowledge it cost them sleep. I would tell them leadership is already noticing their work, and that this is a chance to be seen with the content they know best. I would ask what would make Thursday manageable and offer options: a dry run with me on Wednesday, or opening the first two minutes together. We would agree the plan, and I would check in with them on Friday about how it felt and what to do differently next time.',
    weak: ['Agrees to swap presenters to relieve the stress and moves on', 'Insists it is their turn and everyone has to do it', 'Gives a pep talk about confidence without asking what the worry is'],
    mcq: [{
      q: 'What is the most effective response to {p2}\'s message?',
      options: [
        { level: 'L3', text: 'Meet {p2} this afternoon, ask what specifically worries them, share what went well last time, and agree a rehearsal and a check-in after Thursday.' },
        { level: 'L2', text: 'Tell {p2} you would like them to present because leadership is noticing their work, and offer to do a dry run together on Wednesday.' },
        { level: 'L1', text: 'Reply that presenting is part of the rotation and everyone finds it hard, and suggest they practice in front of a mirror.' },
        { level: 'L0', text: 'Agree to swap presenters this quarter so {p2} is not stressed, and ask another team member to deliver the summary.' },
      ],
    }],
  },
  {
    skillId: 'SK-COACH', tag: 'T7', difficulty: 'High', title: 'Two coaching needs, one hour',
    header: 'You run operations for a regional distribution business. {p3}, a new shift supervisor, has had a rough month.',
    situation: 'You run operations for {company}\'s regional distribution centre. {p3} was promoted to shift supervisor two months ago from the best picker on the floor. Since then the night shift\'s error rate has doubled and two experienced pickers have asked to move to days. {p3} comes to you visibly tired and says: "I think I made a mistake taking this. I end up doing half the picking myself because it is faster than explaining, and the team still misses targets." You have seen {p3} on the floor: they step in whenever a picker slows down, and they have not run a single shift briefing. The regional head has asked you for a plan to fix night shift errors by the end of the month. You have an hour with {p3} now and you want {p3} to succeed, but the numbers cannot continue.',
    prompt: 'What would you say to {p3} in this hour? Include how you would handle the doubt they have just expressed.',
    mcqPrompt: 'What is the most useful first move in this conversation?',
    facts: ['Night shift errors have doubled since {p3} was promoted', 'Two experienced pickers have asked to move off the shift', '{p3} steps in and picks instead of supervising, and runs no shift briefings', '{p3} has expressed doubt about the role', 'The regional head wants an error plan by month end'],
    constraints: ['One hour now', 'Month end deadline from the regional head', '{p3} is tired and doubting themselves'],
    stakeholders: ['{p3}', 'The night shift pickers, including two who want to leave the shift', 'The regional head'],
    ideal: [
      { text: 'Ask {p3} what they think is driving the errors and the transfer requests, and what supervising would look like if they were not picking', indicator: 'COACH-E1', fact: 2 },
      { text: 'Name the specific behavior observed, stepping in to pick and skipping briefings, and connect it to the error rate and the pickers\' requests', indicator: 'COACH-E2', fact: 1 },
      { text: 'Agree one concrete change {p3} owns this week, such as running a ten minute briefing every shift and not picking for the first hour, with a review date before month end', indicator: 'COACH-E3', fact: 4 },
      { text: 'Address the doubt directly by adjusting support to a new supervisor, such as shadowing a briefing together, without taking the role back', indicator: 'COACH-E4', fact: 3 },
    ],
    modelAnswer: 'I would first acknowledge what {p3} said and ask them to walk me through a typical night: when they pick, when they supervise, and what they think is behind the errors and the two transfer requests. Then I would share what I have seen: that they step in whenever someone slows and have not yet run a briefing, and that the shift is missing the direction it needs from them, which is why errors and frustration are up. I would ask what a shift would look like if they did not pick at all, and agree two things for this week: a ten minute briefing at the start of every shift covering priorities and the top error type, and no picking in the first hour. I would offer to attend the first two briefings. On the doubt, I would say that the promotion was for judgment on the floor, not speed, and that we review together in two weeks with the error numbers in front of us before I answer the regional head.',
    weak: ['Accepts that the promotion was a mistake and offers to move {p3} back to picking', 'Lists the changes {p3} must make and the deadline without asking for their view', 'Focuses on the regional head\'s plan and treats {p3} as the problem to report'],
    mcq: [{
      q: '{p3} has just said they think the promotion was a mistake. What do you do first?',
      options: [
        { level: 'L3', text: 'Acknowledge it, then ask {p3} to describe a typical night and what they think drives the errors, before sharing what you have observed on the floor.' },
        { level: 'L2', text: 'Tell {p3} you have seen them picking instead of supervising and ask what would have to change for them to lead the shift instead.' },
        { level: 'L1', text: 'Reassure {p3} that every new supervisor struggles, and give them a checklist of briefings and reports to run each night.' },
        { level: 'L0', text: 'Agree that the role may not suit them and offer to move them back to picking while you find another supervisor.' },
      ],
    }],
  },
  {
    skillId: 'SK-DELEG', tag: 'T2', difficulty: 'Low', title: 'The vendor review nobody owns',
    header: 'You lead procurement at {company}. The annual review of the logistics vendor is due in three weeks and you usually run it yourself.',
    situation: 'You lead a five person procurement team at {company}. Every year you personally run the review of the main logistics vendor: pulling service data, drafting the scorecard, and leading the review meeting. This year the vendor contract renews at the same time as a system migration you are leading, and you cannot do both well. {p1}, a buyer with three years in the team, has asked twice for more visible work and sat in on last year\'s review. {p2}, your most senior buyer, has run supplier reviews before but is fully loaded on the migration with you. The review meeting is in three weeks. The finance director will attend and will want a clear recommendation on renewal terms. You have half an hour with {p1} this afternoon and you are deciding whether to hand the review over and how.',
    prompt: 'What would you do, and how would you hand the review over? Explain your reasoning.',
    mcqPrompt: 'What is the best way to handle the vendor review?',
    facts: ['The review is in three weeks and clashes with the migration you lead', '{p1} has asked for visible work and observed last year\'s review', '{p2} is experienced but fully loaded', 'The finance director expects a renewal recommendation'],
    constraints: ['Three weeks', 'You cannot do both well', 'The finance director attends'],
    stakeholders: ['{p1}', '{p2}', 'The finance director', 'The logistics vendor'],
    ideal: [
      { text: 'Hand the review to {p1} with the outcome stated: a scorecard and a renewal recommendation the finance director can act on, and why it matters', indicator: 'DELEG-E1', fact: 3 },
      { text: 'Explain why {p1} is the right person now, linking it to their request for visible work and last year\'s observation', indicator: 'DELEG-E2', fact: 1 },
      { text: 'Make explicit what {p1} can decide alone, such as the scorecard structure, and what needs you, such as the recommended terms', indicator: 'DELEG-E3', fact: 3 },
      { text: 'Set two check-ins, for example after the data pull and before the meeting, rather than reviewing every draft', indicator: 'DELEG-E4', fact: 0 },
    ],
    modelAnswer: 'I would hand the review to {p1}. I would tell them the outcome I need: a scorecard on service performance and a recommendation on renewal terms that the finance director can decide on in the meeting, and why this matters with the contract renewing. I would say why them: they asked for visible work and saw the process last year. I would set the boundaries: they decide the scorecard structure and run the vendor conversations; the recommended terms we agree together before the meeting. I would ask {p2} to be available for one hour of questions but not to own anything. We would check in twice, after the data pull in week one and three days before the meeting, and {p1} would lead the meeting with me present.',
    weak: ['Keeps the review and works evenings to fit it in', 'Hands over the task list but reviews every draft daily', 'Gives it to {p2} because they have done it before, adding to their load'],
    mcq: [{
      q: 'How should you handle the vendor review this year?',
      options: [
        { level: 'L3', text: 'Give {p1} the review with the outcome and its importance stated, clear decision rights, {p2} as a one hour advisor, and two check-ins before the meeting.' },
        { level: 'L2', text: 'Give {p1} the review, explain the finance director\'s expectations, and ask them to send you each draft so you can correct course quickly.' },
        { level: 'L1', text: 'Ask {p2} to run the review since they have done supplier reviews before, and ask {p1} to support with the data pull.' },
        { level: 'L0', text: 'Keep the review yourself since the finance director attends, and move the migration meetings to make room over the next three weeks.' },
      ],
    }],
  },
  {
    skillId: 'SK-DELEG', tag: 'T7', difficulty: 'Medium', title: 'Taking it back at the first wobble',
    header: 'You are a marketing manager at {company}. You delegated the product launch webinar to {p2} two weeks ago and the first dry run did not go well.',
    situation: 'You are a marketing manager at {company}. Two weeks ago you delegated the {product} launch webinar to {p2}, a marketing executive with strong writing skills who has never run a live event. The webinar is in nine days with 400 registrations. Yesterday\'s dry run had problems: the demo ran eight minutes long, the polling tool failed, and {p2} read from notes. The product head, who was on the dry run, has just messaged you: "Are we sure about {p2} fronting this? Happy for you to take it." You know {p2} prepared hard and was upset after the run. You also know that if the webinar goes badly, 400 prospects see it. You have a slot with {p2} in an hour and need to decide what you are going to do about ownership of the webinar.',
    prompt: 'What would you do about ownership of the webinar, and what would you say to {p2} and to the product head?',
    mcqPrompt: 'What should you do about who owns the webinar?',
    facts: ['The webinar is in nine days with 400 registrations', 'The dry run had a long demo, a failed poll and note reading', 'The product head has offered for you to take over', '{p2} prepared hard and has never run a live event'],
    constraints: ['Nine days', 'High visibility with 400 prospects', 'Pressure from the product head'],
    stakeholders: ['{p2}', 'The product head', '400 registered prospects'],
    ideal: [
      { text: 'Keep {p2} as owner and restate the outcome: a webinar that runs to time with a working demo and poll, and why it matters with 400 registrations', indicator: 'DELEG-E1', fact: 0 },
      { text: 'Match support to {p2}\'s gap in live event experience, for example a producer for the tools and a second dry run, without taking the presenter role', indicator: 'DELEG-E2', fact: 3 },
      { text: 'Make clear what {p2} decides and what triggers your involvement, such as a second failed dry run', indicator: 'DELEG-E3', fact: 1 },
      { text: 'Set check-ins proportionate to risk, such as a dry run in four days and a tech check the day before, and tell the product head this plan', indicator: 'DELEG-E4', fact: 2 },
    ],
    modelAnswer: 'I would keep {p2} as the owner. Taking it back after one dry run teaches the team that delegation ends at the first problem. In our slot I would tell {p2} the outcome has not changed: a webinar that runs to 45 minutes, with a working demo and poll, in front of 400 prospects. I would name what I saw: the demo overran, the poll failed and the script was read. Then I would ask what they need, and offer a producer to run the tools and a second dry run in four days, with a decision point: if that run has the same problems, I present and they produce. I would reply to the product head that {p2} owns it, here is the plan and the check-in dates, and I will confirm after the second run.',
    weak: ['Takes the webinar back because the stakes are too high', 'Tells {p2} to fix the demo and the poll and hopes for the best', 'Lets the product head\'s message decide and does not tell {p2} why'],
    mcq: [{
      q: 'The product head has offered for you to take over. What do you do?',
      options: [
        { level: 'L3', text: 'Keep {p2} as owner, add a producer for the tools and a second dry run with a clear decision point, and tell the product head the plan and dates.' },
        { level: 'L2', text: 'Keep {p2} as owner, tell them exactly what went wrong and ask them to fix it, and reply to the product head that you have it under control.' },
        { level: 'L1', text: 'Co-present with {p2} so you can step in live if the demo or poll fails, and let the product head know you will be on screen.' },
        { level: 'L0', text: 'Take the presenter role yourself given 400 prospects are watching, and ask {p2} to manage the slides and the chat.' },
      ],
    }],
  },
  {
    skillId: 'SK-DELEG', tag: 'T3', difficulty: 'High', title: 'The audit response with two owners',
    header: 'You are a finance controller at {company}. An internal audit response is due in ten days and two of your reports both think they own it.',
    situation: 'You are a finance controller at {company}. Internal audit has raised four findings on expense controls and a formal response is due in ten days. Two of your reports have started work on it separately. {p1}, a senior accountant, drafted the response to two findings without being asked and knows the controls deeply. {p3}, a newer analyst you are trying to develop, was told by your predecessor that audit responses were their development project and has built a tracker. Each has now asked you why the other is involved. The audit committee chair is known to reject responses that do not show a single accountable owner. You also need one of them to cover month end close, which falls in the same ten days. You have both of them in a room with you now.',
    prompt: 'What would you do to set up ownership of the audit response, and what would you say to {p1} and {p3}?',
    mcqPrompt: 'How should you set up ownership of the audit response?',
    facts: ['Four findings, response due in ten days', '{p1} knows the controls and has drafted two responses unasked', '{p3} was promised this as a development project and built a tracker', 'The audit committee expects one accountable owner', 'Month end close falls in the same window'],
    constraints: ['Ten days', 'One person must cover month end', 'Both feel ownership'],
    stakeholders: ['{p1}', '{p3}', 'The audit committee chair', 'Internal audit'],
    ideal: [
      { text: 'State the outcome for the response: four findings answered with evidence and dates, accepted by the audit committee, and why single ownership matters to them', indicator: 'DELEG-E1', fact: 3 },
      { text: 'Choose the owner on capability and development need with reasons said aloud, for example {p3} owns the response as promised with {p1} as control expert for two findings', indicator: 'DELEG-E2', fact: 2 },
      { text: 'Make decision rights explicit: who signs off the wording, who talks to audit, and who covers month end', indicator: 'DELEG-E3', fact: 4 },
      { text: 'Set a check-in rhythm tied to risk, such as a draft review on day five and a final read on day nine, rather than daily oversight', indicator: 'DELEG-E4', fact: 0 },
    ],
    modelAnswer: 'I would start by stating the outcome: a single response covering all four findings, with evidence and remediation dates, that the audit committee accepts first time, which needs one accountable owner. I would make {p3} the owner, because it was promised to them as a development project and the tracker shows they can run it, and I would say so. I would ask {p1} to be the control expert on the two findings they drafted, owning the technical accuracy while {p3} owns the document and the audit conversations. Decision rights: {p3} decides structure and dates, {p1} signs off control descriptions, I sign the final version. {p1} covers month end close. We review the draft on day five and do a final read on day nine.',
    weak: ['Splits the four findings two each so nobody feels left out', 'Takes ownership yourself because the audit committee is demanding', 'Gives it to {p1} because they know the controls and tells {p3} to focus on month end'],
    mcq: [{
      q: 'Both {p1} and {p3} believe they own the audit response. What do you do?',
      options: [
        { level: 'L3', text: 'Name one owner with the reason said aloud, give the other a defined expert role and month end, set decision rights and two review points.' },
        { level: 'L2', text: 'Make {p3} the owner as promised, ask {p1} to support on the two technical findings, and check in with them both every other day.' },
        { level: 'L1', text: 'Split the four findings between them, two each, and ask them to merge their drafts before it comes to you for sign off.' },
        { level: 'L0', text: 'Take ownership of the response yourself given the audit committee\'s expectations, and ask both to send you their material by Friday.' },
      ],
    }],
  },
  {
    skillId: 'SK-FEEDBK', tag: 'T2', difficulty: 'Low', title: 'The interrupted client call',
    header: 'You lead an account team at {company}. On yesterday\'s client call, {p1} repeatedly spoke over the client\'s procurement lead.',
    situation: 'You lead a four person account team at {company}. Yesterday you joined {p1}\'s renewal call with a key client. {p1} knows the account well and had prepared thoroughly. Three times during the call, the client\'s procurement lead started to raise a concern about invoicing and each time {p1} jumped in with an explanation before the concern was fully stated. On the third occasion the procurement lead said "let me finish" and went quiet for the rest of the call. After the call {p1} said to you, "I think that went well, I handled all their objections." The client has since emailed asking for the invoicing point to be discussed with you directly. You have a one to one with {p1} this morning. {p1} is ambitious, responds well to specifics and is not aware of the client\'s email.',
    prompt: 'What would you say to {p1} in this one to one?',
    mcqPrompt: 'How should you open the feedback conversation with {p1}?',
    facts: ['{p1} interrupted the procurement lead three times on the invoicing concern', 'The procurement lead said "let me finish" and withdrew', '{p1} believes the call went well', 'The client has asked to discuss invoicing with you directly'],
    constraints: ['{p1} is unaware of the client email', 'Renewal is in progress'],
    stakeholders: ['{p1}', 'The client\'s procurement lead', 'The renewal'],
    ideal: [
      { text: 'Describe the specific behavior: three interruptions on the invoicing point and the moment the procurement lead said "let me finish"', indicator: 'FEEDBK-E1', fact: 0 },
      { text: 'State the impact: the concern was never heard, the client withdrew and has now asked to speak to you instead', indicator: 'FEEDBK-E2', fact: 3 },
      { text: 'Ask {p1} how they saw those moments and listen before proposing a change', indicator: 'FEEDBK-E3', fact: 2 },
      { text: 'Agree what will be different on the next call, for example letting the client finish and summarizing back before responding, and how you will both know', indicator: 'FEEDBK-E4', fact: 1 },
    ],
    modelAnswer: 'I would say that the preparation showed and then move to the specific thing I want to talk about. On the invoicing point, the procurement lead started three times and each time we came in before they finished, and the third time they said "let me finish" and did not speak again. The effect is that we still do not know what the concern is, and this morning they emailed asking to discuss it with me instead. I would ask {p1} how those moments felt from their side and listen. Then I would agree one change for the next call: when the client raises a concern, let them finish, summarize it back, and only then respond. I would suggest {p1} replies to the client to book the invoicing conversation themselves, with me joining, and we debrief straight after.',
    weak: ['Says the call was fine but they should listen more in general', 'Tells {p1} about the client email as the headline and treats the interruptions as the cause of a problem to fix quickly', 'Avoids the topic because {p1} is pleased and the renewal is delicate'],
    mcq: [{
      q: 'Which opening gives {p1} the most useful feedback?',
      options: [
        { level: 'L3', text: 'Describe the three interruptions and the "let me finish" moment, state that the concern went unheard and the client has now come to you, then ask how {p1} saw it.' },
        { level: 'L2', text: 'Tell {p1} they interrupted the procurement lead several times and that the client has emailed you, and ask them to let clients finish next time.' },
        { level: 'L1', text: 'Say the call went mostly well but {p1} should work on listening skills, and suggest a course on active listening.' },
        { level: 'L0', text: 'Forward the client email to {p1} with a note to be careful with procurement leads, and take the invoicing conversation yourself.' },
      ],
    }],
  },
  {
    skillId: 'SK-FEEDBK', tag: 'T2', difficulty: 'Medium', title: 'Strong work, missed handover',
    header: 'You manage a software support team at {company}. {p2} resolved a critical incident brilliantly, then left without handing over.',
    situation: 'You manage a twelve person support team at {company}. On Tuesday night {p2}, one of your senior engineers, diagnosed and fixed a payment outage in under an hour, saving the client from a large penalty. It was excellent work and the client\'s CTO has already sent thanks. However, {p2} closed the incident at 11pm and went home without briefing the on call engineer or writing the handover note the process requires. At 6am the issue partially recurred and the on call engineer, {p3}, spent two hours rediscovering what {p2} already knew before finding {p2}\'s fix in the commit history. {p3} has told you they felt set up to fail. {p2} has a history of strong technical work and thin documentation, and you have mentioned it lightly before. You are meeting {p2} at 10am.',
    prompt: 'What would you say to {p2} at 10am? Cover both the excellent fix and the missed handover.',
    mcqPrompt: 'How should you structure the 10am conversation with {p2}?',
    facts: ['{p2} fixed a critical outage in under an hour and the client CTO sent thanks', '{p2} left without briefing on call or writing a handover note', 'The issue recurred at 6am and {p3} lost two hours rediscovering the fix', '{p3} felt set up to fail', 'Documentation has been raised lightly before'],
    constraints: ['Balance recognition with a repeated gap', 'Process requires a handover note'],
    stakeholders: ['{p2}', '{p3}', 'The client', 'The wider on call rotation'],
    ideal: [
      { text: 'Describe both specific behaviors: the fast diagnosis and fix, and closing the incident at 11pm without a briefing or handover note', indicator: 'FEEDBK-E1', fact: 1 },
      { text: 'State the impact of the gap: two hours lost at 6am and {p3} feeling set up to fail, alongside the client impact of the fix', indicator: 'FEEDBK-E2', fact: 2 },
      { text: 'Invite {p2}\'s view of the night, including why the handover did not happen, and listen', indicator: 'FEEDBK-E3', fact: 4 },
      { text: 'Agree an observable change, for example a handover note before closing any incident, and how you will notice it, given it has been raised before', indicator: 'FEEDBK-E4', fact: 4 },
    ],
    modelAnswer: 'I would start with the fix: diagnosing and resolving the payment outage in under an hour was excellent and the client CTO has said so. Then I would be equally specific about the second thing. The incident was closed at 11pm without a briefing to on call and without a handover note. At 6am it partially recurred and {p3} spent two hours rediscovering the fix before finding it in the commits, and they told me they felt set up to fail. I would ask {p2} to tell me about the end of the night and why the handover did not happen. I would say I have mentioned documentation before and this time I need an agreed change: no incident closes without a handover note and a message to on call, starting now. We would check it in the next two incident reviews, and I would ask {p2} to talk with {p3} today.',
    weak: ['Leads with praise and mentions the handover as a small footnote', 'Focuses only on the process breach and does not acknowledge the fix', 'Says "you always skip documentation" and generalizes about attitude'],
    mcq: [{
      q: 'What is the best way to give {p2} feedback on Tuesday night?',
      options: [
        { level: 'L3', text: 'Name the fast fix and its impact, then the missed handover and its cost to {p3}, ask for {p2}\'s account, and agree a handover rule you will both check.' },
        { level: 'L2', text: 'Thank {p2} for the fix, tell them the missing handover cost {p3} two hours, and ask them to write handover notes in future.' },
        { level: 'L1', text: 'Praise the fix warmly and mention that documentation could be better, since {p2} did the hard part and morale matters.' },
        { level: 'L0', text: 'Tell {p2} they always skip documentation and this time it hurt a colleague, and that it will go in their performance file.' },
      ],
    }],
  },
  {
    skillId: 'SK-FEEDBK', tag: 'T3', difficulty: 'High', title: 'Feedback to a peer who outranks you in the room',
    header: 'You are a project lead at {company}. A senior peer from another function keeps changing agreed decisions in front of your team.',
    situation: 'You lead the {product} rollout project at {company}. {p3}, a senior manager in operations who does not report to you, sits on the steering group. In the last three project meetings {p3} has reopened decisions the group had already agreed, twice in front of your team, saying "I was never comfortable with that." Each time the team has stopped work while the decision was re-debated, and two engineers have asked you privately whether the plan is real. {p3} is respected, has more tenure than you and their team will operate {product} after rollout. The next steering meeting is in two days. You have asked {p3} for 20 minutes tomorrow, and they have accepted, asking "is everything alright?" You want the working relationship intact after this conversation, because the rollout depends on it.',
    prompt: 'What would you say to {p3} in those 20 minutes?',
    mcqPrompt: 'How should you open the conversation with {p3}?',
    facts: ['{p3} reopened agreed decisions in three consecutive meetings, twice in front of the team', 'Work stopped each time and two engineers doubt the plan', '{p3} is senior, respected and their team will run {product}', 'Steering meets again in two days'],
    constraints: ['{p3} does not report to you and has more tenure', '20 minutes', 'You need {p3}\'s team to operate the product'],
    stakeholders: ['{p3}', 'Your engineers', 'The steering group', '{p3}\'s operations team'],
    ideal: [
      { text: 'Describe the specific occasions: three meetings, decisions reopened after agreement, twice in front of the team, without labeling {p3}\'s intent', indicator: 'FEEDBK-E1', fact: 0 },
      { text: 'State the impact: work stopped each time and engineers now doubt whether the plan is real', indicator: 'FEEDBK-E2', fact: 1 },
      { text: 'Ask what sits behind the discomfort and listen, since {p3}\'s team will operate the product', indicator: 'FEEDBK-E3', fact: 2 },
      { text: 'Agree a different route for concerns, for example raising them with you before the meeting, and how you will both check it worked in two days', indicator: 'FEEDBK-E4', fact: 3 },
    ],
    modelAnswer: 'I would thank {p3} for the time and say it is about how we are working together on the project. In the last three meetings, decisions the steering group had agreed were reopened, twice in front of my engineers. I would give the two examples. The effect is that work stopped each time, and two engineers have asked me whether the plan is real. I would then ask what is behind the discomfort, because {p3}\'s team will run {product} and if something is wrong I want to know before the meeting, not during it. I would listen and take the concerns seriously. Then I would propose that concerns come to me before steering so we can bring options together, and that agreed decisions are only reopened with new information. I would suggest we try it on Thursday and speak afterwards.',
    weak: ['Complains to your own manager instead of speaking to {p3}', 'Tells {p3} they are undermining you and demands it stop', 'Softens so much that the specific meetings and impact are never named'],
    mcq: [{
      q: 'You have 20 minutes with {p3}. How do you open?',
      options: [
        { level: 'L3', text: 'Describe the three meetings and the two moments in front of your team, state that work stopped and engineers doubt the plan, then ask what sits behind the discomfort.' },
        { level: 'L2', text: 'Say that decisions keep getting reopened and it is slowing the team, and ask {p3} to raise concerns with you before steering instead.' },
        { level: 'L1', text: 'Ask {p3} how they feel the project is going and hope the topic of reopened decisions comes up naturally in the conversation.' },
        { level: 'L0', text: 'Tell {p3} that reopening agreed decisions in front of your team undermines you and that you will raise it with the sponsor if it continues.' },
      ],
    }],
  },
  {
    skillId: 'SK-DIFFCON', tag: 'T2', difficulty: 'Low', title: 'The hygiene complaint',
    header: 'You supervise a shared services desk at {company}. Two colleagues have complained about a third\'s personal hygiene.',
    situation: 'You supervise a shared services desk of eight at {company}, working closely in an open plan area. Two team members have separately and awkwardly told you that {p1}\'s body odour has become hard to sit near, especially in the afternoons, and one has started booking a desk elsewhere. {p1} is a reliable colleague who cycles 40 minutes to work and has been with the company for six years. Nobody has said anything to {p1}. The two complainants have asked you not to name them. It is Thursday afternoon and there is a quiet meeting room free. You know that if you do not address it, the desk arrangement will unravel and {p1} will eventually hear it from someone less careful.',
    prompt: 'What would you say to {p1}? Speak as you would in the room.',
    mcqPrompt: 'How should you handle the complaints about {p1}?',
    facts: ['Two colleagues complained separately about body odour, one has moved desks', '{p1} is reliable, six years in the company and cycles 40 minutes to work', 'Nobody has spoken to {p1}', 'Complainants asked not to be named'],
    constraints: ['Keep the complainants anonymous', 'Private room available now'],
    stakeholders: ['{p1}', 'The two complainants', 'The desk team'],
    ideal: [
      { text: 'Open privately and get to the issue within the first sentences, saying why you are raising it, rather than circling', indicator: 'DIFFCON-E1', fact: 2 },
      { text: 'State the observation as a fact about the afternoons, likely linked to the cycle commute, and keep the source anonymous without inventing details', indicator: 'DIFFCON-E2', fact: 1 },
      { text: 'Acknowledge how uncomfortable this is to hear and {p1}\'s long, reliable record', indicator: 'DIFFCON-E3', fact: 1 },
      { text: 'Propose a practical way forward, such as shower access or a change of clothes, and confirm it stays between you', indicator: 'DIFFCON-E4', fact: 0 },
    ],
    modelAnswer: 'I would ask {p1} for five minutes in the meeting room and start directly: this is awkward and I would rather you hear it from me privately. I would say that on some afternoons there has been a noticeable body odour at the desk, that it has been raised with me, and that I think it is probably linked to the long cycle in. I would not name anyone. I would say clearly that this is not about their work, which has been reliable for six years, and that I know it is uncomfortable to hear. Then I would ask if there is anything I can help with practically, mention that the building has showers and a locker, and agree that this stays between us. I would check in casually the following week.',
    weak: ['Sends an all team email about workplace hygiene and hopes {p1} gets the hint', 'Postpones because it is awkward and moves the complainants\' desks instead', 'Tells {p1} that people are complaining about them'],
    mcq: [{
      q: 'What is the most effective response to the complaints?',
      options: [
        { level: 'L3', text: 'Speak to {p1} privately today, state the observation directly and kindly without naming anyone, acknowledge their record, and offer a practical way forward.' },
        { level: 'L2', text: 'Speak to {p1} privately, explain that some colleagues have noticed an odour issue and ask them to take care of it.' },
        { level: 'L1', text: 'Send a general reminder to the whole desk about personal presentation in shared spaces, so nobody is singled out.' },
        { level: 'L0', text: 'Move the two complainants to desks further away and monitor whether the issue comes up again before saying anything.' },
      ],
    }],
  },
  {
    skillId: 'SK-DIFFCON', tag: 'T1', difficulty: 'Medium', title: 'Telling the client the date will slip',
    header: 'You are a delivery manager at {company}. The go live date you promised a client in writing will slip by three weeks.',
    situation: 'You are a delivery manager at {company}. Six weeks ago you confirmed in writing to {p2}, the client\'s head of operations, that {product} would go live on the first of next month. Yesterday your test lead showed you the defect trend: a data migration issue means a safe go live is three weeks later. {p2} has told their board the date and has scheduled staff training around it. {p2} is direct, does not like surprises, and once ended a supplier relationship over a missed date that was communicated late. You have a regular call with {p2} in 30 minutes. Your own director has said "see if you can hold the date" but the test lead is clear that it would risk corrupting client data.',
    prompt: 'What would you say to {p2} on the call? Speak as you would say it.',
    mcqPrompt: 'How should you handle the call with {p2}?',
    facts: ['You confirmed the date in writing six weeks ago', 'A migration defect means a safe go live is three weeks later', '{p2} has committed the date to their board and scheduled training', '{p2} ended a supplier over a late communicated miss', 'Holding the date risks corrupting client data'],
    constraints: ['30 minutes until the call', 'Your director would prefer to hold the date', 'Data safety is not negotiable'],
    stakeholders: ['{p2} and their board', 'Your director', 'The client\'s staff scheduled for training'],
    ideal: [
      { text: 'Open the call with the slip and the reason in the first sentences, not at the end', indicator: 'DIFFCON-E1', fact: 1 },
      { text: 'Separate the fact, a migration defect that risks client data, from your judgment about the new date and say which is which', indicator: 'DIFFCON-E2', fact: 4 },
      { text: 'Acknowledge {p2}\'s position: the board commitment, the training schedule, and that you gave the date in writing', indicator: 'DIFFCON-E3', fact: 2 },
      { text: 'Propose a way forward with options, such as a phased go live or training on a staging system, and how you will keep {p2} informed', indicator: 'DIFFCON-E4', fact: 2 },
    ],
    modelAnswer: 'I would open with it: "{p2}, I need to start with something you will not want to hear. We cannot go live safely on the first." I would give the fact: testing found a data migration defect that, if we went live, could corrupt your records. The fix and retest take three weeks. That is the fact; my judgment is that a safe date is the twenty second, and I would rather move once than move twice. I would acknowledge that I gave the date in writing, that they have told their board and scheduled training, and that this lands on them. Then I would offer options: train on the staging system on the original dates so training holds, or a phased go live for the modules not affected. I would propose a written update they can share with their board today and a call every two days until we are live.',
    weak: ['Tries to hold the date to satisfy your director and hopes testing improves', 'Spends the first 20 minutes on status before mentioning the slip', 'Blames the client\'s data quality for the migration defect'],
    mcq: [{
      q: 'The call with {p2} starts in 30 minutes. What do you do?',
      options: [
        { level: 'L3', text: 'Open with the slip and the data safety reason, own the written commitment, acknowledge the board and training impact, and offer two concrete options and a communication plan.' },
        { level: 'L2', text: 'Explain the migration defect early in the call, tell {p2} the new date, and apologize for the impact on their board and training.' },
        { level: 'L1', text: 'Run the normal status update, then raise a risk to the go live date at the end and say you will confirm the impact next week.' },
        { level: 'L0', text: 'Hold the date as your director asked, tell {p2} everything is on track, and plan to fix the migration issue after go live.' },
      ],
    }],
  },
  {
    skillId: 'SK-DIFFCON', tag: 'T2', difficulty: 'High', title: 'The high performer who is driving people out',
    header: 'You are a sales director at {company}. Your top performer\'s behavior has cost you two team members and HR has now been contacted.',
    situation: 'You are a sales director at {company}. {p3} closed 38 percent of the region\'s revenue last year and is on track to do the same. In the last five months two account executives have resigned; both exit interviews mention {p3}: taking over their deals, publicly mocking their pipeline in team calls, and a comment about one of them "not being cut out for sales." Yesterday a third team member went to HR. HR has told you they expect you to address it directly with {p3} this week, and that a formal process may follow if it recurs. {p3} believes they are holding the team to a high standard and has said so. Your regional target depends heavily on {p3}\'s number. You have booked an hour with {p3} tomorrow, and they know HR has been involved.',
    prompt: 'What would you say to {p3} in that hour? Include how you would handle their likely reaction.',
    mcqPrompt: 'What is the right way to open the conversation with {p3}?',
    facts: ['{p3} delivers 38 percent of regional revenue', 'Two resignations cite {p3}: taking deals, public mocking, a demeaning comment', 'A third team member has gone to HR', 'HR expects a direct conversation this week and a formal process may follow', '{p3} believes they are upholding standards'],
    constraints: ['Target depends on {p3}', 'HR has set expectations', 'One hour, {p3} knows HR is involved'],
    stakeholders: ['{p3}', 'The remaining team members', 'HR', 'Your regional target'],
    ideal: [
      { text: 'Open with the purpose of the conversation and the seriousness in the first sentences, without preamble about results', indicator: 'DIFFCON-E1', fact: 3 },
      { text: 'State the facts from exit interviews and the HR complaint as facts, and your interpretation as interpretation, and say which is which', indicator: 'DIFFCON-E2', fact: 1 },
      { text: 'Acknowledge {p3}\'s results and their belief that they are upholding standards, without accepting the behavior', indicator: 'DIFFCON-E3', fact: 4 },
      { text: 'Set a clear way forward: the behaviors that stop now, what happens if they recur, and support offered, protecting both the team and the relationship', indicator: 'DIFFCON-E4', fact: 3 },
    ],
    modelAnswer: 'I would open plainly: "I want to talk about how you work with the team, and I need to say at the start that this is serious." I would lay out the facts: two exit interviews that describe you taking over deals, mocking pipelines in team calls and telling someone they were not cut out for sales, and a third colleague who went to HR yesterday. Those are the reports; my interpretation is that a standard you hold is being delivered in a way that is driving people out, and I would say the distinction. I would acknowledge the 38 percent and that they believe they are raising the bar. Then I would be clear: the public comments and taking deals stop now; if it recurs HR will open a formal process; and I will support them with a coach if they want one. If they push back that the team is weak, I would return to the specific behaviors and the resignations, not argue about standards. We would meet again in two weeks.',
    weak: ['Opens with praise for the numbers and softens the behavior into "some feedback from the team"', 'Delegates the conversation to HR to protect the relationship', 'Threatens dismissal in the first minute and gets into an argument about who is right'],
    mcq: [{
      q: 'How do you open the hour with {p3}?',
      options: [
        { level: 'L3', text: 'State the purpose and seriousness immediately, lay out the specific reports as facts, acknowledge their results and view, then set what stops now and what follows if it recurs.' },
        { level: 'L2', text: 'Explain that HR has received a complaint and two exit interviews named them, describe the behaviors, and tell them it has to change.' },
        { level: 'L1', text: 'Start with their strong results, then say some team members have found their style tough and ask them to be more supportive.' },
        { level: 'L0', text: 'Tell {p3} that HR has a case and the next incident means dismissal, and that you are not going to discuss the details.' },
      ],
    }],
  },
];
