// Ready made NanoAI templates: a brief, audience, purpose and Skills the author can start from and adjust.
export const TEMPLATES = [
  { id: 'tpl-flm', name: 'First line manager readiness', tagline: 'Coach, feed back, delegate and prioritise in a busy team', audience: 'First line managers, 12 to 24 months in role', purpose: 'readiness', skills: ['SK-COACH', 'SK-FEEDBK', 'SK-DELEG', 'SK-PRIOR'], tags: ['Managers', 'People leadership'], icon: 'people',
    brief: 'First line managers run daily stand ups, hand projects to team members and sometimes take them back too early, give feedback after customer calls and mystery shopper visits, and juggle head office requests with day to day operations when colleagues are absent.' },
  { id: 'tpl-sales', name: 'Sales negotiation drill', tagline: 'Hold value under discount pressure and influence procurement', audience: 'Account executives and account managers', purpose: 'baseline', skills: ['SK-NEGOT', 'SK-INFLU', 'SK-CUST', 'SK-COMM'], tags: ['Sales', 'Commercial'], icon: 'handshake',
    brief: 'Account managers face renewal conversations where procurement asks for 15 to 20 percent off citing a competitor quote, need to get internal teams to prioritise their client work without authority over them, handle unhappy customers who threaten to leave, and decide whether a large low margin order is worth taking.' },
  { id: 'tpl-service', name: 'Customer service recovery', tagline: 'Own the problem, fix the cause, stay honest about limits', audience: 'Customer service team leads and senior agents', purpose: 'baseline', skills: ['SK-CUST', 'SK-PROBS', 'SK-DIFFCON'], tags: ['Customer', 'Frontline'], icon: 'headset',
    brief: 'Service teams handle repeat complaints about the same billing error, customers asking for exceptions that break policy, recurring returns whose cause is unclear, and conversations where a promise made by a colleague cannot be kept.' },
  { id: 'tpl-risk', name: 'Compliance and risk judgment', tagline: 'Spot the risk, act within policy, still get the job done', audience: 'Managers in regulated operations', purpose: 'function', skills: ['SK-RISK', 'SK-DATADEC', 'SK-STAKE'], tags: ['Governance', 'Operations'], icon: 'shield',
    brief: 'Managers receive gifts from suppliers before contract signature, discover colleagues emailing customer data to personal accounts, find approvals signed after the fact under deadline pressure, and must read control dashboards to decide what to escalate.' },
  { id: 'tpl-data', name: 'Data driven team leadership', tagline: 'Read the numbers, decide in proportion, prioritise the week', audience: 'Team leads and operations supervisors', purpose: 'development', skills: ['SK-DATADEC', 'SK-PRIOR', 'SK-PROBS', 'SK-COMM'], tags: ['Analytical', 'Operations'], icon: 'chart',
    brief: 'Team leads read weekly dashboards where one region is behind or two metrics move in opposite directions, decide which of many requests to do first when short staffed, diagnose recurring operational stops, and weigh orders and cost cuts by margin rather than revenue.' },
  { id: 'tpl-change', name: 'Leading through change', tagline: 'Announce, listen, resolve conflict and keep people moving', audience: 'Department heads and senior managers', purpose: 'manager', skills: ['SK-CHANGE', 'SK-CONFL', 'SK-STAKE', 'SK-DIFFCON'], tags: ['Leadership', 'Change'], icon: 'compass',
    brief: 'Department heads announce new shift patterns and system changes their teams did not ask for, manage a restructure whose details are undecided, resolve conflict between team leads and functions, and deliver bad news to sponsors and clients before it reaches them elsewhere.' },
];
